No Recommended: Stop hiding when all posts are recommended
AprilSylph/XKit-Rewritten pull request #1008
Opened 2023-02-26 19:05 UTC by marcustyphoon

### Description

This turns No Recommended's hide recommended posts tweak off once more than (an arbitrary) 10 posts in a row are recommendations.

This prevents the endless-scrolling-enabled dashboard from continually loading new content if part of one's dash is entirely recommended posts, which appears to be happening on my account if I scroll back enough (and might be true on a new user's dash as well). This saves server load and memory, of course.

~~I think this is fine to do without any UI copy updates. A fancier version could apply a CSS style to the element with `precedingHiddenPosts(postElement) === 10` that gives it a `before` with a message about too many recommended posts to hide.~~ actually you know what here

<img width="1517"  src="https://user-images.githubusercontent.com/8336245/221431215-899e7739-e258-47aa-b1fb-73f7d15f773d.png">

### Testing steps

If your dash does the same thing as mine: scroll far enough down your dashboard that all of the posts are recommended and confirm that the UI appears as shown.

2023-03-02 20:24 UTC, marcustyphoon commented
I can't remember how Limit People is supposed to work exactly, but this technique could probably work there too? possibly?

2023-03-02 21:18 UTC, AprilSylph commented
> I can't remember how Limit People is supposed to work exactly, but this technique could probably work there too? possibly?

Basically, though with a configuration option for how many posts by the same blog is considered acceptable, and with the option to expand the hidden posts.

2023-03-03 00:56 UTC, marcustyphoon commented
Started thinking about how I would do that and realized that if it were me I would want it to interface with hide liked posts, hide seen posts, show originals, etc, which would have a complicated state machine both to work and to not have unpredictable behavior if you e.g. turned off hide seen posts or changed the show originals mode. Well, story for another time.

2023-03-21 22:52 UTC, AprilSylph requested changes

2023-03-21 22:52 UTC, AprilSylph commented on src/scripts/no_recommended/hide_recommended_posts.js
> +  return count;
I'd like comments on these. Recursion always takes me a minute to wrap my head around...

```suggestion
  // If there is no previous sibling, stop counting
  if (!previousElement) return count;
  // If the previous sibling is not a post, skip over it
  if (!previousElement.matches(postSelector)) return precedingHiddenPosts(previousElement, count);
  // If the previous sibling is hidden, count it and continue
  if (previousElement.classList.contains(hiddenClass)) return precedingHiddenPosts(previousElement, count + 1);
  // Otherwise, we've hit a non-hidden post; stop counting
  return count;
```

2023-03-21 22:57 UTC, marcustyphoon commented on src/scripts/no_recommended/hide_recommended_posts.js
> +  return count;
Yeah, for sure. Normally I try to avoid recursion entirely (see: `waitForReactLoaded`:D), but I didn't think of a clearer solution in this case.

2023-03-21 22:59 UTC, AprilSylph commented on src/scripts/no_recommended/hide_recommended_posts.js
> +  color: rgba(var(--white-on-dark), 0.6);
This might be the most annoying change I ever request but... Tumblr never uses 60% opacity colours... only 65%

```suggestion
  color: rgba(var(--white-on-dark), 0.65);
```

2023-03-21 23:33 UTC, AprilSylph approved these changes

2023-03-21 23:33 UTC, merged

2023-03-21 23:41 UTC, marcustyphoon commented
Not sure if we should consider doing things like this for other post-hiding extensions too; it kind of depends. Like, for "hide seen posts" I could see it being annoying for people trying to get farther back in their dash or whatever.