Trim Reblogs: always show trim button
AprilSylph/XKit-Rewritten pull request #1013
Opened 2023-03-02 12:05 UTC by marcustyphoon

Seeing a lot of user reports that Trim Reblogs is broken and I would really like to know if it's a button add failure or a misunderstanding about which posts should be trimmable. Hence:

### Description

As described in the linked issue, this disables the trim button on editable but untrimmable posts, rather than not adding it at all.

This uses the native dom `disabled` attribute on the button element and moves the event handlers on control buttons to the button element itself.

Resolves #958.

### Testing steps

- Confirm that e.g. Quick Tags works as expected.
- Try to press the Trim Reblogs button on an original post, a reblog with no added content and only one trail item, and a post with enough content to trim.

2023-03-02 12:07 UTC, marcustyphoon commented
(oh, and yes, I checked what happens if a user removes the disabled attribute and clicks the button; nothing bad occurs.)

2023-03-03 05:35 UTC, marcustyphoon commented
Oh, major problem with this:

 - [ ] fix quick tags popup closing when you press space

I guess you have focus of the button element once you click it and the spacebar clicks it again or something...? Not sure yet, help appreciated

2023-03-03 08:35 UTC, AprilSylph commented
> I guess you have focus of the button element once you click it and the spacebar clicks it again or something...?

Are we not stopping keydown propagation in the Quick Tags field? We should be doing that for every `<input type="text">` we add to the page

2023-03-03 08:47 UTC, marcustyphoon commented
We are; ~~I don't understand what's happening.~~ Apparently you need to preventDefault() they keyup event??????????

Possibly related:

- https://bugzilla.mozilla.org/show_bug.cgi?id=816437
- https://github.com/emberjs/ember-test-helpers/issues/1054

(testing in chrome, though)

<img width="955" src="https://user-images.githubusercontent.com/8336245/222673709-c029bfc5-915b-40c4-ac61-10b25ffa1e01.png">

2023-03-04 21:31 UTC, marcustyphoon commented
Oh, I bet I know what's happening: because I attached the handlers to the button element without changing the handlers themselves, and they reference `currentTarget`, the popups are being placed inside the `button` element instead of inside the container. Pressing spacebar inside the popup is thus pressing spacebar with the focus inside a button.

2023-03-04 22:36 UTC, AprilSylph commented
oh right, yeah, definitely do not put popups inside button elements. that's no good on multiple levels.

2023-03-20 22:32 UTC, AprilSylph requested changes
Works well with the exception that I can sneak a peak of `cursor: pointer` when hovering the very edge of a disabled button. We should attach `cursor: not-allowed` to the element that is actually disabled.

2023-03-20 22:32 UTC, AprilSylph commented on src/content_scripts/control_buttons.css
> +}
```suggestion
.xkit-control-button:disabled {
  cursor: not-allowed;
}

.xkit-control-button:disabled svg {
  fill: rgba(var(--black), 0.4);
}
```

2023-03-20 22:35 UTC, marcustyphoon commented on src/content_scripts/control_buttons.css
> +}
Ooh, good catch! I didn't think to check that in mobile view.

2023-03-20 22:37 UTC, AprilSylph approved these changes

2023-03-20 22:37 UTC, merged