Tweaks: Fix "your tags" dropdown visual issue of Unsticky Tab Bar
AprilSylph/XKit-Rewritten pull request #1029
Opened 2023-03-18 06:19 UTC by AlecBlance

### Description

Goal is to provide a fix in #968 by changing `position: static !important;` to `position: relative !important; top: 0 !important;`. 

### Testing steps

- Change `position: static !important;` to `position: relative !important; top: 0 !important;`.  https://github.com/AprilSylph/XKit-Rewritten/blob/c4a0a29d3aad83ab4dd49279fd0a9672f12907c2/src/scripts/tweaks/unsticky_tab_bar.js#L5
- Enable Unsticky Tab Bar tweak
- Go to your dashboard > your tags
- Click "filter by tags"

Confirm the fix works if it shows:

![image](https://user-images.githubusercontent.com/17378596/226088430-628363f2-1898-45dd-985b-ba2cb334a8bf.png)

2023-03-18 12:32 UTC, AprilSylph commented
(You don't need to list the changes in the PR in the testing steps, you can assume your reviewer will be running the branch you're pull-requesting)

2023-03-18 12:33 UTC, AprilSylph commented
(also @marcustyphoon you know you're allowed to review PRs too, right? :D)

2023-03-18 14:24 UTC, AlecBlance commented
> You don't need to list the changes in the PR in the testing steps, you can assume your reviewer will be running the branch you're pull-requesting

Thanks! I'm still not that familiar with github. I'll take note of this.

2023-03-25 23:49 UTC, AprilSylph requested changes
This does indeed fixed the referenced issue, but also causes a visual oddity where the tab bar will appear to jump down, and then slide back up when the tweak is first activated (or the page first loads). Overriding the `transition` property as well should remove this effect.

2023-03-25 23:50 UTC, AprilSylph reviewed
(Forgot to submit my suggestion before submitting my review...)

2023-03-25 23:50 UTC, AprilSylph commented on src/scripts/tweaks/unsticky_tab_bar.js
> +  ${keyToCss('tabsHeader')} { position: relative !important; top: 0 !important;}
```suggestion
  ${keyToCss('tabsHeader')} {
    position: relative !important;
    top: 0 !important;
    transition: none !important;
  }
```

2023-03-25 23:51 UTC, marcustyphoon commented on src/scripts/tweaks/unsticky_tab_bar.js
> +  ${keyToCss('tabsHeader')} { position: relative !important; top: 0 !important;}
See, this is why I didn't review this PR myself! :D

2023-03-26 00:17 UTC, AlecBlance commented on src/scripts/tweaks/unsticky_tab_bar.js
> +  ${keyToCss('tabsHeader')} { position: relative !important; top: 0 !important;}
I didn't notice this behavior. Thanks!

2023-03-26 21:22 UTC, AprilSylph approved these changes

2023-03-26 21:22 UTC, merged