[AccessKit] New script: normal width scroll bar in Firefox
AprilSylph/XKit-Rewritten pull request #1040
Opened 2023-03-26 23:05 UTC by michellepanzironi

### Description
  This PR aims to resolve [#1035]( https://github.com/AprilSylph/XKit-Rewritten/issues/1035) by applying `scrollbar-width: auto !important` to the root, the body, and the scrollbar-container element in blog view.  

  Originally discussed in #1021. 

### Testing steps
In Firefox, open any Tumblr page and the scrollbars default to to 12px (scrollbar-width: thin; ) instead of the standard 16px.

2023-03-28 22:06 UTC, AprilSylph requested changes
Welcome to the codebase, and thanks for picking this up!

Left a few suggestions for improvements, otherwise looks good.

2023-03-28 22:48 UTC, michellepanzironi commented on src/scripts/accesskit.css
> +body.accesskit-normal-width-scrollbar [data-testid="scroll-container"] {
Makes sense, we do want this to affect all the scrollbars.

The reason I specified was because `body.accesskit-normal-width-scrollbar div` creates a visible scrollbar on the horizontal scroll on the dashboard tab selector (see below) which is otherwise is set to `none`. 

I will need to specify something to exclude that. Would it be appropriate to try to use the `aria-label=scroll` properties to select the dashboard tabs instead? 

With:
![image](https://user-images.githubusercontent.com/41551376/228382208-5e6f1915-ca36-4872-a4ca-d8d7faeb07b5.png)

Without:
![image](https://user-images.githubusercontent.com/41551376/228382239-92bd4cc9-9c77-4135-93fa-abb6b3c93ef8.png)

2023-03-28 22:51 UTC, michellepanzironi commented
@AprilSylph Thank you for your comments. I'm happy to contribute to XKit!

2023-03-28 22:56 UTC, michellepanzironi commented on src/scripts/accesskit.css
> +body.accesskit-normal-width-scrollbar [data-testid="scroll-container"] {
Or is this actually desired behavior for this script as is? 🤔

2023-03-29 19:31 UTC, michellepanzironi commented
@AprilSylph I added this to prevent the scrollbar from showing up on the dashboard selector tabs at the top 

```
body.accesskit-normal-width-scrollbar main > div:nth-child(4) div div {
  scrollbar-width: none !important;
}

2023-03-29 19:56 UTC, AprilSylph commented
That's not stable either... again, using the same selector that Tumblr uses is always the best bet. Here, it means you can't use the static stylesheet, and will need to create a style element in the script and make use of the `keyToCss` function to target the element. I use this script to expose source names on Tumblr: https://gist.github.com/AprilSylph/511b809ffec1f4e3b8bcb4af93c1f8cd

2023-03-29 19:58 UTC, AprilSylph commented
In this case, you'll want to target `keyToCss('timelineHeaderNavInner')`.

2023-03-29 21:19 UTC, michellepanzironi commented
@marcustyphoon yes, it seems to work without the `!important`s. Will remove.

2023-03-31 21:34 UTC, AprilSylph commented
@marcustyphoon the static CSS in this PR actually doesn't use `!important`, the specificity is just higher...

- Specificity of `.WVvBo` (the rule with `scrollbar-width: none`): 0 ID, 1 CLASS, 0 TYPE
- Specificity of `body.accesskit-normal-width-scrollbar div`: 0 ID, 1 CLASS, 2 TYPE

Your line of thinking is good, though... we could cheat the specificity rules by using `:where()` to make the rule intentionally less specific! (`:where()` [always has a specificity of zero](https://developer.mozilla.org/en-US/docs/Web/CSS/:is#difference_between_is_and_where).)

2023-03-31 21:38 UTC, AprilSylph commented on src/scripts/accesskit.css
> +body.accesskit-normal-width-scrollbar div {
I think this should make the generated style element unnecessary?
Specificity of the second rule should be 0, 0, 1 if I've counted right

```suggestion
.accesskit-normal-width-scrollbar:is(html, body),
:where(.accesskit-normal-width-scrollbar) div {
```

2023-04-02 19:33 UTC, AprilSylph commented on src/scripts/accesskit.css
> +body.accesskit-normal-width-scrollbar div {
updated the suggestion and comment to make sure we actually have enough specificity to not rely on CSS insertion order 😅

2023-04-04 21:54 UTC, AprilSylph reviewed
Tested it out, and can confirm that the static CSS is now doing the job by itself! Hooray for specificity hacks :partying_face:

2023-04-04 21:54 UTC, AprilSylph commented on src/scripts/accesskit/normal_width_scrollbar.js
> +);
```suggestion
const className = 'accesskit-normal-width-scrollbar';
```

2023-04-04 21:54 UTC, AprilSylph commented on src/scripts/accesskit/normal_width_scrollbar.js
> +  document.documentElement.append(styleElement);
```suggestion
```

2023-04-04 21:54 UTC, AprilSylph commented on src/scripts/accesskit/normal_width_scrollbar.js
> +  styleElement.remove();
```suggestion
```

2023-04-05 21:35 UTC, merged