NotificationBlock: Add XKit label
AprilSylph/XKit-Rewritten pull request #1063
Opened 2023-05-06 18:16 UTC by marcustyphoon

### Description

> We’re working to add the ability to “mute” posts on the web, which will prevent future push notifications and activity items from being created about that post, until the post is unmuted. After that’s out, we’re also extending the mute functionality on all platforms to allow temporary mutes of notifications about a post.
– https://www.tumblr.com/changes/716500434236342272/friday-may-5th-2023

Due to the imminent implementation of native notification "muting," it is likely to be confusing to have multiple menu items that do essentially the same thing. This adds a label to NotificationBlock's menu item disambiguating this.

(Not sure if you plan to simply remove the script? Deleting people's lists of notifcation-blocked posts sucks, but we definitely don't want another "I use the XKit feature instead of the native one" situation.

Also, this got me thinking about putting an XKit icon on all XKit-added meatball items, again.

Also, dear whoever decided to call the native feature "muting," I have... a complaint.)

### Testing steps

2023-05-06 19:11 UTC, AprilSylph commented
I think prepending every custom meatball menu item label with `[XKit]` would be a good idea.

Also, I plan to deprecate the script rather than outright remove it (#1058). Probably gonna pick that issue up for myself unless you beat me to it.

2023-05-06 22:02 UTC, marcustyphoon commented
Yeah, I was thinking about the deprecation method too. I would be tempted to disable the ability to block notifications on new posts, even, but that's probably more trouble than it's worth.

2023-05-06 22:25 UTC, nightpool commented
it probably wouldn't be too hard to offer some sort of auto import
functionality, even today since the API appears to be finished.

On Sat, May 6, 2023, 5:02 PM marcustyphoon ***@***.***> wrote:

> Yeah, I was thinking about the deprecation method too. I would be tempted
> to disable the ability to block notifications on new posts, even, but
> that's probably more trouble than it's worth.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AprilSylph/XKit-Rewritten/pull/1063#issuecomment-1537231025>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABZCV37QG6FNXX3DQ72WLTXE3DAFANCNFSM6AAAAAAXYIZW5M>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-05-06 23:47 UTC, AprilSylph requested changes
really the direction I would like this PR to go is for the meatballs util itself to prepand `[XKit] ` to every label, but failing that:

2023-05-06 23:47 UTC, AprilSylph commented on src/scripts/notificationblock.js
> +const meatballButtonBlockLabel = 'Block notifications (XKit)';
```suggestion
const meatballButtonBlockLabel = '[XKit] Block notifications';
```

2023-05-06 23:47 UTC, AprilSylph commented on src/scripts/notificationblock.js
>  const meatballButtonUnblockLabel = 'Unblock notifications';
```suggestion
const meatballButtonUnblockLabel = '[XKit] Unblock notifications';
```

2023-05-07 00:34 UTC, marcustyphoon commented
Sure thing! Made that change. Additionally, I tried adding actual XKit Rewritten icons in #1064 and #1065, which I find cleaner. (I also tried messing with the text labels a bit, like `[XKit] ` vs `XKit: ` and setting `font-weight: normal`; none felt great to me.)

2023-05-07 09:56 UTC, AprilSylph requested changes

2023-05-07 09:56 UTC, AprilSylph commented on src/util/meatballs.js
> +}
this can just go in the meatballs stylesheet if we're not interpolating anything

2023-05-07 20:55 UTC, marcustyphoon commented on src/util/meatballs.js
> +}
oh, right

2023-05-08 21:33 UTC, AprilSylph approved these changes

2023-05-08 21:33 UTC, merged