New Tweak: Restore post links in attribution header
AprilSylph/XKit-Rewritten pull request #1084
Opened 2023-06-03 18:06 UTC by inklesspen

### Description
Tumblr recently removed the links to the actual post (and the reblogged post, if any) from the header, and [apparently intends](https://www.tumblr.com/changes/718768407758225408/tuesday-may-30th-2023) to keep this change.

However, the links are helpful for many people, so now there is a tweak which restores them.

(Note: the tweak does not attempt to remove the helpful links when disabled. Of course, they will be "removed" on next page reload.)

### Testing steps

1. Enable "Restore links to individual posts in the post header" in the Tweaks module.
2. Examine the links on the blog names in the post attribution header.

I wasn't entirely sure which arguments to use with `filterPostElements`, so I used "Hide Liked Posts" as a model. Feel free to suggest a better way.

2023-06-03 18:26 UTC, nightpool commented on src/scripts/tweaks/restore_attribution_links.js
> +const timeline = /\/v2\/timeline\/dashboard/;
Why only apply this tweak to the dashboard? I think it's helpful everywhere posts are shown.

2023-06-03 18:49 UTC, inklesspen commented on src/scripts/tweaks/restore_attribution_links.js
> +const timeline = /\/v2\/timeline\/dashboard/;
Like I said, I do not entirely understand the intended use of the arguments to `filterPostElements`, so I followed "Hide Liked Posts" as a model.

If you want to suggest a different set of arguments, please feel free.

2023-06-04 08:34 UTC, AprilSylph commented on src/scripts/tweaks/restore_attribution_links.js
> +const timeline = /\/v2\/timeline\/dashboard/;
Omitting `timeline` entirely should make the callback action on all posts.

2023-06-04 09:26 UTC, inklesspen commented on src/scripts/tweaks/restore_attribution_links.js
> +const timeline = /\/v2\/timeline\/dashboard/;
Done.

2023-06-04 17:25 UTC, inklesspen commented
Usernames in the post "trail" could also be made into links to the target post… For instance, in [this post](https://tumblr.com/inklesspen/719106819163897856), we could have not just the username and reblog source in the header, but the "neil-gaiman" in the post trail be a link (in this case to https://neil-gaiman.tumblr.com/post/717333013893087232).

Should this be folded into the same tweak, or a separate tweak?

2023-06-04 17:25 UTC, AprilSylph commented on src/scripts/tweaks/restore_attribution_links.js
> +  filterPostElements(postElements).forEach(async postElement => {
with no arguments, this becomes synonymous with...

```suggestion
  postElements.forEach(async postElement => {
```

2023-06-04 17:27 UTC, inklesspen commented on src/scripts/tweaks/restore_attribution_links.js
> +  filterPostElements(postElements).forEach(async postElement => {
Does it? Looks like filterPostElements is still doing some work:

```
postElements = postElements.map(element => element.closest(postSelector)).filter(Boolean);
```

But if that work is not necessary here, then I can drop the function call.

2023-06-04 17:28 UTC, inklesspen commented on src/scripts/tweaks/restore_attribution_links.js
> +  filterPostElements(postElements).forEach(async postElement => {
Ah, I see, postSelector is already used in the onNewPosts logic.

2023-06-04 17:29 UTC, nightpool commented
> Usernames in the post "trail" could also be made into links to the target post… For instance, in [this post](https://tumblr.com/inklesspen/719106819163897856), we could have not just the username and reblog source in the header, but the "neil-gaiman" in the post trail be a link (in this case to https://neil-gaiman.tumblr.com/post/717333013893087232).

Since this link is already accessible (by clicking on the reblog trail item header, just not on any specific blog), I'm not sure if it's necessary or is worth a tweak. It's not adding a new feature that doesn't exist, just changing things "back to how they used to be". I would suggest leaving it out for now until we see how this feature shakes out (Tumblr staff have mentioned multiple times that this change is just pt. 1 of a larger change to reblog trail items)

2023-06-04 17:30 UTC, inklesspen commented
> Since this link is already accessible

It's accessible, but requires extra steps… Still, as you say, worth waiting for now.

2023-06-04 17:44 UTC, AprilSylph reviewed
it _looks_ like we can combine some of these `querySelector` calls

2023-06-04 17:44 UTC, AprilSylph commented on src/scripts/tweaks/restore_attribution_links.js
> +const reblogAttributionSelector = keyToCss('reblogAttribution');
```suggestion
const postAttributionLinkSelector = `${keyToCss('postAttribution')} a`;
const reblogAttributionLinkSelector = `${keyToCss('reblogAttribution')} a`;
```

2023-06-04 17:44 UTC, AprilSylph commented on src/scripts/tweaks/restore_attribution_links.js
> +    const postAttributionLink = postAttribution?.querySelector('a');
```suggestion
    const postAttributionLink = postElement.querySelector(postAttributionLinkSelector);
```

2023-06-04 17:44 UTC, AprilSylph commented on src/scripts/tweaks/restore_attribution_links.js
> +    const reblogAttributionLink = reblogAttribution?.querySelector('a');
```suggestion
    const reblogAttributionLink = postElement.querySelector(reblogAttributionLinkSelector);
```

2023-06-04 17:54 UTC, inklesspen commented
> it _looks_ like we can combine some of these `querySelector` calls

Had to also change some of the `undefined` comparisons to `null`, because `querySelector` returns an element or `null`.

2023-06-06 10:10 UTC, AprilSylph requested changes
The last thing this needs is proper click behaviour for the updated links. We have an `onClickNavigate` function that can be imported and attached to hopefully override Tumblr's navigation, though you may have to attach it with [`{ capture: true }`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#options), and the function itself may need to be modified to stop propagation (which I don't think should have any adverse effects elsewhere).

If this is too tall an order, I'll try to give it a go myself tonight. Thanks for working on this!

2023-06-06 21:44 UTC, AprilSylph commented
Ah, right, these links aren't blog view URLs, so just plugging in `onClickNavigate` doesn't work at all...

2023-06-06 22:00 UTC, merged

2023-06-06 22:01 UTC, AprilSylph commented
Thanks for the contribution! This'll go out in the next release, which I guess I'll cut... tomorrow?

2023-06-06 22:03 UTC, inklesspen commented
Thanks! I wasn't sure exactly what you meant about the navigation integration (and it seemed to be working well in my local copy) but I'll check out the additional commits.

2023-06-07 09:11 UTC, AprilSylph commented
If you just modify the `href` of a link created by the Tumblr web app, clicking it normally (i.e. with no modifier keys held down) will still navigate within the app to the original link location. There's also a few cases (or at least, there were) where the `href` and navigation target are different out of the gate, e.g. a link to `https://staff.tumblr.com` will navigate to `https://www.tumblr.com/staff`.

Intercepting the click event before it reaches its target, and performing our own navigation instead is necessary to override the default behaviour. Otherwise, we would be changing the attribution links to `https://staff.tumblr.com/post/719408723730251776` but a normal click would still go to `https://www.tumblr.com/staff` instead of `https://www.tumblr.com/staff/719408723730251776`.