Vertical nav layout: Update unsticky tab bar tweak
AprilSylph/XKit-Rewritten pull request #1108
Opened 2023-06-29 20:57 UTC by marcustyphoon

### Description

Updates the unsticky tab bar tweak for the upcoming vertical nav layout.

Presumably the `newDesktopLayout` CSS class will eventually go away, at which point this will break again?

### Testing steps

2023-06-30 08:07 UTC, AprilSylph commented
It won't go away immediately, and I'll be able to tell you when the feature is ramped to 100% of users 😁

2023-07-03 21:35 UTC, AprilSylph requested changes

2023-07-03 21:35 UTC, AprilSylph commented on src/scripts/tweaks/unsticky_tab_bar.js
> +  ${keyToCss('post')} ${keyToCss('stickyContainer')} > ${keyToCss('avatar')}${keyToCss('newDesktopLayout')} { top: 14px !important; }
Could combine these into one selector with a different approach

```suggestion
  ${keyToCss('post')} ${keyToCss('stickyContainer')} > ${keyToCss('avatar')} {
    --dashboard-tabs-header-height: 0px !important;
  }
```

2023-07-03 21:46 UTC, marcustyphoon commented on src/scripts/tweaks/unsticky_tab_bar.js
> +  ${keyToCss('post')} ${keyToCss('stickyContainer')} > ${keyToCss('avatar')}${keyToCss('newDesktopLayout')} { top: 14px !important; }
oh, damn, yeah

2023-07-03 22:20 UTC, AprilSylph approved these changes

2023-07-03 22:20 UTC, merged