Timeformat: Prevent line break in relative time segment
AprilSylph/XKit-Rewritten pull request #1110
Opened 2023-06-29 21:18 UTC by marcustyphoon

### Description

<img width="297" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/1a78b88f-0179-41a9-90a7-3f3461112354">

As a minor readability/aesthetic optimization of longer Timeformat strings shown in posts that are rendered to be narrow, such as in the radar or in masonry views, this uses non-breaking spaces in the optional relative time segment.

### Testing steps

2023-08-26 21:30 UTC, AprilSylph commented
We do match the user's language for this string... are there any languages in which the relative time is too long to display on one line without overflowing?

Unfortunately, there doesn't seem to be a character that is "a space that is non-breaking unless it _really_ has to break".

Maybe the most robust thing would be to use different attributes for the absolute and relative timestamps (displaying the absolute timestamp with `::before` and the relative timestamp with `::after`) in order to set `display: inline-block` on just the relative timestamp...?

2023-09-16 05:28 UTC, marcustyphoon commented
Implemented! I have no idea if it can actually happen "naturally" or not, but I just set the font size in Palettes for Tumblr to be extremely large and it seemed to work just how we want.

2023-09-16 05:30 UTC, marcustyphoon commented
> (would like to buy non-breaking en space for the option to put the dot on the next line, pls)

I tried this with the new method and I think it looked worse.

<img width="299" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/253300b5-b1c0-48fb-9a45-c913208c1126">
<img width="301" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/d9700c91-c075-4325-bb8a-2334544c825a">

2023-09-30 21:23 UTC, AprilSylph requested changes

2023-09-30 21:23 UTC, AprilSylph commented on src/scripts/timeformat.css
> +[data-formatted-time]::before, [data-formatted-time][title]::after {
The usage of `[title]` is so that the cursor only changes if there is text to show on hover, so should be included in both selectors

```suggestion
[data-formatted-time][title]::before,
[data-formatted-time][title]::after {
```

2023-10-01 00:55 UTC, marcustyphoon commented on src/scripts/timeformat.css
> +[data-formatted-time]::before, [data-formatted-time][title]::after {
Oh, whoops, that's a typo!

2023-12-07 22:50 UTC, AprilSylph approved these changes

2023-12-07 22:51 UTC, merged