New tweaks: subtle/hidden following/mutuals indicators
AprilSylph/XKit-Rewritten pull request #1125
Opened 2023-07-08 07:54 UTC by marcustyphoon

### Description

This adds tweaks that remove the bright colors from, and outright hide, the following/mutuals indicators on activity notifications.

Resolves #1122.

### Testing steps

Confirm that the new tweaks remove the bright coloration from or hide the following/mutuals indicators on activity notifications in the activity popover modal.
Confirm that the new tweaks remove the bright coloration from or hide the following/mutuals indicators on activity notifications on the activity page.

2023-07-08 22:24 UTC, AprilSylph commented on src/scripts/tweaks/subtle_activity_mutuals.js
> +  background-color: RGB(var(--black), 0.07);
```suggestion
  background-color: RGBA(var(--black), 0.07);
```

2023-07-08 22:26 UTC, AprilSylph commented
Do we really want two new tweaks for these elements? I think if you want them visible then you want them to stand out.

2023-07-08 22:42 UTC, marcustyphoon commented
Ah, I should have figured you'd ask.

I was going to go start laying out my arguments for yes, but I realized while doing so that the "subtle" tweak doesn't really work/do anything on a bunch of the palettes, and also that the person I had seen giving feedback on the color being difficult to read was talking about something else. So, eh.

***I*** want to see them but find the green and purple quite unpleasant, so I am personally using it at the moment, but especially given the chance of user confusion with the current iteration of it, I definitely see the argument against it.

2023-07-08 22:48 UTC, AprilSylph requested changes

2023-07-08 22:48 UTC, AprilSylph commented on src/scripts/tweaks.json
> +    },
```suggestion
```

2023-07-08 22:48 UTC, AprilSylph commented on src/scripts/tweaks/subtle_activity_mutuals.js
> +export const clean = async () => styleElement.remove();
I still don't know what happens if you accept a code suggestion that removes the entire file contents. Does this result in a blank file? Is GitHub smart enough to outright delete it instead?

```suggestion
```

2023-07-08 22:49 UTC, marcustyphoon commented on src/scripts/tweaks/subtle_activity_mutuals.js
> +export const clean = async () => styleElement.remove();
Hm, let's find out!

2023-08-11 22:16 UTC, AprilSylph approved these changes

2023-08-11 22:16 UTC, merged