New tweak: Subtle following/mutuals indicators
AprilSylph/XKit-Rewritten pull request #1128
Opened 2023-07-09 01:14 UTC by marcustyphoon

<img width="401" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/10700d85-28fc-45f3-a873-be450c72663c">

Just for funsies for now. No idea how to get this to actually work properly.

---

### Description

### Testing steps

2023-07-09 01:53 UTC, marcustyphoon commented
<img width="401" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/f257f5cf-585e-4b2a-a573-904f80889a68">

"screw it, whatever. if one is already manipulating text nodes one may as well rely on `getBoundingClientRect` too"

2024-04-29 10:39 UTC, AprilSylph requested changes

2024-04-29 10:39 UTC, AprilSylph commented on src/scripts/tweaks/subtle_activity_mutuals.js
> +  overflow-x: clip;
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x#browser_compatibility

we'd need a small bump in the addon manifest for this to be reliable

- `"minimum_chrome_version"`: `"89"` &rarr; `"90"`

(don't we use `overflow: clip` in other places already? if so: WHOOPS)

2024-04-29 10:42 UTC, AprilSylph commented on src/scripts/tweaks/subtle_activity_mutuals.js
> +  overflow-x: clip;
(yes we do! fuck!!!!!)

https://github.com/AprilSylph/XKit-Rewritten/blob/e7af3451d5132f2e9165d422ccc528a6ae4b2a4c/src/scripts/shorten_posts.css#L13

2024-04-29 10:50 UTC, marcustyphoon commented on src/scripts/tweaks/subtle_activity_mutuals.js
> +  overflow-x: clip;
Apparently we thought of this! https://github.com/AprilSylph/XKit-Rewritten/pull/176#issuecomment-874297815 I'm not sure I remember how to install Chrome 89 in order to see what this code does when that rule is unsupported, though :D

2024-04-29 10:57 UTC, AprilSylph approved these changes
so nice, so smooth

2024-04-29 10:59 UTC, merged