Popup: Highlight preferences on search
AprilSylph/XKit-Rewritten pull request #1214
Opened 2023-08-17 03:06 UTC by marcustyphoon

### Description

<img width="384" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/49468712-564d-47c0-b1fa-28221533e3d5">

Implements a super-simple highlight around preference options that match the current search.

Maybe this should be a different color in dark mode? Probably. I'm not much of a dark mode user, so maybe someone could weigh in on what feels appropriate. (Honestly, I'm pretty meh on the light mode color too.)

Resolves #1111

### Testing steps

2023-08-17 03:09 UTC, marcustyphoon commented
(`font-weight: bold` is another option.)

2023-12-07 23:15 UTC, AprilSylph requested changes

2023-12-07 23:17 UTC, marcustyphoon commented on src/browser_action/popup.css
> +  --search-highlight: 255, 255, 0, 0.15;
Oh, that's very yellow when used as a highlight at 100% opacity.

2023-12-07 23:29 UTC, AprilSylph commented
Hmm, maybe the yellow highlight is too much on dark mode. Firefox highlights matching text when searching for settings with that yellow on light mode, but with `#003eaa` (RGB: `0, 62, 170`) on dark mode.

2023-12-07 23:30 UTC, marcustyphoon commented
Ah, now I remember why I had added that line to the dark mode section :D

2023-12-07 23:41 UTC, marcustyphoon commented
An option:

<img width="431" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/fa9263dd-ec96-4be7-981b-1e2d2fd4042d">


```diff
.script li.search-highlighted {
  background: rgb(var(--search-highlight));
+  border-radius: 6px;
}
```

2023-12-07 23:41 UTC, AprilSylph approved these changes

2023-12-07 23:43 UTC, AprilSylph requested changes

2023-12-07 23:43 UTC, AprilSylph commented on src/browser_action/configuration.css
> +  background: rgb(var(--search-highlight));
```suggestion
  background-color: rgb(var(--search-highlight));
```

2023-12-07 23:47 UTC, AprilSylph commented
Not sure how I feel about the rounded highlight. TBH I want to go all-in on the squareness and push up against the viewport edges but I don't remember how the padding is set up and don't want to either 1) resort to negative margins or 2) accidentally break something

I guess there aren't that many preference types to check and update, but still, I would rather review that as a separate PR.

2023-12-08 14:32 UTC, merged