Quick tags: Implement New XKit migration
AprilSylph/XKit-Rewritten pull request #1279
Opened 2023-09-12 23:57 UTC by marcustyphoon

### Description

Along with https://github.com/new-xkit/XKit/pull/2135, this is one way of implementing a button that migrates data from New XKit to XKit Rewritten when pressed. It communicates via custom events from one extension's content script to the other. 

### Testing steps

- Load the corresponding New XKit PR, e.g. via the XKit editor.
- Create at least one unique New XKit tag bundle.
- Enable Quick Tags in XKit Rewritten.
- Press the button in the New XKit Quick Tags settings pane. Confirm that the tag bundle appears in XKit Rewritten.

2023-09-13 07:56 UTC, AprilSylph requested changes
I'd like to see some sort of confirmation prompt on this side so we're not just giving storage-add access to literally anything running on Tumblr.

2023-09-13 07:59 UTC, marcustyphoon commented
Hm—now that I think about it, the success UI could be from XKit Rewritten and the failure UI could be from New XKit. No reason to do two prompts in a row.

2023-09-13 08:23 UTC, marcustyphoon commented
The New XKit control panel has `z-index: 21474836`.

This is, you know. This is cool.

2023-09-13 08:46 UTC, marcustyphoon commented
Worth noting that:
a) Maybe we could do something more general—button in New XKit that shoves over everything? That may not be ideal, though (if we add more stuff that can be imported later, that's a mess.
b) Maybe we could make the handler not inside the Quick Tags script itself, so that it could set Quick Tags to enabled when the user confirmed this import? That would be convenient for the "I am migrating from New XKit to this new thing" workflow, especially if we had more scripts with export functionality.

2024-04-29 15:41 UTC, AprilSylph requested changes
It works! I think the copy can be improved here though. The parenthesised comma-separated list of tag bundles threw me off a bit in testing.

2024-04-29 15:41 UTC, AprilSylph commented on src/scripts/quick_tags.js
> +            `(${toAdd.map(({ title }) => title).join(', ')})`
Ideal copy:

> Would you like to import the following [ x tag bundles | tag bundle ] from New XKit to XKit Rewritten?
>
> * tag bundle name
> * tag bundle name
> * etc.

2024-04-29 15:41 UTC, AprilSylph commented on src/scripts/quick_tags.js
> +        message: `Added ${toAdd.length > 1 ? `${toAdd.length} tag bundles` : 'a tag bundle'}!`,
```suggestion
        message: `Imported ${toAdd.length > 1 ? `${toAdd.length} tag bundles` : 'a tag bundle'}!`,
```

2024-04-29 15:41 UTC, AprilSylph commented on src/scripts/quick_tags.js
> +        message: 'XKit Rewritten has these tag bundles already.',
```suggestion
        message: 'Your XKit Rewritten configuration has these tag bundles already.',
```

2024-04-29 17:01 UTC, marcustyphoon commented
Any idea how to make a ul look good in otherwise-centered text?

<img width="573" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/1a4bc55a-322f-44af-b7fa-3c66bc49e7e0">

2024-04-29 21:43 UTC, AprilSylph commented on src/scripts/quick_tags.js
> +            } from New XKit to XKit Rewritten??`,
```suggestion
            } from New XKit to XKit Rewritten?`,
```

2024-04-29 21:43 UTC, AprilSylph commented on src/scripts/quick_tags.js
> +            } from New XKit to XKit Rewritten??`,
lol nice syntax highlighting there github

2024-04-29 21:57 UTC, marcustyphoon commented on src/scripts/quick_tags.js
> +            } from New XKit to XKit Rewritten??`,
Whoops.

2024-04-29 22:35 UTC, AprilSylph commented
Hmm, don't we have styles for `<table>` elements in modals already?
A single-column table would also serve as a fairly good list, I think.

2024-04-29 22:37 UTC, AprilSylph commented
Nevermind. I completely misremembered what our modal table styles looked like. Maybe not.

2024-04-29 22:38 UTC, AprilSylph commented
uhhh something something `text-align: left; display: inline-block; margin: 0 auto;`...?

I might need to play with it myself.

2024-04-30 20:56 UTC, marcustyphoon commented
idea:

- [ ] ignore case in duplicate checking logic

2024-05-06 14:15 UTC, AprilSylph approved these changes

2024-05-06 15:36 UTC, marcustyphoon commented
Every single time I check if this is off-center, and every single time it's correct. Maybe we should set a minimum width on the buttons so the gap between them centers in this case :D

<img src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/eafb9dd4-1568-4347-b1da-41e5b95a4665">

2024-05-06 15:40 UTC, merged