Mutual checker notification filter
AprilSylph/XKit-Rewritten pull request #1303
Opened 2023-10-13 23:32 UTC by zbeok

### Description

Addresses #1301 by adding a new option to only show notifications from mutuals. Added common functionality (ie: unburying notifications) to utils that may be useful to other activity page features such as Notification Block. 

### Testing steps

- Open Tumblr with Mutual Checker and notification filter enabled.
- Navigate to the activity page or trigger the popup.
- Ensure that there are no errors in console and that only mutual notifications pop up.

I'm new to contributing to open source so any and all kind feedback is welcomed!

2023-10-14 02:55 UTC, enchanted-sword commented
Beat me to it, was about to open a PR for this lol.

This is a decent solution, however it's a lot more complicated than it needs to be. Notification react props have a boolean `mutuals` property that can be used to determine if the notification is generated by a mutual without manually comparing it to the users' list of mutuals.

In addition, it probably isn't helpful to hide _all_ non-mutual notifications as this also includes things such as blaze notifications, asks, post flagging status, etc.

2023-10-14 03:24 UTC, enchanted-sword commented
One other problem that this encounters (as does my implementation, and probably the current version of NotificationBlock) is that hiding notifications this way doesn't get rid of the wrapper and dividing line between notifications, so the empty wrappers sort of stack up between notifications 
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/22856111-b7fa-4c9f-a2db-2e7aacc8b1fa)

2023-10-14 22:04 UTC, AprilSylph requested changes
not a super comprehensive review on account of the fact that i am tired and ill, sorry.

i think i like the util changes, though honestly it would be nice to split that out into another PR and make use of it in NotificationBlock (since i think that's where `unburyNotification` is from anyway?)

2023-10-14 22:04 UTC, AprilSylph commented on src/util/react_props.js
> + * @returns {Promise<object>} - The notification's buried notificationObject property
```suggestion
 * @returns {Promise<object>} - The notification's buried `notification` property
```

2023-10-14 22:04 UTC, AprilSylph commented on src/util/mutations.js
> +  addListener: callback => pageModifications.register(`${notificationSelector}`, callback),
```suggestion
  addListener: callback => pageModifications.register(notificationSelector, callback),
```

2023-10-14 22:21 UTC, enchanted-sword commented
Also, I double-checked, and notifications from mutuals seemingly aren't added to rollups, so it isn't necessary to check them.

2023-10-14 22:50 UTC, nightpool commented
@enchanted-sword this was a recently added feature, in the past 2-3 weeks.
![Screenshot_20231014-175012](https://github.com/AprilSylph/XKit-Rewritten/assets/233815/e4dc1df7-7ea8-4e94-988a-a55af51a71d3)

2023-10-15 00:09 UTC, enchanted-sword commented
> Notification react props have a boolean mutuals property that can be used to determine if the notification is generated by a mutual without manually comparing it to the users' list of mutuals.

Now that I've tested both methods more, I can definitely say that checking the `mutuals` property is a better solution performance-wise.

2023-10-15 22:22 UTC, zbeok commented
Thank you for all the feedback! I'll try to carefully incorporate all the comments, though if it's urgent to get this passed feel free to override this PR (LMK if you do) since I'm still learning the ropes and not the most fast. Regardless I'll be sure to split the util work out as well in a later separate PR as well!

2023-10-18 21:46 UTC, AprilSylph commented
This is going to need updating from upstream, now that #1306 is merged :stuck_out_tongue:

Please re-request my review via the sidebar once the conflicts are resolved!

2023-10-18 22:47 UTC, zbeok commented on src/scripts/mutual_checker.css
> +[aria-label="Notification"][data-mutual-checker-hidden],
Agree to the above, though I currently have an unsatisfactory hack to actually target the container (messy chained parentElements); I don't know what CSS selector or otherwise to target with (there's nothing like data-timeline for the notification feed). If you could suggest a different way to select I would love to know.

2023-10-19 21:42 UTC, AprilSylph commented on src/scripts/mutual_checker.css
> +[aria-label="Notification"][data-mutual-checker-hidden],
So, what we want to do here is actually move the CSS... out of the CSS file. That's what `buildStyle` is for - we create a stylesheet from inside the JS file, where all our utils like `keyToCss` are available. Then, we add and remove that stylesheet to the document in `run()` and `clean()`, respectively. There are a ton of other features that have this pattern if you go looking!

Now, since notifications can actually come in two containers (the activity popover, and the activity page), we need to target both of them. `keyToCss` has a neat trick where you can actually put in any number of keys, and get given a selector that targets all of them at the same time. So in this case, it'd be something like...

```js
const styleElement = buildStyle(`
${keyToCss('notifications', 'activityPopover')} [data-mutual-checker-hidden] {
  display: none;
}
`);
```

2023-10-19 21:44 UTC, AprilSylph commented on src/scripts/mutual_checker.css
> +[aria-label="Notification"][data-mutual-checker-hidden],
I was going to also detail how to use `.closest()` to find the wrappers without chaining `.parentElement`, but it looks like... that's not necessary anymore...? I'm not seeing borders on notifications right now...

2023-10-23 01:17 UTC, zbeok commented on src/scripts/mutual_checker.css
> +[aria-label="Notification"][data-mutual-checker-hidden],
That makes sense- I've reverted back to using `buildStyle` instead of the css page. I currently don't see the wrappers when I delete the notifications as well.

One more note though: since this was previously brought up, unless we iterate on the children of the feed itself rather than using `notificationSelectors`, date labels wouldn't be affected (leaving some dates devoid of notifications which is functionally fine but aesthetically undesirable).

2023-10-23 07:58 UTC, AprilSylph commented on src/scripts/mutual_checker.js
> +const buildCss = () => `${keyToCss('notification')}:not([data-mutuals]) { display: none !important; }`;
You can set the contents of the style element directly if they don't need to change based on preferences:

```suggestion
const styleElement = buildStyle(`${keyToCss('notification')}:not([data-mutuals]) { display: none !important; }`);
```

2023-10-23 07:58 UTC, AprilSylph commented on src/scripts/mutual_checker.js
> +    styleElement.textContent = buildCss();
```suggestion
```

2023-10-23 08:06 UTC, AprilSylph commented on src/scripts/mutual_checker.js
> +      const { mutuals } = notification || undefined;
- destructuring anything from `undefined` will throw a type error
- this `|| undefined` will never be reached because you're already testing for `notification` being truthy in the line above

if you're trying to make `mutuals` fall back to `undefined` if it doesn't exist on `notification`, that happens by default. accessing nonexistent properties in JS doesn't cause a type error, it just gives you `undefined`.

```suggestion
      const { mutuals } = notification;
```

2023-10-23 08:06 UTC, AprilSylph commented on src/scripts/mutual_checker.js
> +    // Captures the current date wrapper element before async shenanigans.
I don't see any code relating to the date wrapper here? We're just grabbing the React props and actioning on them

```suggestion
```

2023-10-23 21:50 UTC, zbeok commented
Thanks for being patient with your explanations. It's appreciated! I've amended what you've suggested.

2023-11-02 23:23 UTC, AprilSylph approved these changes
A nice addition, thank you!

2023-11-02 23:24 UTC, merged