CleanFeed: Prevent text overlapping on small images
AprilSylph/XKit-Rewritten pull request #1328
Opened 2023-11-11 02:33 UTC by enchanted-sword

### Description
Prevents the "Hidden by CleanFeed" text from overlapping on certain small images, as can be seen [here](https://www.tumblr.com/meowlgbt/733113897690775552/kitty-can-be-doggy-as-a-treat).

### Testing steps
Enable CleanFeed, add the blog in the post above to the filter list, and view the image cover

2023-11-11 02:37 UTC, marcustyphoon commented
`line-height: 1;` is equivalent, right? Might be a bit more semantic than a pixel value that happens to correspond to the font size.

2023-11-11 02:44 UTC, enchanted-sword commented
> `line-height: 1;` is equivalent, right? Might be a bit more semantic than a pixel value that happens to correspond to the font size.

True, I forgot that's a thing.

2023-11-12 00:48 UTC, AprilSylph requested changes
Thanks for figuring this one out!

2023-11-12 00:48 UTC, AprilSylph commented on src/scripts/cleanfeed.css
> +  line-height: 1;
This is _sort of_ a nitpick but I might as well require this since releases are slow...

`line-height: 1.5` is the standard for readability for "regular" sized text:

```suggestion
  line-height: 1.5;
```

2023-11-12 08:52 UTC, AprilSylph approved these changes

2023-11-12 08:53 UTC, merged