upgrade to Manifest V3
AprilSylph/XKit-Rewritten pull request #1466
Opened 2024-05-27 08:51 UTC by AprilSylph

### Description

TBD

### Testing steps

TBD

2024-05-27 22:11 UTC, marcustyphoon commented on src/utils/inject.js
> +        reject(JSON.parse(script.dataset.exception));
<img src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/a8d1cf8d-86cb-492d-a8b9-55378325e7c6">

Not the world's greatest error printout in Firefox :D Perhaps we should construct an `Error` here and throw that. Not the fault of this diff, but.

2024-05-27 22:17 UTC, marcustyphoon commented on src/utils/inject/unbury_timeline_object.js
<img src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/f78b28d1-d64e-4ffc-a6be-66c4a0f0738d">

Asynchronous inject can result in race conditions where there were previously not any. (Well, maybe this isn't what you would think of of as a race condition? Anyway, by the time the code runs, the target may not be attached to the DOM any more, e.g. if you've scrolled past it.)

Presuming we don't want to pursue instant injection, at least at the moment, this should be fairly easy to handle. I would probably just decline to run `unburyTimelineObject` and never resolve the inject promise, at first thought? That would stall the function awaiting the inject forever rather than making it have to put a conditional on the result. Not sure how garbage collection works in that case, though; we don't want to leave DOM elements un-GC'd because they have event listeners pending.

2024-05-27 22:49 UTC, marcustyphoon requested changes

2024-05-27 22:49 UTC, marcustyphoon commented on src/utils/react_props.js
>    const reactKey = Object.keys(notificationElement).find(key => key.startsWith('__reactFiber'));
<img src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/4d4c53fe-8d13-4db0-8b69-0dd4c5391843">

A forgotten migration!

2024-05-28 08:27 UTC, marcustyphoon requested changes
https://github.com/AprilSylph/XKit-Rewritten/blob/381f0235df8a827673cedf1a71b90eb89ad859c9/src/utils/react_props.js#L102

also, this one!

2024-06-06 12:58 UTC, marcustyphoon commented
What do you think about bumping to Chrome 121 for https://caniuse.com/mdn-css_properties_scrollbar-width (so we don't have a Firefox-only feature) or perhaps Chrome 117 for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/groupBy (which I found a use for in #1482)?

2024-06-16 21:20 UTC, AprilSylph commented
All features smoke-tested and working in Firefox 128.0b3.

AccessKit, PostBlock, and Tweaks tested and working in Chromium 126.0.6478.55.

Will merge with one approving review. If you'd like to test extensively on your browser of choice, please feel free to edit the PR description to reset the checklist.

2024-06-16 23:47 UTC, marcustyphoon commented
- [x] most features smoke tested in safari
- [ ] smoke test in Firefox for Android

2024-06-17 08:34 UTC, marcustyphoon commented on src/manifest.json
> +      "strict_min_version": "121.0"
Currently unable to test on Android; probably will be able to tomorrow. But will this need to be 128? Has anyone tested on 127?

2024-06-17 08:51 UTC, marcustyphoon commented
https://bugzilla.mozilla.org/show_bug.cgi?id=1889402
https://github.com/mdn/content/pull/34094

Uh. Hm. Are we supposed to request host permissions in manifest.json?

Obviously in Chromium land, no we aren't, since we only have static content scripts. But if in Firefox land we do need host permissions, and if in the future Firefox will ask the user during install if they want to grant the host permissions we request in the manifest, and if in the present Firefox will apparently unconditionally the host permissions we request in the manifest...

2024-06-18 16:26 UTC, marcustyphoon submitted a review, later dismissed
Smoke tested in Firefox for Android 126.0.1, and by "smoke tested" I mean "it took me more than ten minutes just to get web-ext to load the damn thing on a Nexus 5X and I cannot for the life of me get it to work a second time, but I think Vanilla Videos was working that one time, probably."

(Aside: if it were me, I might consider rebasing, squashing to a "rename everything without changes" commit and an "implement MV3" commit, then merge committing that, so they're separate in the repo history. Kind of a pain, but might make it easier to merge into PR branches.)

2024-06-18 16:55 UTC, marcustyphoon commented
Also tested in Firefox for Android 121.1.0.

Also tested: my patience.

2024-06-18 20:00 UTC, AprilSylph commented
> (Aside: if it were me, I might consider rebasing, squashing to a "rename everything without changes" commit and an "implement MV3" commit, then merge committing that, so they're separate in the repo history. Kind of a pain, but might make it easier to merge into PR branches.)

I could cherrypick out the renames into a separate PR, merge that, then rebase this PR with those changes already in the main branch?

2024-06-18 20:01 UTC, marcustyphoon commented
That would work! Definitely not a big deal if I had to guess.

2024-06-19 11:41 UTC, marcustyphoon commented
We could also consider setting the minimum Firefox version to at least 127, in which users [will (it seems)](https://bugzilla.mozilla.org/show_bug.cgi?id=1889402) continue to have the extension work in the background without manually granting origin permissions. I did test this using web-ext and it does seem to work in that case, while 126 requires the click.

There may be other MV3 improvements in 128, as well, but that releases 4 weeks from now and I'm not keen on delaying bugfix/feature updates for Firefox users until then-plus-however-long-it-takes-people-to-update.

2024-06-22 14:31 UTC, AprilSylph commented
hm. c9d5924 should've been included in #1507, technically. oh well.

2024-06-22 14:33 UTC, AprilSylph commented
also, to be clear, my plan for this weekend is:
1. today, get Manifest V3 merged, but not released
2. tomorrow, fix the TimelineV2 shenanigans, and _then_ do a release

2024-06-22 14:35 UTC, marcustyphoon approved these changes
Squash merged the old branch, reverted the result, squash merged this branch, merged the old revert and the new squash, got an empty diff. Conclusion: the resulting file state of this PR has not changed, and thus tests should continue to be valid.

2024-06-22 14:37 UTC, merged

2024-06-22 14:37 UTC, AprilSylph commented
Next up: time to rebase #1501.