Shorten Posts: fix avatars in Chrome, part 3
AprilSylph/XKit-Rewritten pull request #176
Opened 2021-07-02 18:57 UTC by marcustyphoon

#### User-facing changes
- Shortened posts doesn't break sticky avatars in Chrome

#### Technical explanation
- Goes back to (only using) `overflow-y: clip`, which now that [https://github.com/AprilSylph/XKit-Rewritten/commit/f6ffb57776c129d611327328af70e8211bb8a611](https://github.com/AprilSylph/XKit-Rewritten/commit/f6ffb57776c129d611327328af70e8211bb8a611) is implemented, seems to work on both browsers.

2021-07-05 11:38 UTC, AprilSylph commented on src/scripts/shorten_posts.css
> -
this is my fault for not updating the style guide, but i'm trying to use [Idiomatic CSS](https://github.com/necolas/idiomatic-css) across stylesheets now, meaning there should be blank lines between positioning and box model rules. (not a request for changes, just letting you know!)

2021-07-05 11:42 UTC, AprilSylph requested changes
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y#browser_compatibility), `overflow-y` `clip` value is only supported beginning with Chrome 90, meaning that `minimum_chrome_version` in `src/manifest.json` should be bumped accordingly.

https://github.com/AprilSylph/XKit-Rewritten/blob/a703c69397c50944f7ac1d5b82ef5410569978ad/src/manifest.json#L54

2021-07-05 19:38 UTC, marcustyphoon commented
Oh, good point. It looks like leaving in the `hidden` rule as a backup has no effect in Firefox 89/Edge 91, and causes the not-great-looking-but-functional effect in Chromium 80:

<img width="650" src="https://user-images.githubusercontent.com/8336245/124512341-f45fa180-dd8c-11eb-8e40-2a7cd91704a2.png">

It looks like there's some graphical issues in the popup in that browser, so maybe it's worth bumping the minimum version in any case, but it does function just fine!

2021-07-05 19:42 UTC, marcustyphoon commented on src/scripts/shorten_posts.css
> -
Oh right! I did see that commit when I was scrolling through to catch up, but forgot to look into it - and, I'll be honest, I don't have a great foundational grasp of CSS yet and don't instinctively know which properties would go in which category. Good motivation to look into that more!

2021-07-06 11:14 UTC, AprilSylph approved these changes

2021-07-06 11:15 UTC, merged