Add helpers to create post control buttons
AprilSylph/XKit-Rewritten pull request #19
Opened 2020-10-01 15:36 UTC by invalidCards

#### User-facing changes
- None.

#### Technical explanation
Allows developers to easily create post control buttons using the RemixIcon library that is already used throughout the extension. This includes:
- A dev script (run with Node.js) to create a JSON lookup of the SVG paths for all RemixIcon icons;
- Helper functions added to `interface.js` to look up SVG paths, create button templates, and clone the templates while adding a callback to the `click` event at the same time; 
- A global stylesheet that copies the styles used by Tumblr vanilla buttons in order to blend in as much as possible.

#### Issues this closes
None, but it is a card on the To-Do list of the Alpha project.

2020-10-02 14:53 UTC, AprilSylph requested changes
i think i'd prefer if the code consistently called them "control buttons" or "control icons" to align with Tumblr's terminology

also, i'm preferring snake_case for filenames we create... i should probably note that in `CONTRIBUTING.md` somehow

- ~~`dev/remix_svg_to_json.js`~~
- `src/footer_button.css` (actually would prefer `src/control_buttons.css` or `src/control_icons.css`)
- `src/util/remixicon_svg.json`

2020-10-02 14:53 UTC, AprilSylph commented on src/util/interface.js
> +    const queueButtonContainer = document.createElement('div');
this and `queueButtonInner` should definitely have more generic names :P

2020-10-02 15:12 UTC, invalidCards commented on src/util/interface.js
> +    const queueButtonContainer = document.createElement('div');
Whoops, I just C/P'd it from my old Quick Queue PR without looking >.<

2020-10-05 17:05 UTC, AprilSylph requested changes
code otherwise LGTM, just a couple things:
- for jsdoc `@param` tags, i prefer a hyphen to separate the description from the parameter name
- i feel like `remixicon_svg.json` should be in `lib/` since it's not really by us

2020-10-07 14:40 UTC, AprilSylph requested changes
sorry to reiterate a previous point, but the classnames still use "post button" terminology
(if you bulk-accept these suggestions i think i got all of them)

2020-10-07 14:40 UTC, AprilSylph commented on src/control_buttons.css
> +.xkit-post-button-container {
```suggestion
.xkit-control-button-container {
```

2020-10-07 14:40 UTC, AprilSylph commented on src/control_buttons.css
> +.xkit-post-button-container-span {
```suggestion
.xkit-control-button-container-span {
```

2020-10-07 14:40 UTC, AprilSylph commented on src/control_buttons.css
> +.xkit-post-button {
```suggestion
.xkit-control-button {
```

2020-10-07 14:40 UTC, AprilSylph commented on src/control_buttons.css
> +.xkit-post-button-inner {
```suggestion
.xkit-control-button-inner {
```

2020-10-07 14:40 UTC, AprilSylph commented on src/util/interface.js
> +    controlButtonContainer.classList.add('xkit-post-button-container', buttonClass);
```suggestion
    controlButtonContainer.classList.add('xkit-control-button-container', buttonClass);
```

2020-10-07 14:40 UTC, AprilSylph commented on src/util/interface.js
> +    controlButtonContainerSpan.classList.add('xkit-post-button-container-span');
```suggestion
    controlButtonContainerSpan.classList.add('xkit-control-button-container-span');
```

2020-10-07 14:40 UTC, AprilSylph commented on src/util/interface.js
> +    controlButton.classList.add('xkit-post-button');
```suggestion
    controlButton.classList.add('xkit-control-button');
```

2020-10-07 14:40 UTC, AprilSylph commented on src/util/interface.js
> +    controlButtonInner.classList.add('xkit-post-button-inner');
```suggestion
    controlButtonInner.classList.add('xkit-control-button-inner');
```

2020-10-07 14:50 UTC, invalidCards commented
That's all of them yeah, thanks

2020-10-07 14:57 UTC, AprilSylph requested changes
> for jsdoc `@param` tags, i prefer a hyphen to separate the description from the parameter name

2020-10-07 14:57 UTC, AprilSylph commented on src/util/interface.js
> +   * @param {string} cssClass The RemixIcon class of the requested icon
```suggestion
   * @param {string} cssClass - The RemixIcon class of the requested icon
```

2020-10-07 14:57 UTC, AprilSylph commented on src/util/interface.js
> +   * @param {string} buttonClass An extra class to identify the extension that added the button
```suggestion
   * @param {string} iconClass - The RemixIcon class of the requested icon
   * @param {string} buttonClass - An extra class to identify the extension that added the button
```

2020-10-07 14:57 UTC, AprilSylph commented on src/util/interface.js
> +   * @param {Function} callback A function to run when the button is clicked
```suggestion
   * @param {HTMLDivElement} template - A button template as returned by createControlButtonTemplate()
   * @param {Function} callback - A function to run when the button is clicked
```

2020-10-07 15:25 UTC, AprilSylph requested changes
hopefully my last nitpick here... i feel like these new functions warrant having their own file (`src/util/control_buttons.js`), especially since they have their own stylesheet

2020-10-12 16:54 UTC, AprilSylph requested changes

2020-10-12 16:54 UTC, AprilSylph commented on src/util/control_buttons.js
> +    const url = browser.runtime.getURL('/src/lib/remixicon-svg.json');
missed a renamed path

```suggestion
    const url = browser.runtime.getURL('/src/lib/remixicon_svg.json');
```

2020-10-12 17:13 UTC, AprilSylph commented
trying to test this out and `createControlButtonTemplate` results in a `DOMException` on Firefox 82.0b8 (64-bit)... can you reproduce?

2020-10-12 17:27 UTC, AprilSylph requested changes
`src/` and `lib/` are separate folders

2020-10-12 17:27 UTC, AprilSylph commented on dev/remix-svg-to-json.js
> +const outputPath = './src/lib/remixicon_svg.json';
```suggestion
const outputPath = './lib/remixicon_svg.json';
```

2020-10-12 17:27 UTC, AprilSylph commented on src/util/control_buttons.js
> +    const url = browser.runtime.getURL('/src/lib/remixicon_svg.json');
```suggestion
    const url = browser.runtime.getURL('/lib/remixicon_svg.json');
```

2020-10-12 18:01 UTC, invalidCards commented
They sure are

2020-10-12 18:10 UTC, AprilSylph approved these changes
tested and LGTM!

here's my working example/test script, which adds a button to posts that logs the post ID to the console when clicked. (might be useful for reference purposes)

```js
(function () {
  let controlButtonTemplate;
  const excludeClass = 'xkit-control-button-test';

  const onButtonClick = ({ target }) => {
    const post = $(target).parents('[data-id]')[0];
    console.log(post.dataset.id);
  };

  const addButtons = async function () {
    const { getPostElements } = await fakeImport('/src/util/interface.js');
    const { cloneControlButton } = await fakeImport('/src/util/control_buttons.js');

    getPostElements({ excludeClass }).forEach(postElement => {
      const controls = postElement.querySelector('footer > :last-child');
      controls.prepend(cloneControlButton(controlButtonTemplate, onButtonClick));
    });
  };

  const main = async function () {
    const { onNewPosts } = await fakeImport('/src/util/mutations.js');
    const { createControlButtonTemplate } = await fakeImport('/src/util/control_buttons.js');

    controlButtonTemplate = await createControlButtonTemplate('ri-terminal-line', 'xkit-control-button-test-button');
    onNewPosts.addListener(addButtons);

    addButtons();
  };

  const clean = async function () {
    const { onNewPosts } = await fakeImport('/src/util/mutations.js');
    onNewPosts.removeListener(addButtons);

    $(`.${excludeClass}`).removeClass(excludeClass);
    $('.xkit-control-button-test-button').remove();
  };

  return { main, clean };
})();
```

2020-10-12 18:10 UTC, merged