[AccessKit] New script: display alt text below images
AprilSylph/XKit-Rewritten pull request #194
Opened 2021-07-27 22:29 UTC by turtleseason

#### User-facing changes
Adds an option to AccessKit that displays any (non-default) image alt text in posts as a caption below the image.

#### Technical explanation
It checks for any not-yet-processed imageBlocks in onPostsMutated (skipping blocks where the image hasn't loaded yet); if the alt text isn't the default "Image" text, it inserts a caption into the block (I used figcaption since imageBlock is a figure, but div would probably work too)

Like I mentioned in #192, the styling probably needs some work, haha. I also haven't spent much time testing in Chrome yet, though a quick check in tumblr.com/search/alt+text seemed OK.

#### Issues this closes
#192

2021-07-29 14:11 UTC, AprilSylph requested changes

2021-07-29 14:11 UTC, AprilSylph commented on src/scripts/accesskit.css
> +  color: #111;
Rule no.1 of inserting elements into the webpage: remember that different palettes exist!

I get that it's not easy to figure out how to use all the different variables, though. Personally, for this sort of complimentary in-post element, I would use "black" text on a "secondary accent" background.

| True Blue | Dark Mode | Low-Contrast Classic |
|-----------|------------|----------------------|
| ![Screen Shot 2021-07-29 at 14 57 21](https://user-images.githubusercontent.com/28949509/127505429-e9ee38e9-dbd3-4043-81a0-05df570e9acf.png) | ![Screen Shot 2021-07-29 at 14 57 35](https://user-images.githubusercontent.com/28949509/127505458-ac21cf99-deb5-4cdc-97cc-77500ddf6493.png) | ![Screen Shot 2021-07-29 at 14 59 29](https://user-images.githubusercontent.com/28949509/127505494-1c1be5b3-2638-49fe-9c1d-d6672e3a58ad.png) |



```suggestion
  background-color: rgb(var(--secondary-accent));
  color: rgb(var(--black));
```

2021-07-29 14:11 UTC, AprilSylph commented on src/scripts/accesskit.css
> +  margin-top: 2px;
Personally not a fan of having a margin between the image and the alt text container. Without margin, it feels more like a captioned photo on Wikipedia, just without the outer frame.

```suggestion
```

2021-07-29 14:26 UTC, AprilSylph commented on src/scripts/accesskit/visible_alt_text.js
> +        if (image.alt && image.alt.toLowerCase() !== 'image') {
This won't work for images posted by non-English users. I feel like it would be easier to remove this check altogether rather than use the localised string though; I for one would definitely prefer to explicitly see that an image has no user-set alt text, even if only to be sure that the feature is working.

2021-07-29 14:34 UTC, AprilSylph commented
A very impressive first contribution! I hope you found the framework relatively easy to write for.

I did have a thought about simplifying this feature down to duplicating an image's alt text into its `title` attribute so that it's shown on hover, but just as I was about to suggest it, I realised it would make the feature completely unusable on devices without a cursor input...

2021-07-29 18:35 UTC, turtleseason commented on src/scripts/accesskit.css
> +  color: #111;
LOL, here I was wondering if there was some magical way to detect the current theme colors, and the variables were right in front of me the whole time... noob mistakes 😆

2021-07-29 18:49 UTC, turtleseason commented
Thanks so much for your help and feedback (and of course for all of your work on XKit)!

It did feel easy to work with (and it helped that there was a similar processing-all-images script in disable-gifs to ~~steal~~ learn from haha). I feel like I'm too much of a newbie to really judge, but the scripts seemed really clean and easy to read, I didn't have trouble finding what I needed!

2021-07-29 18:50 UTC, turtleseason commented on src/scripts/accesskit.css
> +  line-height: 1;
By the way, looking at this again, the text feels a tiny bit cramped to me - what do you think of bumping the line-height to 1.25 (and maaaybe padding to .75ch)?

2021-07-29 19:10 UTC, AprilSylph commented on src/scripts/accesskit.css
> +  line-height: 1;
Tumblr uses `line-height: 1.5;` in posts so I think it's best to just copy that. I'd have to take another look for the padding.

2021-07-29 19:22 UTC, AprilSylph commented on src/scripts/accesskit/visible_alt_text.js
> +        if (image.alt && image.alt.toLowerCase() !== 'image') {
> though on the other hand, maybe it's good that they'll get a taste of how screenreader users probably feel, haha [...] maybe it'll help motivate more people to (prod other people to) start actually using alt text in their posts

I think this is justification enough. I would love for this feature to become an educational tool on the importance of setting alt text.

> I feel like it could be irritating for people who just want to see extra information where it exists

If anyone finds it annoying enough to complain about in a discussion or issue, we can address it there and maybe change the behaviour if there's a stronger argument for ignoring the default alt text.

2021-07-29 19:25 UTC, turtleseason commented on src/scripts/accesskit.css
> +  line-height: 1;
Fair point! I was worried that using the full line spacing makes the caption look too large/take up too much space, but on second thought I'm probably just overthinking it x)

2021-07-29 19:29 UTC, AprilSylph commented on src/scripts/accesskit.css
> +  line-height: 1;
If you feel that's the case (and to be honest, I did too - I tried reducing the font weight only to realise it was at its minimum already) maybe we could reduce the `font-size` to `.875rem` (to match the post header)?

2021-07-29 19:41 UTC, turtleseason commented on src/scripts/accesskit.css
> +  line-height: 1;
I think I like that! I just made the side padding a little larger, too - `padding: .75ch 1ch`

2021-07-29 19:46 UTC, turtleseason commented
One more question btw - once all the changes are ironed out, I'm assuming I should rebase to some extent - should I flatten everything into one commit, or keep most of the history and just clean it up a little (e.g. my messing around with the spacing)?

2021-07-29 20:22 UTC, AprilSylph commented
No need! I squash every PR upon merge, so unless there are merge conflicts displayed, the finished PR will just be one clean commit at the top of the history.

2021-07-30 20:48 UTC, AprilSylph requested changes
Looking good! I was about to approve this with a note that I'd make a few tweaks before releasing the feature, but in case you end up submitting further contributions, I thought I should instead take the time to be educational.

---

Another comment I couldn't include: `className` for a custom class used across a script is maybe a little too generic. When using a classname to exclude already-processed elements I typically call it `excludeClass`, although there might be something more fitting here given that we're also using it to style elements.

2021-07-30 20:48 UTC, AprilSylph commented on src/scripts/accesskit/visible_alt_text.js
> +  [...document.querySelectorAll(`${imageBlockSelector}:not(.${className})`)]
`keyToCss` can't be relied on to produce just a single class selector. If Tumblr adds a new element with a different `imageBlock` class, this will end up as `.nonsenseOne, .nonsenseTwo:not(.accesskit-visible-alt-text)`, which won't work as intended.

Since there's no way to group selectors in CSS to achieve the desired effect with `:not()`, we can either use `keyToClasses` to only grab one classname to use, or we can do the more robust thing: filter the array instead of trying to construct a perfect selector.

```suggestion
  [...document.querySelectorAll(imageBlockSelector)]
    .filter(imageBlock => imageBlock.classList.contains(className) === false)
```

I believe it is technically more performant to use a perfect selector (browsers' CSS engines are *very* fast), but robustness has to come first.

2021-07-30 20:48 UTC, AprilSylph commented on src/scripts/accesskit/visible_alt_text.js
> +  document.querySelectorAll(`.${className}`).forEach(element => element.classList.remove(className));
Since `clean()` is only called once upon user input, we can sacrifice a bit of performance for the sake of code simplicity, and instead use jQuery to remove these modifications.

```suggestion
  $(`.${className} figcaption`).remove();
  $(`.${className}`).removeClass(className);
```

2021-07-30 21:29 UTC, turtleseason commented on src/scripts/accesskit/visible_alt_text.js
> +  [...document.querySelectorAll(`${imageBlockSelector}:not(.${className})`)]
Ooh makes sense! I guess if we really wanted to stick with CSS selectors, maybe generating a string with keyToClasses and 
```imageBlockSelector = imageBlockClasses.foreach(imageBlockClass => `${imageBlockClass}:not(.${className})`).join(', ')``` would work? Though idk if the tradeoff in readability/simplicity is worth it.

2021-07-30 21:31 UTC, turtleseason commented
> I typically call it `excludeClass`, although there might be something more fitting here given that we're also using it to style elements.

Just to throw out a couple possibilities before changing it - maybe processedClass or styledClass? (Or processed[Image]BlockClass to be a bit more descriptive)

Thanks again for taking the time to review this 🙏 Your comments have been really helpful!

2021-07-31 02:25 UTC, AprilSylph commented on src/scripts/accesskit/visible_alt_text.js
> +  [...document.querySelectorAll(`${imageBlockSelector}:not(.${className})`)]
Readability comes first, especially when the loss in performance is negligible in real-life measures. `onPostsMutated` listener triggering is debounced, after all.

I admit I do want to write some kind of function that makes creating selectors like this more feasible, but my ideas for that are still cooking.

2021-07-31 02:35 UTC, AprilSylph commented
`processedClass` looks best to me! It's not the most descriptive option, but being more verbose doesn't seem useful enough in this case to justify having such a painfully long constant name.

2021-08-02 14:46 UTC, AprilSylph approved these changes
A great feature idea, and beautifully executed! It's been a joy to review this. Thank you for your contribution!

2021-08-02 14:46 UTC, merged

2021-08-02 15:33 UTC, marcustyphoon commented
Wonderful! I love this.

2021-08-02 15:37 UTC, marcustyphoon commented on src/scripts/accesskit/visible_alt_text.js
> +        if (image.alt && image.alt.toLowerCase() !== 'image') {
I had the same thoughts as discussed here. I did think, additionally, about whether the localized version of "Image" should have some kind of special handling - something like being faded, being italic, being slightly smaller, being replaced by "no alt text," etc. Probably not worth the extra lines of code, but I figured I'd mention the idea!