New script: Shrink posts in queue/drafts
AprilSylph/XKit-Rewritten pull request #221
Opened 2021-09-02 21:23 UTC by marcustyphoon

Okay so first off, I have no idea what you would call this script.

#### User-facing changes
Adds a script to [shrink/collapse/condense/whatever] posts in your queue, and optionally drafts, between the header and footer. Makes it easier to rearrange your queue. Is an excuse to use CSS box shadows.

Previously a function of Enhanced Queue/Queue+. (Shuffling your queue is now built in to Tumblr; clearing your queue will presumably be in mass deleter.)

#### Technical explanation
Had the code lying around from learning the Rewritten framework. Figured I'd update it to learn the changes to the framework since then.

The JQuery is a nightmare and needs a rewrite. The CSS is... kind of a nightmare and kind of needs a rewrite.

#### Issues this closes
None, but I think somebody requested it back when XK7 wasn't abandonware.

2021-09-20 21:20 UTC, lihatt commented
I used to use this feature all the time and would be delighted to have this back in XKit.

2021-12-01 10:41 UTC, AprilSylph commented
> In order to place a shadow within (over) the shrunk post content, an absolutely positioned element with a positioned parent of the correct size is needed. I don't know how to do this with less than 3 DOM elements.

What you can (probably) do is use [CSS pseudo-elements](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements) to be less invasive with DOM manipulation. Any `::before` or `::after` pseudo-elements count as children of their targets, so you can make the target `position: relative;` and the pseudo-element `position: absolute;` to get a fully-stylable absolutely-positioned new child.

```diff
- .xkit-queue-shadow-outer { position: relative; }
- .xkit-queue-shadow { position: absolute; }
+ .xkit-queue-shadow { position: relative; }
+ .xkit-queue-shadow::before { position: absolute; }
```

Not sure if you could put the pseudo-element on the scroll container, it might use the container height instead of the content height, but then again it might not scroll with the content because of its positioning...

P.S. Sorry for taking so long to get to reviewing this!

2021-12-05 06:18 UTC, marcustyphoon commented
Oh, riiiight, those things! They've always confused me but seemed really useful to learn.

2022-01-17 09:27 UTC, AprilSylph requested changes
Otherwise LGTM!

2022-01-17 09:27 UTC, AprilSylph commented on src/scripts/collapsed_queue.js
> +  timelineRegex = new RegExp(String.raw`\/v2\/blog\/[^/]+\/posts\/(${regexGroup})`);
Since we're using the `RegExp` constructor rather than literal notation, these forward-slashes don't need to be escaped. They have no special meaning in regular expressions themselves.

```suggestion
  timelineRegex = new RegExp(String.raw`/v2/blog/[^/]+/posts/(${regexGroup})`);
```

2022-01-17 09:53 UTC, marcustyphoon commented on src/scripts/collapsed_queue.js
> +  timelineRegex = new RegExp(String.raw`\/v2\/blog\/[^/]+\/posts\/(${regexGroup})`);
Oh, man, I'm still not used to wrapping my brain around the difference between "what you have to type to create a regex" and "the characters that make up the regex" :D The `String.raw` call should be unnecessary as well, then, if I'm understanding correctly.

2022-01-17 10:05 UTC, AprilSylph approved these changes

2022-01-17 10:05 UTC, merged