new script: Mutual Checker
AprilSylph/XKit-Rewritten pull request #25
Opened 2020-10-09 05:14 UTC by marcustyphoon

#### User-facing changes
Ports the Mutual Checker extension from XKit 7.

#### Technical explanation
This finds the author of each post, checks if that author is following the user's main blog or a selected one of their sideblogs via an api call, and prepends an icon to the author's name if so.

Posts by mutuals get a `from-mutual` class that other extensions could make use of.

#### Issues this closes
n/a

2020-10-09 14:07 UTC, AprilSylph requested changes
my original XKit sin has come back to haunt me...

the filename (and thus also entry in the scripts index) should be snake_case for consistency
(`mutualchecker` &rarr; `mutual_checker`)

2020-10-16 17:08 UTC, AprilSylph requested changes
since Mutual Checker only does the one thing, and you're already clearing `mutuals` in `main()`, you could cut out `onStorageChanged()` and just use [`autoRestart: true`](https://github.com/AprilSylph/XKit-Rewritten/blob/master/docs/framework.md#autorestart) here

2020-10-16 17:08 UTC, AprilSylph commented on src/scripts/mutual_checker.js
> +  };
```suggestion
```

2020-10-16 17:08 UTC, AprilSylph commented on src/scripts/mutual_checker.js
> +
```suggestion
```

2020-10-16 17:08 UTC, AprilSylph commented on src/scripts/mutual_checker.js
> +    browser.storage.onChanged.removeListener(onStorageChanged);
```suggestion
```

2020-10-16 17:08 UTC, AprilSylph commented on src/scripts/mutual_checker.js
> +  return { main, clean, stylesheet: true };
```suggestion
  return { main, clean, stylesheet: true, autoRestart: true };
```

2020-10-16 17:11 UTC, AprilSylph commented on src/scripts/mutual_checker.json
> +  }
this makes me feel uneasy... i see that you've included some verification logic, but i think simply not obeying a preference is something to be avoided

2020-10-16 19:00 UTC, marcustyphoon commented on src/scripts/mutual_checker.json
> +  }
Yeah, 100% agreed, I really don't like it either. Given that the preferences page has (if I understand correctly) no ability to get information from the main extension or the tumblr window, any ideas how to make this work elegantly? Removing the ability to select no-primary blogs seems quite limiting but is definitely an option, making it a sidebar toggle seems a bit silly, and adding buttons to some part of the tumblr UI that lists every one of your blogs... could work maybe?

2020-10-16 20:51 UTC, AprilSylph commented on src/scripts/mutual_checker.json
> +  }
for now i think i'd prefer to go with only checking the primary blog. i'm fairly sure i would put sideblog-checking back in eventually when i figure out the most elegant way to do it, but for now it seems more important to get the basic feature in without any attached mess

2020-10-19 17:19 UTC, AprilSylph requested changes
this is looking great, and it works beautifully! i think these are my last nitpicks before merging - i'm very happy to have this feature back. thank you again!

2020-10-19 17:19 UTC, AprilSylph commented on src/scripts/mutual_checker.js
> +    getPostElements({ excludeClass, noPeepr: true }).forEach(async postElement => {
i think it makes more sense to process filtered posts since the header is visible at first
(this isn't perfect since our changes to the header are lost upon expanding, but hopefully i'll figure something out to deal with that)

```suggestion
    getPostElements({ excludeClass, noPeepr: true, includeFiltered: true }).forEach(async postElement => {
```

2020-10-19 17:19 UTC, AprilSylph commented on src/scripts/mutual_checker.css
> +	vertical-align: text-bottom;
> **vertical-align** has no effect on this element since it’s not an inline or table-cell element.

since this ends up as a flex item, you'd need to instead use `align-self` to vertically position it. i think it looks best as it is, though
```suggestion
```

2020-10-19 17:19 UTC, AprilSylph commented on src/scripts/mutual_checker.css
> +	padding-right: 0.3em;
personal nitpick
```suggestion
	margin-right: 0.5ch;
```

2020-10-19 17:32 UTC, marcustyphoon commented
Hm, not sure if filtered posts are actually working at the moment, but I haven't looked into why yet!

2020-10-19 17:33 UTC, AprilSylph commented
they're working for me
![image](https://user-images.githubusercontent.com/28949509/96491074-a2e0a800-1239-11eb-992c-3f8e6d6d02b6.png)

2020-10-19 17:34 UTC, marcustyphoon commented
Ah never mind, pulled the wrong repo, whoops :S

2020-10-19 17:35 UTC, AprilSylph approved these changes

2020-10-19 17:35 UTC, merged