Add line separator tweak
AprilSylph/XKit-Rewritten pull request #295
Opened 2021-10-02 13:35 UTC by invalidCards

#### User-facing changes
- Adds a tweak to turn the "You're caught up" section into a simple line separator.
![image](https://user-images.githubusercontent.com/842080/135718595-20623740-4868-4be2-ad7a-1bc9f73a86ce.png)

#### Technical explanation
Completely hides the "You're caught up" title and turns the carousel into a 0px-high element with a 4 pixel top border that is coloured with the `white-on-dark` variable (which makes it visible in every default theme, at least).

#### Issues this closes
None necessarily, but it might be a (temporary) alternative to the proposed solution in #251.

2021-10-02 13:47 UTC, AprilSylph requested changes

2021-10-02 13:47 UTC, AprilSylph commented on src/scripts/tweaks.json
> +}
Nitpick: newline at end of file is preferred

```suggestion
}

```

I recommend setting up EditorConfig!

2021-10-02 13:54 UTC, AprilSylph commented on src/scripts/tweaks/caught_up_line.js
> +      carouselWrapper?.closest(listTimelineObjectSelector)?.previousElementSibling.classList.add(hiddenClass);
do we need to action on `carouselWrapper`? couldn't we just go straight to the closest `listTimelineObject`, eliminating the need to use `closest()` twice?

2021-10-02 13:54 UTC, AprilSylph commented on src/scripts/tweaks/caught_up_line.js
> +  .${hiddenClass} { display: none; }
I believe this would reintroduce the K-to-top bug. The recommended tag carousel option in No Recommended uses `.${hiddenClass} > div { display: none; }`.

2021-10-02 14:06 UTC, AprilSylph commented on src/scripts/tweaks/caught_up_line.js
> +      carouselWrapper?.closest(listTimelineObjectSelector)?.previousElementSibling.classList.add(hiddenClass);
looking at https://github.com/AprilSylph/XKit-Rewritten/blob/f41443311d0fe02c6935993f073ac89ff9f7a15d/src/scripts/no_recommended/hide_tag_carousels.js#L13-L21 more closely, i think we do want to use `carouselWrapper` but the other way round.

targeting every `tagChicletCarouselItem` and then mapping them to their closest `carouselWrapper` will give us an array full of duplicate items, while targeting every `carouselWrapper` and then filtering only to those with `tagChicletCarouselItem` descendants will give us an array of only unique items we need to action on.

the filtering does use `querySelector` though so repeat actioning per tag chiclet might actually be actually more performant? maybe @marcustyphoon has the answer.

2021-10-02 14:10 UTC, AprilSylph commented on src/scripts/tweaks/caught_up_line.js
> +      carouselWrapper?.closest(listTimelineObjectSelector)?.previousElementSibling.classList.add(hiddenClass);
i'm going to go all-in with the assumption that filtering the array down to unique items is going to be more performant, but i'm fine handling that myself.

2021-10-02 14:22 UTC, AprilSylph reviewed
Otherwise seems fine, will test and hopefully approve on Monday

2021-10-02 14:22 UTC, AprilSylph commented on src/scripts/tweaks/caught_up_line.js
> +    .map(tagChicletCarouselItem => tagChicletCarouselItem.closest(listTimelineObjectSelector))
```suggestion
    .map(tagChicletCarouselItem => tagChicletCarouselItem.closest(listTimelineObjectSelector))
    .filter((element, index, array) => array.indexOf(element) === index)
```

Does this work? This seems to be the easiest way to remove duplicate items from an array without interrupting the chain, but I'm not at liberty to test its implementation today.

2021-10-02 19:26 UTC, marcustyphoon commented on src/scripts/tweaks/caught_up_line.js
> +    .map(tagChicletCarouselItem => tagChicletCarouselItem.closest(listTimelineObjectSelector))
I don't think it'll make a performance difference (anything run once in onNewPosts will be 0ms) but it's a fun little Javascript problem to solve!

`new Set(items.map(/* */).forEach(/* */)` is probably the clearest way semantically, given that the reader knows what an ES6 Set does.

2021-10-04 10:42 UTC, AprilSylph commented on src/scripts/tweaks/caught_up_line.js
> +  .${borderClass} > div > div { border-top: 4px solid rgb(var(--white-on-dark)); height: 0px; }
i think it would be cleaner to just target the first `div` and set `overflow-y: hidden;` explicitly rather than relying on Tumblr's carousel CSS
```suggestion
  .${borderClass} > div {
    box-sizing: content-box;
    height: 0px;
    overflow-y: hidden;
    border-top: 4px solid rgb(var(--white-on-dark));
  }
```

2021-10-04 10:47 UTC, AprilSylph approved these changes

2021-10-04 10:47 UTC, merged