Show Originals: Ensure user can scroll
AprilSylph/XKit-Rewritten pull request #307
Opened 2021-10-09 08:12 UTC by marcustyphoon

#### User-facing changes

In rare cases with large displays, Show Originals could result in a user's timeline rendering as short enough vertically that it fits in the browser viewport, resulting in nowhere to scroll to trigger infinite scrolling. This ensures this does not happen.

#### Technical explanation

The timeline is set to a minimum height of 100vh, or 100% of the browser viewport height, if it does not contain pagination controls. It is not right at the top of the page, so this always results in the page height being at least a bit taller than the viewport.

Duplicating `/v2/timeline/dashboard` as both string and regex doesn't feel very DRY. `getPostElements` could be overloaded to take a string for its `timeline` prop but I remember you preferring to avoid `typeof`.

#### Issues this closes
None, but discussed in discussion #107

2021-11-04 14:39 UTC, AprilSylph requested changes
> Duplicating `/v2/timeline/dashboard` as both string and regex doesn't feel very DRY. `getPostElements` could be overloaded to take a string for its `timeline` prop but I remember you preferring to avoid `typeof`.

i believe you could reduce repetition by constructing the regex from the string, at least

2021-11-04 14:39 UTC, AprilSylph commented on src/scripts/show_originals.js
> +const dashboardTimeline = '/v2/timeline/dashboard';
```suggestion
const dashboardTimeline = '/v2/timeline/dashboard';
const dashboardTimelineRegExp = new RegExp(dashboardTimeline);
```

2021-11-04 14:39 UTC, AprilSylph commented on src/scripts/show_originals.js
>    getPostElements({ excludeClass, timeline: /\/v2\/timeline\/dashboard/, includeFiltered: true }).forEach(async postElement => {
```suggestion
  getPostElements({ excludeClass, timeline: dashboardTimelineRegExp, includeFiltered: true }).forEach(async postElement => {
```

2021-11-04 17:43 UTC, marcustyphoon commented
I... cannot believe I assumed that would not work because of the required escape characters :D

2021-11-05 16:14 UTC, AprilSylph approved these changes

2021-11-05 16:15 UTC, merged