Show Originals: Run in additional locations (WIP)
AprilSylph/XKit-Rewritten pull request #349
Opened 2021-12-05 08:03 UTC by marcustyphoon

Todo: write description

```
#### User-facing changes
- 

#### Technical explanation

#### Issues this closes
```

2021-12-05 08:15 UTC, marcustyphoon commented
Discussion: do you think it makes sense to move the logic of when Show Originals should or should not run from a regex in `getPostElements` to a class that is conditionally added to the timeline?

What makes it difficult to clearly specify the intent, with the current system, is that the `timeline` attribute `/v2/blog/blognamegoeshere/posts` is essentially the same when viewing other people's blogs in Peepr and when viewing your own blog's posts. Hence, one regex does not suffice to target "only Peepr."

The two options I can think of to make this clear are
a) adding an "onlyPeepr" flag to `getPostElements` and combining the results of multiple `getPostElements` calls together per the user's settings, or 
b) not using the filtering options in `getPostElements`, and simply determining once per timeline whether Show Originals should be active or not (e.g. `timelineElement.closest('[role="dialog"]') !== null` means we're in Peepr).

The commit above implements the second one, but I'm honestly not sure which makes more sense/is more clear.

2022-01-29 07:17 UTC, marcustyphoon commented
If this topic engenders more than a cursory discussion, I'm glad to make it a github discussion or separate PR once this is merged, but: any opinion on adding some kind of visual indicator to timelines that this script affects? We do have "Original Posts" in `window.tumblr.translations`, which isn't terrible UI copy. 

(I would have made it a separate PR already, but it would obviously merge conflict with this one, and rebasing it would decouple the comment history from the comment thread, at which point I figured it was cleaner not to.)

2022-02-07 13:06 UTC, AprilSylph commented on src/scripts/show_originals.json
> +      "label": "Run in [user friendly description of Peepr goes here]",
hopefully the phrase "blog view" will clearly refer to `/blog/view`

```suggestion
      "label": "Run on the blog view drawer",
```

2022-02-07 13:18 UTC, AprilSylph requested changes

2022-02-07 13:18 UTC, AprilSylph commented on src/scripts/show_originals.js
> +  const paginationCss = await keyToCss('manualPaginatorButtons');
```suggestion
  const paginatorSelector = await keyToCss('manualPaginatorButtons');
```

this makes me realise how poorly-named `keyToCss` is. will have to do a repo-wide search and replace sometime

2022-02-07 13:18 UTC, AprilSylph commented on src/scripts/show_originals.js
> +  if (!timeline.querySelector(paginationCss)) {
```suggestion
  if (!timeline.querySelector(paginatorSelector)) {
```

2022-02-07 13:18 UTC, AprilSylph commented on src/scripts/show_originals.js
> +        timeline.dataset.which === 'blog_subscriptions';
I would like multiple conditions to follow the philosophy of our array/object newline rules; either nothing gets its own line, or everything does

```suggestion
      const onBlogSubscriptions =
        timeline.dataset.timeline === '/v2/timeline' &&
        timeline.dataset.which === 'blog_subscriptions';
```

2022-02-07 13:23 UTC, marcustyphoon commented on src/scripts/show_originals.js
> +  const paginationCss = await keyToCss('manualPaginatorButtons');
Yeah, agreed. I was trying to think of something extremely short that would be sufficiently clear because of how it now gets used inline with resolveExpressions so much.

2022-02-07 13:30 UTC, AprilSylph commented on src/scripts/show_originals.js
> +  const paginationCss = await keyToCss('manualPaginatorButtons');
Oh, that's a factor I hadn't considered. I was thinking `keyToSelector`, but that would be clunky written out multiple times in the same line.

Considering what `keyToCss` returns now, how about `keyToIs`? Not sure if that's too esoteric.

2022-02-07 13:33 UTC, AprilSylph commented on src/scripts/show_originals.js
> +    .filter(postElement => postElement.closest('[data-timeline]').classList.contains(activeTimelineClass));
Would there be a performance draw from changing this to

```suggestion
    .filter(postElement => postElement.matches(`[data-timeline].${activeTimelineClass} div');
```

?

2022-02-07 13:46 UTC, marcustyphoon commented on src/scripts/show_originals.js
> +  const paginationCss = await keyToCss('manualPaginatorButtons');
Hmm... yeah, that feels a bit too esoteric imo, not that I have any great ideas. I would assume that didn't do the translation step, just converted an array of classes to an is selector.

`import { cssMap } from '../util/css_map.js';` - kinda cute; kinda weird to have to rename the storage variable inside the module
`import { obfuscate } from '../util/css_map.js';` - fairly obscure
`import { map } from '../util/css_map.js';` - nice if you only ever use it inline in a template string that is obviously going to be a stylesheet; very strange in other contexts

I guess there's always
```js
export const keyToSelector = /* */;
export const map = keyToSelector;
```

or making a pattern of using `import { keyToSelector as map } from '../util/css_map.js';` where relevant, but... I dunno

2022-02-07 14:03 UTC, marcustyphoon commented on src/scripts/show_originals.js
> +    .filter(postElement => postElement.closest('[data-timeline]').classList.contains(activeTimelineClass));
Shouldn't make any difference :) Anything that gets run like 10 times can be done however; it's the querySelectors that get run in some fashion on like 30,000 DOM nodes where performance becomes at all significant!

2022-02-07 14:07 UTC, marcustyphoon commented on src/scripts/show_originals.js
> +    .filter(postElement => postElement.closest('[data-timeline]').classList.contains(activeTimelineClass));
Oh, the other thought I had that's sort of related to this is that, in theory, you could skip this check entirely, run the extension on every timeline, and just change the selector to `${activeClass} ${hiddenClass} article { display: none; }` or whatever. Can't really think of a reason to do it that way, but it's probably a possibility for all of the exposeTimelines scripts.

2022-02-08 13:45 UTC, AprilSylph approved these changes

2022-02-08 13:45 UTC, merged