Start to attempt to make quick actions
AprilSylph/XKit-Rewritten pull request #4
Opened 2020-08-15 12:15 UTC by invalidCards

It looks promising! But the POST request to reblog the post isn't working for some godforsaken reason. I intend to come back to this at some point, but feel free to have a poke and see what works.

Other things to do:
- Make the "create a button in the control area of a post" a generic utility function
- Quick drafting
- Preference change listener

2020-08-20 16:36 UTC, AprilSylph requested changes

2020-08-20 16:36 UTC, AprilSylph commented on src/scripts/quick_queue.js
> +      event.target.innerHTML = '<path d="M12 10.586l4.95-4.95 1.414 1.414-4.95 4.95 4.95 4.95-1.414 1.414-4.95-4.95-4.95 4.95-1.414-1.414 4.95-4.95-4.95-4.95L7.05 5.636z"/>';
i think all these paths would be better as named constants available to the entire module, both for source-labelling purposes and for potential reduced repetition (it looks like this path in particular is reused at least once?)

2020-08-20 16:36 UTC, AprilSylph commented on src/util/user-blogs.js
> +    return blogs.filter(blog => blog.primary === true)[0];
```suggestion
    return blogs.find(blog => blog.primary === true);
```

2020-08-20 16:39 UTC, AprilSylph commented on src/scripts/quick_queue.js
> +      const response = await apiFetch(`/v2/blog/${defaultBlog}.tumblr.com/posts`, {method: 'POST',
does `/v2/user/info` not give us UUIDs? it'd be nice to use those instead of .tumblr.com identifiers
(also, even if it doesn't, can't we just do `/v2/blog/${defaultBlog}/posts`? i thought non-URL identifiers were always treated as usernames)

2020-08-20 17:34 UTC, AprilSylph requested changes
it would be super nice (and entirely possible, i'm sure) to have the Quick Queue button between the reply and reblog buttons, like the "Fast Queue" button is on the mobile app

2020-08-30 08:15 UTC, invalidCards commented
Closing this in favour of two PRs so that the user blog utilities can be merged without needing to wait on Tumblr documentation.

2020-08-30 08:15 UTC, closed without merging