Minor refactor: Name injected functions
AprilSylph/XKit-Rewritten pull request #442
Opened 2022-02-02 13:06 UTC by marcustyphoon

#### User-facing changes
- None. Like, really, really none.

#### Technical explanation
This is super minor; feel free to close or modify. This names some of the common injected functions by converting them from arrow functions (whose ES6 "names" don't make it through `toString()`, unfortunately). This is exclusively to make them not show up as "anonymous" in devtools and has no other benefit.

#### Issues this closes
n/a

2022-02-02 16:45 UTC, AprilSylph requested changes
Kinda cringe of JavaScript to make us type function names twice!

I'm okay with this idea, but if we're going to do this at all, I would rather have *all* injected functions named.

2022-02-02 16:49 UTC, AprilSylph requested changes
I also think there would be a benefit to a naming scheme for these functions to make them clearly identifiable as XKit-produced. My suggestion is simply `xkit` plus the name of the constant or containing function.

2022-02-02 16:49 UTC, AprilSylph commented on src/scripts/notificationblock.js
> +const unburyTargetPostIds = async function unburyTargetPostIds (notificationSelector) {
```suggestion
const unburyTargetPostIds = async function xkitUnburyTargetPostIds (notificationSelector) {
```

2022-02-02 16:49 UTC, AprilSylph commented on src/util/react_props.js
> +  cache[postID] = inject(async function unburyTimelineObject (id) {
```suggestion
  cache[postID] = inject(async function xkitTimelineObject (id) {
```

2022-02-02 16:49 UTC, AprilSylph commented on src/util/react_props.js
> +const unburyGivenPaths = async function unburyGivenPaths (selector) {
```suggestion
const unburyGivenPaths = async function xkitUnburyGivenPaths (selector) {
```

2022-02-02 16:49 UTC, AprilSylph commented on src/util/tumblr_helpers.js
> +  return inject(async function callApiFetch (resource, init) {
```suggestion
  return inject(async function xkitApiFetch (resource, init) {
```

2022-02-02 21:17 UTC, marcustyphoon commented
Yeah, I definitely don't love the syntax, even when writing the injected function inline. Feels pretty clunky. And I assume the only one looking at this code in devtools is probably me, and I can just manually name them when testing things (and at this point I can identify most of them in the profiler from what they look like :P) I guess it is good to have a name in the stack trace if an injected function throws, though.

...actually, wait, does the catch() not work?

```js
inject(async function testFunctionName () {
  JSON.parse('fkghdkg');
}).then(console.log);
```

<img width="589" alt="Screen Shot 2022-02-02 at 1 10 00 PM" src="https://user-images.githubusercontent.com/8336245/152237913-94f0f6df-8847-4681-a6bf-654feadcddbb.png">

Well, we can discuss that elsewhere.

Anyway, I guess a different option would be adding a third parameter to `inject()` to request a name, and modify the injected script skeleton to like, 
```js
`const ${name} = {${asyncFunc.toString()}};
${name}(...${JSON.stringify(args)}).then(/* */).catch(/* */)`
```
Kind of feels cleaner, actually? Makes it more explicit whether you're supplying a function name or not. (Of course, passing a named non-arrow function and a different name parameter would ignore the parameter in favor of the actual function name in that case, but a) as long as it's not anonymous, whatever and b) not using arrow functions? blasphemy).

2022-02-03 09:15 UTC, AprilSylph commented
It looks like, actually, you should be able to get the constant name in `inject` via the `arguments` object?

```js
const func = () => {};
const args = [];
(function (f, a) {
  console.log(arguments[0].name)
})(func, args);
// => 'func'
```

2022-02-03 09:27 UTC, marcustyphoon commented
Trouble is, we're stringifying the function and (effectively) `eval()`ing it.
```js
const func = () => {};

const stringified = func.toString()
console.log(stringified); 
// "() => {}"

eval(`
console.log((${stringified}).name)
`); 
// ""
```

My idea of manually passing a function name as a parameter to inject() was totally silly, though, I just realized: inject() has the real function, and thus knows the real function name.

```diff
export const inject = (asyncFunc, args = []) => new Promise((resolve, reject) => {
  const callbackId = Math.random();
  callbacks.set(callbackId, [resolve, reject]);

  const script = document.createElement('script');
+ const name = asyncFunc.name || 'xkitInjected';

  script.setAttribute('nonce', nonce);
  script.textContent = `{
-   (${asyncFunc.toString()})(...${JSON.stringify(args)})
+   const ${name} = ${asyncFunc.toString()};
+   ${name}(...${JSON.stringify(args)})
    .then(result => window.xkit$${injectKey}.messagePort.postMessage({
```
Didn't test it yet, but it should work and require almost no changes to scripts.

2022-02-03 09:55 UTC, marcustyphoon commented
Not like it matters, but what would you do with the mega editor function as far as name, extract-or-inline, and extract-to-local-or-module? Technically it's just a generic fetch, right?

2022-02-03 09:59 UTC, AprilSylph requested changes
If we're handling the name passing in `inject()` anyway, we can put an identifying prefix there and not have to change anything else.

2022-02-03 09:59 UTC, AprilSylph commented on src/util/inject.js
> +  const name = asyncFunc.name || 'xkitInjected';
```suggestion
  const name = `xkit$${asyncFunc.name || 'injected'};
```

2022-02-03 10:01 UTC, marcustyphoon commented on src/util/inject.js
> +  const name = asyncFunc.name || 'xkitInjected';
Ooh, good point.

2022-02-03 10:03 UTC, AprilSylph commented on src/util/inject.js
> +  const name = `xkit$${asyncFunc.name || 'injected'};
I LOVE TYPOS I LOVE TYPOS I LOVE TYPOS
```suggestion
  const name = `xkit$${asyncFunc.name || 'injected'}`;
```

2022-02-03 10:05 UTC, AprilSylph commented on src/util/inject.js
> +  const name = `xkit$${asyncFunc.name || 'injected'};
I blame VS Code for automatically creating closing quotes/brackets/parens when you type an opening one. I've gotten lazy.

2022-02-03 10:06 UTC, marcustyphoon commented
...this does, though, beg the question: if you don't name the inner function as a named inline non-arrow function... then what other name do you give the injected getCssMap function, which you are injecting in getCssMap, in order to call Tumblr's function getCssMap?

2022-02-03 10:09 UTC, AprilSylph commented
...`getCssMapFromPage`? `pageContextGetCssMap`? 😅

2022-02-03 10:11 UTC, AprilSylph commented
Maybe the inline injections can stay inline if they're only called once per pageload.

2022-02-03 10:16 UTC, marcustyphoon commented
"Right, good, yes. Now I'll just name the apiFetch injection, uh, wait, hm."

2022-02-03 10:21 UTC, marcustyphoon commented
I mean, honestly... all of the one-liners can't really fail and cause a stack trace that would be confusing anyways. Shall we just make the change to inject(), make a habit of extracting any injected function big enough to make sense to extract, and just leave the simple ones that would naturally be inline as-is?

2022-02-03 10:24 UTC, AprilSylph commented
Yeah, I think that's best.

I was workshopping a comment saying you could do something like
```js
export const apiFetch = async (...args) => inject(
  async function apiFetch (resource, init) { return window.tumblr.apiFetch(resource, init); },
  args
);
```
but it might not be worth doing. Maybe though?

2022-02-03 10:26 UTC, marcustyphoon commented
Yeah, that's what I had in the original PR commit :D

2022-02-03 10:29 UTC, AprilSylph commented
I think we're gonna have to go with a step-by-step review here. Let's see how things look with *just* the `inject()` change; I'm happy with that code, but would you be happy with the results?

2022-02-03 10:34 UTC, AprilSylph commented
> I think I am losing my mind

Me too, just a little bit. I like increasing debuggability though!

2022-02-03 10:40 UTC, marcustyphoon commented
Alright, this is exclusively:

- change to inject() that uses function names where applicable, and `xkit$injected` otherwise
- Make timelineObject use the same structure as exposeTimelines

I think those both make sense. `apiFetch`: shrug! We could leave it as is, name it inline, or name it something else.

2022-02-03 10:43 UTC, AprilSylph approved these changes
I'm happy with this, at least. It definitely makes sense to extract the injected part of `timelineObject` and makes the logic easier to follow.

The next step would be to extract more large injected functions, if they can be given sane names within their modules. Do you want to do that here, or in a subsequent PR?

2022-02-03 10:47 UTC, marcustyphoon commented
I think the only other one in the repository is editPostFormTags! If you have a reasonable name idea for that one... I do not :D

2022-02-03 10:52 UTC, AprilSylph commented
Inputs handled by React are referred to as "controlled inputs", right? How about `controlTagsInput`?

2022-02-03 10:56 UTC, marcustyphoon commented
Ooh, I like it! And indeed they are!

2022-02-03 11:00 UTC, AprilSylph approved these changes
I think I'd like to merge this as-is, then think about naming injected function expressions later. Do you want to rename this PR to make the commit title more accurate? :D

2022-02-03 11:07 UTC, marcustyphoon commented
Hold on, now we have to come up with a clear and concise name for a PR too? Wild 😆

2022-02-03 11:10 UTC, merged

2022-02-03 11:10 UTC, AprilSylph commented
I know right? What a nightmare!

(But it IS part of the contributing guidelines...)