Experiment: Save quick reblog selection in local storage
AprilSylph/XKit-Rewritten pull request #450
Opened 2022-02-04 12:01 UTC by marcustyphoon

Honestly, I'm not sure if this was something you wanted to work on yourself, and if so, I am 100% fine with that! I just wanted to learn about the crypto functions available in javascript and the way XKit Rewritten interfaces with storage... and then wound up learning about attaching event listeners and how to convert an ArrayBuffer to base64.*

*hope you're in Node; if not, reject all of the solutions as awful and do something entirely different.

Pretty sure there are ways to do this in less code. (Honestly, if you want to use any of this, feel free to copy-paste/I could make it a branch in this repo if you want.)

#### User-facing changes
- Quick reblog's "remember the last selected blog in the popup" option persists through page reloads, yet the local storage contains no record of who the user is.

#### Technical explanation
Instead of saving the UUID of the most recently selected blog (and the UUID of your main, so your preferences are remembered on a per-account basis), this saves the SHA256 hash of both UUIDs instead. This identifies them without storing them (unless you can break SHA256, in which case you have better things to do).

I guess if the UUID of your main blog changes, this forgets your preference? Can that happen? Oh well, pretty minor if it does.

This adds an onChange listener to the blog selector so that it can update local storage immediately when you select a blog.

I spent way too long trying to think of an elegant, easily-comprehendable-without-a-comment syntax to search through the values of an object to get the matching key before just saying screw it and also storing the object in reverse ¯\_(ツ)_/¯ 

#### Issues this closes
#429; same ones as #429

2022-02-04 12:05 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> + * @returns {Promise<string>} hash - hexadecimal string of a unique hash of the input
jsdoc nitpicks

```suggestion
 * adapted from https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest#basic_example
 *
 * @param {string} data - String to hash
 * @returns {Promise<string>} Hexadecimal string of a unique hash of the input
```

2022-02-08 09:11 UTC, AprilSylph requested changes
First (and perhaps most obviously), this commented-out code and debug `console.log` calls don't need to be here.

I know this was originally just an experiment, but commented-out code and debug logs have no reason for being once the feature actually works.

2022-02-08 09:11 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +
```suggestion
```

2022-02-08 09:11 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +
```suggestion
```

2022-02-08 09:11 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +      console.log('userblogUUIDs[savedBlogHash]', hashToUuid[savedBlogHash]);
```suggestion
```

2022-02-08 09:23 UTC, AprilSylph requested changes

2022-02-08 09:23 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +let accountKey;
GitHub won't let me suggest this properly because where these should go is untouched, but this collection of `let` statements is for preferences - these should be moved to the collection above, e.g.

```js
let lastPostID;
let timeoutID;
let suggestableTags;
let uuidToHash;
let accountKey;
```

2022-02-08 09:23 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +  console.log('setting', rememberedBlogs);
Missed this one in my first review

```suggestion
```

2022-02-08 09:33 UTC, AprilSylph requested changes

2022-02-08 09:33 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +let uuidToHash;
We actually have no reason to ever reassign this, since user blogs are cached anyway. So let's declare it as a constant further down...

```suggestion
```

2022-02-08 09:33 UTC, AprilSylph commented on src/scripts/quick_reblog.js
...here!
```suggestion
const uuidToHash = {};
```

2022-02-08 09:33 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +    uuidToHash = {};
```suggestion
```

2022-02-08 09:38 UTC, marcustyphoon commented on src/scripts/quick_reblog.js
> +let uuidToHash;
Wait, but then -- oh! Because we're mutating an object!

I am so used to immutable JS from Redux that I forgot that updating data stored in an object doesn't necessarily mean reassigning the variable :D

2022-02-08 09:52 UTC, AprilSylph requested changes

2022-02-08 09:52 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +    const hashToUuid = {};
I see what this is getting at, but this is only used in one place, and it's easy enough to do a sort of reverse-search of `uuidToHash` in one line.

```suggestion
```

2022-02-08 09:52 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +      hashToUuid[hash] = uuid;
```suggestion
      uuidToHash[uuid] = await sha256(uuid);
```

2022-02-08 09:52 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +    }
I personally find this easier to read, too; we're trying to find a matching hash, and there's not a much more direct way of doing that than `.find()` with a strict equality check.

```suggestion
    const savedBlogUuid = Object.keys(uuidToHash).find(uuid => uuidToHash[uuid] === savedBlogHash);
    if (savedBlogUuid) blogSelector.value = savedBlogUuid;
```

2022-02-08 09:58 UTC, marcustyphoon commented on src/scripts/quick_reblog.js
> +    }
Ahh, there we go. My oneliner was really awkward because I was using `entries` instead of `keys`, and... well, you can see what I did in the commented code in the initial commit; it was bad :D

2022-02-08 09:59 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +    }
Hey, you weren't off the mark by much!

2022-02-08 10:03 UTC, AprilSylph requested changes
Looking good! But now that there's only one hash map, I think a cleaner name for `uuidToHash` is in order...

2022-02-08 10:03 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +const uuidToHash = {};
```suggestion
const blogHashes = {};
```

2022-02-08 10:03 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +  const selectedBlogHash = uuidToHash[selectedBlog];
```suggestion
  const selectedBlogHash = blogHashes[selectedBlog];
```

2022-02-08 10:03 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +      uuidToHash[uuid] = await sha256(uuid);
```suggestion
      blogHashes[uuid] = await sha256(uuid);
```

2022-02-08 10:03 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +    accountKey = uuidToHash[mainBlog.uuid];
```suggestion
    accountKey = blogHashes[mainBlog.uuid];
```

2022-02-08 10:03 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +    const savedBlogUuid = Object.keys(uuidToHash).find(uuid => uuidToHash[uuid] === savedBlogHash);
```suggestion
    const savedBlogUuid = Object.keys(blogHashes).find(uuid => blogHashes[uuid] === savedBlogHash);
```

2022-02-08 10:05 UTC, marcustyphoon commented on src/scripts/quick_reblog.js
> +    }
It's interesting to analyze why the pattern here doesn't tend to occur to me! I think on some level it's how much of my process of learning JS was doing performance optimizations, and writing out uuidToHash twice doesn't intuitively feel like a reduction in "things that the code does" even though that's a totally meaningless way to characterize code.

2022-02-08 10:07 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +    }
programmers can have little a repeat yourself, as a treat

2022-02-08 10:17 UTC, marcustyphoon commented on src/scripts/quick_reblog.js
> +    const savedBlogUuid = Object.keys(uuidToHash).find(uuid => uuidToHash[uuid] === savedBlogHash);
My brain immediately goes, "wait, what do the keys of blogHashes represent?" But while this makes sense, I'm pretty meh on it:

```diff
- const savedBlogUuid = Object.keys(blogHashes).find(uuid => blogHashes[uuid] === savedBlogHash);
+ const savedBlogUuid = userBlogs.map(blog => blog.uuid).find(uuid => blogHashes[uuid] === savedBlogHash);
```

Aside: another thing my brain does is go, "hold on, can't you do the `.then(console.log)` trick to shorten the "obj => obj.prop" pattern?" Which, you know... no.

2022-02-08 10:25 UTC, AprilSylph requested changes
And now, some destructuring. Also, nitpicks for existing destructuring.

Applying this batch of suggestions will make the PR identical to my local version.

2022-02-08 10:25 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +const updateRememberedBlog = async event => {
In most cases I find it good practice to use `currentTarget` over `target`, as it ensures you're getting the data from the element you're attaching the event listener to (assuming you're attaching the function directly, as we are here).

```suggestion
const updateRememberedBlog = async ({ currentTarget: { value: selectedBlog } }) => {
```

2022-02-08 10:25 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +  const selectedBlog = event.target.value;
```suggestion
```

2022-02-08 10:25 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +    accountKey = blogHashes[mainBlog.uuid];
```suggestion
    const { uuid: primaryUuid } = userBlogs.find(({ primary }) => primary === true);
    accountKey = blogHashes[primaryUuid];
```

2022-02-08 10:25 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +      await browser.storage.local.get(rememberedBlogStorageKey);
```suggestion
    const {
      [rememberedBlogStorageKey]: rememberedBlogs = {}
    } = await browser.storage.local.get(rememberedBlogStorageKey);
```

2022-02-08 10:25 UTC, AprilSylph commented on src/scripts/quick_reblog.js
> +    await browser.storage.local.get(rememberedBlogStorageKey);
```suggestion
  const {
    [rememberedBlogStorageKey]: rememberedBlogs = {}
  } = await browser.storage.local.get(rememberedBlogStorageKey);
```

2022-02-08 10:40 UTC, marcustyphoon commented on src/scripts/quick_reblog.js
> +
Nope, it shouldn't! At least, I can't think of a crazy race condition for it to matter.

2022-02-08 11:06 UTC, AprilSylph approved these changes
Good work! Thanks for following along with the review process. Hopefully it was enlightening in some small way.

2022-02-08 11:07 UTC, merged

2022-02-08 11:25 UTC, marcustyphoon commented
Indeed; thanks for typing it all up so I could follow through your thought process!