Experiment: Implement inject utility without return callback
AprilSylph/XKit-Rewritten pull request #454
Opened 2022-02-07 08:45 UTC by marcustyphoon

Yep, it's another weird one.

#### User-facing changes
- n/a

#### Technical explanation
This implements a version of `inject()` without the callback functionality, for injecting functions which don't have a meaningful return value. This has two essentially-meaningless benefits:
 - Injected functions can be synchronous, and will be passed through synchronously just as one would expect. (Script tags are evaluated immediately when they're added to the DOM, it turns out.) This improves a minor performance inefficiency with the `exposeTimelines` utility, in which a newly added timeline triggers inject being called up to 4 times in a row, as the normal `inject` function is asynchronous and thus all scripts that immediately call `exposeTimelines` will run their querySelectorAll checks before any of them have injected the function to update the DOM, all finding that their injection is necessary. With a synchronous injection, the first call has its desired effect immediately, and the rest will see that they are unneeded. (This is still a few unnecessary querySelectorAll calls, but oh well. The ways that I thought of to improve that are easy but clunky.)
 - Naturally, the unnecessary postMessage and messageHandler calls are avoided. No meaningful performance benefit, though, thanks to the MessageChannel implementation.

Worthwhile? Eh. Shrug emoji.

#### Issues this closes
n/a

2022-02-09 00:16 UTC, marcustyphoon commented
a) I suppose a better API for this is probably `inject(asyncFunc, args, { void: true })`
b) Different idea that solves the "inject can be called a bunch of times in a row" problem on a general basis:
```js
const caches = new Map();
export const throttledInject = (asyncFunc, args = []) => {
  if (!caches.has(asyncFunc)) caches.set(asyncFunc, {});
  const cache = caches.get(asyncFunc);

  const argsString = JSON.stringify(args);
  if (!cache[argsString]) {
    cache[argsString] = inject(asyncFunc, args);
    cache[argsString].then(() => { delete cache[argsString]; });
  }
  return cache[argsString];
};
```
(I was going to write a PR implementing this on timelineObject, but then I realized it could be generalized to all injections).

Realistically, that would be a separate PR, but just a note that it would conflict with this one unless the change in (a) were made so the option could be passed through. Both behaviors would be needed in order to fully optimize the hide recommended posts tweak, though honestly... eh. None of these are really noticeable even if you scroll a lot. Just feels a bit silly :D

![image](https://user-images.githubusercontent.com/8336245/153097471-c745411f-c7dc-42b0-ba63-7e1dec81c706.png)

2022-02-10 07:49 UTC, marcustyphoon commented
Undrafting this for comment. Implementation/API aside (`injectVoid(/* */)` vs `inject(/* */, { void: true })` or whatever; two similar functions vs one function with conditional logic), do you think it makes sense to implement this at all?

Whether there's a synchronous version of inject affects the cleanest way for me to write other experiment PRs like my current best idea to solve #467.

2022-02-10 11:06 UTC, AprilSylph commented
inject can't be synchronous. If you inject something, you either have to wait for a response from the page context (asynchronously) or not care about if the page context code has finished running or not.

2022-02-10 11:16 UTC, marcustyphoon commented
> Script tags are evaluated immediately when they're added to the DOM, it turns out

This works just fine! For example, you can do:
```js
const script = document.createElement('script');
script.setAttribute('nonce', nonce);
script.textContent = `{
  document.querySelector('article')?.classList.add('firstArticle');
}`;

document.documentElement.appendChild(script);
console.log('the first article is:', document.querySelector('.firstArticle'));
```
and the result is the same as if you had done 
```js
document.querySelector('article')?.classList.add('firstArticle');
console.log('the first article is:', document.querySelector('.firstArticle'));
```

2022-02-10 11:22 UTC, AprilSylph commented
Ah, right, normal scripts are parser-blocking... which means if all the code in one is synchronous, `append`/`appendChild` should only complete after their evaluation.

I've got so much experience with avoiding parser-blocking scripts that I failed to realise they could have an advantage... mein gott...

2022-02-10 11:24 UTC, AprilSylph commented
I think the optional void argument is the better idea. If only the `Function` interface had a property for reading potential return values...

2022-02-10 11:30 UTC, marcustyphoon commented
*skims google results* Oh, neat keyword!

Yeah, I remember when I first encountered inject (or... whatever it was called in XK7). It seemed obvious to me that it would be performance-expensive and asynchronous, and actually I initially thought timelineObject must be a network fetch if it was using a script tag and freaked out at the duplicate calls. But, weirdly, it just kinda turns out to be a convoluted regular function call that has to be runtime compiled, as long as you don't care about trying to message back the result. Always injecting exposeTimelines instead of checking if you need to turns out to actually be a performance gain, kind of, which is wild.

2022-02-17 12:19 UTC, AprilSylph requested changes
apparently i had some nitpicks pending

2022-02-17 12:21 UTC, marcustyphoon commented on src/util/inject.js
> +  returnsVoid ? injectVoid(asyncFunc, args) : injectWithReturn(asyncFunc, args);
👍

2022-02-23 14:37 UTC, marcustyphoon commented
Will close this if we implement synchronous injection in another way, since... well, you know, duh.

2022-02-25 12:50 UTC, marcustyphoon commented
As we discussed in the thread below #416, it seems counterproductive to write any code that relies on injected functions being synchronous, as Chrome's upcoming MV3 migration seems likely to make that impossible. (Presumably void functions will not be distinct from functions which return, in that case.) In that light, I could see the argument that this is not worthwhile.

On the other hand, because I was careful to return a Promise no matter what in the later versions of this PR, and because the optional void argument could easily be ignored in MV3, it seems to me like this API would allow Firefox/MV2 to resolve injected void functions before a repaint while MV3 would have them resolve afterwards, and this would be entirely transparent to the calling script, no matter if it uses `await` or `.then()`. So in the spirit of "give Firefox users nice things," this could still be interesting.

2022-02-25 13:15 UTC, AprilSylph commented
I'm still very interested in the `document.currentScript` approach without the benefits of true synchronicity. In fact, in the meantime, we could very easily do the synchronous approach so long as we still return a `Promise`, so no APIs that rely on `inject()` have to be adapted to expect promises in the MV3 switchover.

An async function with no `await` statements should return an already-resolved promise, shouldn't it? So we can get the performance gain that way until we have to put the `load` event in as part of obeying MV3's CSP.

2022-02-25 13:17 UTC, marcustyphoon commented
Yep, exactly!

2022-02-25 13:26 UTC, AprilSylph commented
I think what I want to do is rewrite `inject()` with the `document.currentScript` approach for all injection types (returns value, returns void, returns promise), which should cover the intention of this PR as well. If an injected function is not async, `inject()` could resolve immediately regardless of the return value.

2022-02-25 13:29 UTC, marcustyphoon commented
Sounds good to me! I keep forgetting that MV3 doesn't mean you *have* to inject from the background script, since I spent so long reading its documentation which seems - at least in my opinion - quite clear that you must.

2022-02-25 15:21 UTC, closed without merging