Show Originals: New in-dash toggle UI
AprilSylph/XKit-Rewritten pull request #463
Opened 2022-02-09 12:55 UTC by marcustyphoon

todo: make code good, write description, etc

```
### User-facing changes
- 

#### Technical explanation

#### Issues this closes
```

2022-02-09 13:28 UTC, AprilSylph commented on src/scripts/show_originals.js
> +  if (allPostsLabel === 'All posts') allPostsLabel = 'All Posts';
you could skip this line and use `text-transform: capitalize;` in the style(/sheet)

2022-02-09 13:58 UTC, marcustyphoon commented on src/scripts/show_originals.js
> +  if (allPostsLabel === 'All posts') allPostsLabel = 'All Posts';
Ah, perfect.

2022-02-09 14:11 UTC, marcustyphoon commented
(maybe blogs on which the script has no effect should have a disabled controls selector rather than none, probably less confusing)

2022-02-28 11:54 UTC, AprilSylph commented on src/scripts/show_originals.js
> +  const nonGroupUserBlogs = (await getUserBlogs().catch(() => []))
When could `getUserBlogs()` reject? When you're logged out?

I'd rather build in error handling to the user blogs module itself if that's the case.

2022-02-28 11:55 UTC, marcustyphoon commented
I've looked over this a couple of times trying to reduce the number of lines of code. It's certainly a lot. The biggest thing that really isn't super necessary is the unique behavior that handles viewing a blog in Peepr whose posts would all be shown regardless of if the extension was active or not.

2022-02-28 11:58 UTC, marcustyphoon commented on src/scripts/show_originals.js
> +  const nonGroupUserBlogs = (await getUserBlogs().catch(() => []))
When you're logged out, yeah. This is rather silly, but I just sort of left it as is because all of the other scripts that use it shouldn't do anything when you're logged out anyways, so user_blogs crashing them on init kind of worked out, at the moment. But yes, it should certainly be handled... not like that, ideally.

2022-03-03 14:56 UTC, AprilSylph requested changes

2022-03-03 14:56 UTC, AprilSylph commented on src/scripts/show_originals.js
> +import { getPrimaryBlogName, getUserBlogs } from '../util/user_blogs.js';
```suggestion
import { translate } from '../util/language_data.js';
import { getPrimaryBlogName, getUserBlogs } from '../util/user_blogs.js';
import { postSelector } from '../util/interface.js';
```

2022-03-03 14:56 UTC, AprilSylph commented on src/scripts/show_originals.js
> +    timelineElement.querySelector('[data-id]')?.before(controls);
```suggestion
    timelineElement.querySelector(postSelector)?.before(controls);
```

2022-03-03 14:56 UTC, AprilSylph commented on src/scripts/show_originals.js
> +    timelineElement.querySelector('[data-id]')?.parentElement?.prepend(controls);
```suggestion
    timelineElement.querySelector(postSelector)?.parentElement?.prepend(controls);
```

2022-03-03 15:23 UTC, AprilSylph reviewed
The feature description is definitely going to need to be updated. The "on the dashboard" part is safe to just toss out, but I'm not sure what the most succinct way to communicate the toggle behaviour is.

Maybe just "Hide reblogged posts by default"? I was thinking along the lines of "Make reblogs opt-in"/"View reblogs on an opt-in basis", but that only communicates the main selling point of Show Originals through inference.

2022-03-03 21:30 UTC, marcustyphoon commented on src/scripts/show_originals.js
> +import { getPrimaryBlogName, getUserBlogs } from '../util/user_blogs.js';
👍

2022-03-03 21:48 UTC, marcustyphoon commented
Hmm... yeah, that is tough. My brain goes to "filter" instead of "hide" for the verb, but I can't think of a logical justification for why that communicates optionality to me. Will have to think about it more.

2022-03-04 10:28 UTC, AprilSylph reviewed
Testing this out on a fresh dev install, one thing that strikes me as very odd is how it's very possible to have a big enabled "Original Posts" button with a reblogged post right underneath it, due to `showOwnReblogs` and `showReblogsWithContributedContent` being enabled by default. With this change, I think it would be best to change them both to disabled by default.

Their descriptions could also use updating; I think "Always show" would make more sense than just "Show" given the new behaviour.

2022-03-04 11:18 UTC, AprilSylph requested changes
Some style suggestions you'll hopefully agree with. Here's a screenshot of how it looks with all these changes applied:

Dashboard | Blog View
---|---
![image](https://user-images.githubusercontent.com/28949509/156753730-a24cbe2d-e301-4f95-8bf6-192c62b38ad1.png) | ![image](https://user-images.githubusercontent.com/28949509/156753860-effc00a7-3512-4cda-a90c-aadee070535d.png)

2022-03-04 11:18 UTC, AprilSylph commented on src/scripts/show_originals.css
> +}
Removes the hover background. I know this is copied from the `/tagged/` page's Recent/Top buttons, but the way there's no bottom border on the controls container means the visual effect is not quite the same. For me, I have to do a double-take on whether the enabled `box-shadow` is actually inset, since there's nothing for it or the hover background to both be flush against.

```suggestion
```

2022-03-04 11:18 UTC, AprilSylph commented on src/scripts/show_originals.css
> +  box-shadow: inset 0 -2px 0 var(--blog-link-color, rgb(var(--accent)));
Makes the enabled shadow thicker. No solid justification for this one either, it just looks better to me.

```suggestion
  box-shadow: inset 0 -3px 0 var(--blog-link-color, rgb(var(--accent)));
```

2022-03-04 20:30 UTC, marcustyphoon commented
Style changes sound good, and I trust your eye - going to accept changes and try them then comment if I think any deserve more discussion.

2022-03-04 20:42 UTC, marcustyphoon commented
> Testing this out on a fresh dev install, one thing that strikes me as very odd is how it's very possible to have a big enabled "Original Posts" button with a reblogged post right underneath it, due to `showOwnReblogs` and `showReblogsWithContributedContent` being enabled by default. With this change, I think it would be best to change them both to disabled by default.

Hm, user confusion vs users not realizing options exist that I think most should be aware of. I think that's fair, especially the case of the latter. The former feels like it has the potential to cause some confusion in its own right, even though the functionality of "hide reblogged posts" pretty clearly doesn't have an inherent exception for your own posts, so I'm ambivalent about that one. Again, I trust your judgement.

> Their descriptions could also use updating; I think "Always show" would make more sense than just "Show" given the new behaviour.

+1, certainly on the first two. Opinions on "Blogs to show reblogs from" vs "Blogs to always show reblogs from" vs "Always show reblogs from these blogs?"

2022-03-04 21:22 UTC, AprilSylph commented
"Always show reblogs from these blogs" sounds better to me!

2022-03-07 11:35 UTC, AprilSylph approved these changes
Great work!

I'd like to add this update to my next Week in Review given its significance. Would you like to be credited in it via your GitHub username or a Tumblr mention?

2022-03-07 11:35 UTC, merged

2022-03-07 20:40 UTC, marcustyphoon commented
Oh, thanks! Hmm... GitHub username works I suppose :)