Visible Alt Text Tweak: Improve wrapping on tiny images
AprilSylph/XKit-Rewritten pull request #478
Opened 2022-02-12 23:50 UTC by marcustyphoon

#### User-facing changes

Improves alt text captions wrapping on very small images.

Before:

<img width="595" src="https://user-images.githubusercontent.com/8336245/153731992-cebbaadb-73d1-4998-b183-adf833bbd699.png">

After:
<img width="595" src="https://user-images.githubusercontent.com/8336245/153731950-81e2cb25-3ee0-4e55-9e9c-0b03170a843a.png">

<img width="599" src="https://user-images.githubusercontent.com/8336245/153732000-a97a34db-3aec-48e2-8ccf-2de247872c03.png">

#### Technical explanation

`min-content` sets the minimum width to the width of the longest word. This is not perfect:

<img width="599" src="https://user-images.githubusercontent.com/8336245/153732024-e7a9afb7-ec97-4c1b-bbe9-ec5884d975c0.png">

If you know of a way to improve this, that would be awesome. Perhaps just setting the minimum width to a reasonable quantity is better? But that doesn't adapt nicely to single word captions, so I dunno.

#### Issues this closes
n/a

2022-02-13 09:26 UTC, AprilSylph commented
![image](https://user-images.githubusercontent.com/28949509/153746947-6ef35d3f-ca7a-4ee6-bb35-5f94e5d4b977.png)

I don't think a perfect solution will be quite so simple

2022-02-13 09:43 UTC, marcustyphoon commented
Indeed. Simply setting a fixed minimum width the size of a reasonably short word is definitely less aesthetically pleasing on the single word example, but probably looks better with a few very short words and isn't prone to looking broken with, you know, endless screaming or whatever. (Not that one should put that in a caption designed for screen reader accessibility, I would imagine, but I digress :P)

[I may add screenshots to this comment later, but I may not.]

2022-02-13 11:57 UTC, AprilSylph commented
maybe a sensible minimum width would be the width of a 1/3 photoset photo? not quite 540/3 because of the padding, but close.

2022-02-13 12:31 UTC, marcustyphoon commented
126px min width, plus 2x20 margins = 166px container, which if multiplied by three yields 498, which is the width of the content in a textblock? Oh - you edited while I was typing this haha. So, not quite this. I think I was imagining a smaller value, but I think this works too.

<img width="593" src="https://user-images.githubusercontent.com/8336245/153752604-6979c414-646f-4a84-bfd2-663ffa7fdb08.png">

(Also, it just dawned on me that the horizontal padding could be `min(var(--post-padding), /* some percentage */)` (or even  `max(var(--post-header-vertical-padding), calc(100% * 20/540))`) such that it wouldn't be as high when the caption block is small. The full 20px looks good in full width but pretty weird on the tiny stuff, IMO.)

2022-02-15 06:39 UTC, AprilSylph requested changes

2022-02-15 06:39 UTC, AprilSylph commented on src/scripts/accesskit.css
> +  min-width: min-content;
Apparently the true number of pixels for the width of a single image in a three-image row is `177.33334350585938px`. Also, setting that without accounting for the padding breaks three-image photoset rows!

Beyond that, I realised that using a pixel value (or a `calc()` assuming the post width to be `540px` ) would break on viewport widths under 540px wide. I thought we might need to use a media query, but for once, CSS `min()` looks like it actually does its job!

```suggestion
  box-sizing: border-box;
  height: 100%;
  min-width: calc((min(540px, 100vw) / 3) - (4px * 2));
```

2022-02-15 07:06 UTC, marcustyphoon commented on src/scripts/accesskit.css
> +  min-width: min-content;
I... cannot believe I didn't know about `box-sizing: border-box;` :D

2022-02-15 07:32 UTC, marcustyphoon commented on src/scripts/accesskit.css
> +  min-width: min-content;
Ah, I see what you're doing here: setting a minimum size equal to the smallest an image could be in a photoset.

2022-02-15 09:31 UTC, AprilSylph approved these changes

2022-02-15 09:31 UTC, merged

2022-04-16 21:18 UTC, marcustyphoon commented
While I can't remember my exact thinking at the time, I just stumbled upon [the MDN article for overflow-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) while investigating something unrelated and thought, "hey, wouldn't this have solved a problem I encountered previously?" Not sure if that is actually true, but I am putting a note here just in case.

2022-04-16 21:32 UTC, AprilSylph commented
The ruleset you modified in this PR already has `overflow-wrap: break-word`; specifying `anywhere` instead would reduce the intrinsic width down to what is necessary to fit one letter per line.

2022-04-16 21:59 UTC, marcustyphoon commented
Oh, I just looked at the CSS for the demo on that page and it's not doing what I thought it was - it's just a static max width ;( Never mind!