Element based inject test
AprilSylph/XKit-Rewritten pull request #504
Opened 2022-03-01 08:41 UTC by marcustyphoon

As we discussed in #416, it should be possible to skip using querySelector in some (all, I think, but at the expense of too much complexity in some cases) by injecting script elements into relevant DOM containers. I got worried it wouldn't work, so I tried it, and it seems to! Committing in case it saves time/sparks useful discussion.

Feel free to ignore, peruse, cherry pick, etc, or I could convert this into a real PR with a real issue template description and a rebase off of master if you'd like. Sometimes it's fun to see the different ways we think to implement concepts when we try them independently, though - I'm curious if you were imagining something somewhat different than I was!

2022-03-01 09:25 UTC, AprilSylph commented on src/util/inject.js
> + * @param {Element} target
```suggestion
 * @param {Element} [target] - Element to append script to
```

2022-03-01 09:48 UTC, marcustyphoon commented on src/util/inject.js
> + * @param {Element} target
```diff
  /**
   * @param {Function} func - Function to run in the page context (can be async)
   * @param {Array} args - Array of arguments to pass to the function via spread
+  * @param {Element} [target] - Element to append script to; will be accessible as
+  *                             document.currentScript.parentElement in the injected function.
   * @returns {Promise<any>} The return value of the function, or the caught exception
   */
```

Perhaps?

(Or I guess we could get really cute and prepend `const target = document.currentScript.parentElement` into the injection body and set it as a global in eslint, or append it to the arguments... yeah, okay, no, I can't think of a clean way to do it, darn :D)

2022-03-01 10:22 UTC, AprilSylph commented on src/util/inject.js
> + * @param {Element} target
Looks fine to me!

2022-03-01 10:47 UTC, AprilSylph commented
Now, I'll admit that I should have reviewed #463 already, but it is a fairly complex change, whereas this isn't really on its own. If you could drop 166cea1, implement the bare changes to Show Originals needed for it to continue to work with the new `timelineObject`, then force-push this branch, I would be happy to review this PR properly.

2022-03-01 10:56 UTC, marcustyphoon commented
Oh yeah, no worries! I just included the merged commit here since that was how I was testing it and I didn't feel the need to fix it unless you wanted to use this :) Will do!

2022-03-01 14:32 UTC, AprilSylph commented on src/util/inject.js
>   * @param {Array} args - Array of arguments to pass to the function via spread
This isn't exactly to do with the changes in this PR, but reviewing it made me realise that `args` is optional too:

```suggestion
 * @param {Array} [args] - Array of arguments to pass to the function via spread
```

I'm not suggesting to pass `undefined` instead of `[]` anywhere, but it would (accurately) denote that an `inject()` call only needs `func` in order to work... though I can't think of any use-cases for that myself.

2022-03-01 14:36 UTC, marcustyphoon commented on src/util/inject.js
>   * @param {Array} args - Array of arguments to pass to the function via spread
Indeed, we do use that: for getting the css map and language data!

2022-03-01 14:48 UTC, AprilSylph commented on src/util/inject.js
>   * @param {Array} args - Array of arguments to pass to the function via spread
Oops, yeah.

I am not awake enough.

2022-03-02 16:47 UTC, AprilSylph requested changes
Just `cache` is too generic IMO

2022-03-02 16:47 UTC, AprilSylph commented on src/util/react_props.js
> +const cache = new WeakMap();
```suggestion
const timelineObjectCache = new WeakMap();
```

2022-03-02 16:47 UTC, AprilSylph commented on src/util/react_props.js
> +    cache.set(postElement, inject(unburyTimelineObject, [], postElement));
```suggestion
  if (!timelineObjectCache.has(postElement)) {
    timelineObjectCache.set(postElement, inject(unburyTimelineObject, [], postElement));
```

2022-03-02 20:04 UTC, AprilSylph commented
oh WHAT is up with my awful incomplete suggestions lately

2022-03-02 20:06 UTC, marcustyphoon commented
No worries ❤️

2022-03-03 13:28 UTC, AprilSylph approved these changes

2022-03-03 13:28 UTC, merged