Add XKit header to all API requests
AprilSylph/XKit-Rewritten pull request #529
Opened 2022-03-16 15:29 UTC by cyle

#### User-facing changes

- None!

#### Technical explanation

Like the previous version of XKit, it'd be helpful for us on the Tumblr side to know when requests are coming from XKit. I think this should do the trick?

#### Issues this closes

- None!

@AprilSylph hello

2022-03-16 15:46 UTC, AprilSylph commented
> Also what's the best way to test this locally? 🤔

https://github.com/AprilSylph/XKit-Rewritten/blob/master/docs/Chapter%202%20-%20Getting%20started.md!

P.S. hi

2022-03-16 15:57 UTC, AprilSylph requested changes

2022-03-16 15:57 UTC, AprilSylph commented on src/util/tumblr_helpers.js
> +      window.tumblr.apiFetch(resource, init);
This needs to be explicitly returned now that it's no longer the sole statement; arrow functions only return implicitly in their braceless form.

```suggestion
      return window.tumblr.apiFetch(resource, init);
```

2022-03-16 16:37 UTC, AprilSylph commented on src/util/tumblr_helpers.js
> +      }
i'd say it's acceptable given the lacking jsdoc. (hopefully the eslint plugin doesn't complain about me documenting specific arguments within rest parameters...)

that said, it would definitely be possible to make use of some newer and cuter language features here, since XKit Rewritten has very strict browser requirements:
1. it's safe to assume `init` is either going to be an object or omitted entirely, so ensuring it exists is as simple as setting it as a [default parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)
2. it's also fairly safe to assume `init.headers` is either going to be an object or omitted (I'm sure setting it to another type would likely have some adverse effects), so ensuring it exists is also straightforward using [logical nullish assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment)

```suggestion
    async (resource, init = {}) => {
      init.headers ??= {}; 
```

2022-03-16 16:54 UTC, marcustyphoon commented on src/util/tumblr_helpers.js
> +      }
> [logical nullish assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment)

Ooh, I was avoiding using that one because I wasn't sure if people would be familiar with it! Will make use in future :)

2022-03-16 19:35 UTC, cyle commented on src/util/tumblr_helpers.js
> +      }
awesome, thank you for explaining that so thoroughly 👌

2022-03-16 20:08 UTC, cyle commented
awesome, i can confirm the header is being sent via Quote Replies, for example 👌

2022-03-16 20:16 UTC, marcustyphoon commented
I don't think it makes any difference (I guess if there's an exception in the code added here it would produce a more informative stack trace, but whatever), but just a note that this manipulation could also be done in the function body instead of in the inject body.

Anyway, certainly not the same scenario, but would it also be useful to add a similar header to the mega-edit utility?

2022-03-16 20:52 UTC, AprilSylph commented
Moving the manipulation to the outer function body would include switching away from using rest parameters, so I'd say that's out of scope for this PR.

It's pretty late for me, but I'll test this locally and merge tomorrow morning, @cyle. And thanks for putting the work in!

2022-03-17 09:46 UTC, AprilSylph approved these changes
LGTM! I will note though that the way XKit Rewritten bundles all its code, this will have to be included in a new release (v0.17.1) and won't reach previous versions - so any stats you gather won't be accurate for Firefox users, who can prevent addons from auto-updating and can choose to install any previous version of the addon.

2022-03-17 09:46 UTC, merged