Visible Alt Text: Disable in Gutenberg editor
AprilSylph/XKit-Rewritten pull request #558
Opened 2022-04-20 20:38 UTC by marcustyphoon

This is one way of solving #557. Perhaps not the best way; it would be convenient to be able to preview the alt text that you have written for an image while composing it. Getting the styling correct seems nontrivial without a better understanding of the Gutenberg code than I currently have, however.

#### User-facing changes
- There is no visible alt text in the post compose form, but at least it isn't buggy and doesn't change formatting suddenly without user interaction.

#### Technical explanation
n/a

#### Issues this closes
#557

2022-04-21 20:09 UTC, AprilSylph requested changes
I think we can agree that this feature was only designed to work within posts, where we can guarantee there is room for a caption.

We could reflect this in the code and solve the issue more simply by changing the selector used to register `processImages()` to `pageModifications` to something more specific:

```diff
-  pageModifications.register('img[alt]', processImages);
+  pageModifications.register(`${postSelector} ${imageBlockSelector} img[alt]`, processImages);
```

---

As a bonus, this would allow us to skip the check for `imageBlock` in the function itself, too, since we'll only be processing descendants of `imageBlock`s in the first place:
```diff
-    const imageBlock = imageElement.closest(imageBlockSelector);
-    if (imageBlock !== null) imageBlocks.set(imageBlock, alt);
+    imageBlocks.set(imageElement.closest(imageBlockSelector), alt);
```

2022-04-21 20:29 UTC, marcustyphoon commented
Right! Thought about that - it would require a custom `postSelector` in order to still work on the radar post, right?

Actually, it looks like simply adding `${imageBlockSelector}` would work, assuming that that css map key is never used inside Gutenberg. Do you think that's better, or do you think explicitly specifying e.g. `is(${postSelector}, ${radarSelector})` is more clear about exactly where the feature is supposed to function?

(I assume there are no other locations where this is relevant besides timeline posts and radar? Trying to remember.)

2022-04-21 20:34 UTC, AprilSylph commented
Ah, right, the Radar. Well, I was originally going to recommend more simply using `article ${imageBlockSelector} img[alt]`, which I guess would cover it.

As for omitting a post selector entirely, we're... already checking for `imageElement.closest(imageBlockSelector)` before sending the image blocks to be processed. Checking for it twice won't change anything.

2022-04-21 20:43 UTC, marcustyphoon commented
Right, it would only matter if there are or might ever be `imageBlock`s that are not within `article`s somewhere.

2022-04-24 16:27 UTC, AprilSylph approved these changes

2022-04-24 16:27 UTC, merged