New script experiment: Themed posts
AprilSylph/XKit-Rewritten pull request #568
Opened 2022-04-22 21:11 UTC by marcustyphoon

This is definitely <https://www.tumblr.com/settings/labs>, I don't know what you're talking about.
||||
| - | - | - |
| ![image](https://user-images.githubusercontent.com/8336245/164793508-9353638e-ba77-482a-83a8-40f081cbfdd4.png) | ![image](https://user-images.githubusercontent.com/8336245/164793518-aef9f1c0-e5cd-4b9c-b5a6-89770256a1fc.png) | ![image](https://user-images.githubusercontent.com/8336245/164793520-711c02fb-b53f-4f0d-9161-7097f627f2b2.png) |
 | ![image](https://user-images.githubusercontent.com/8336245/164793522-7d34c316-8058-496c-b162-2eee1c348560.png) | ![image](https://user-images.githubusercontent.com/8336245/164793523-42b25444-c119-4261-b68b-1f1d574b3ea7.png) | ![image](https://user-images.githubusercontent.com/8336245/164793525-7204ff03-d565-40fa-8f1b-86b873d541c2.png) | 
|![image](https://user-images.githubusercontent.com/8336245/164793526-a28fc0ef-09e6-4402-9f80-518b0d46882e.png) | ![image](https://user-images.githubusercontent.com/8336245/164793530-6b0168ca-f945-419c-afe2-0c22efab5e83.png) | ![image](https://user-images.githubusercontent.com/8336245/164793533-8f917f79-13e1-407d-8d36-e73a73d2c9c3.png) |

2022-05-14 14:13 UTC, AprilSylph requested changes
i'm going to be a bit more casual reviewing your PRs from now on if that's okay, makes it more fun

REVIVAL

2022-05-14 14:13 UTC, AprilSylph commented on src/scripts/themed_posts.js
> +  onNewPosts.removeListener(processPosts);
order order order order

ideal order of cleanup:
1. remove listeners (makes sure none of the rest of the script runs while the rest of cleanup happens
2. remove visual changes (remove elements, remove styles)
3. remove dom changes
4. reset data

technically i'm breaking this a little bit with my suggestion but if you're manipulating the same thing multiple times i think it's fine to group that together too. clarity!

```suggestion
  onNewPosts.removeListener(processPosts);

  styleElement.remove();
  styleElement.textContent = '';

  $('[data-xkit-themed]').removeAttr('data-xkit-themed');

  blogs.clear();
```

2022-05-14 14:13 UTC, AprilSylph commented on src/scripts/themed_posts.js
> +    const titleColorHex = hexToRGB(titleColor);
\>output of `hexToRGB`
\>name implies they're still hex
:thinking:

```suggestion
    let backgroundColorRGB = hexToRGB(backgroundColor);
    const titleColorRGB = hexToRGB(titleColor);
```

2022-05-14 14:13 UTC, AprilSylph commented on src/scripts/themed_posts.js
> +      backgroundColorHex = '255, 255, 255';
```suggestion
      backgroundColorRGB = '255, 255, 255';
```

2022-05-14 14:13 UTC, AprilSylph commented on src/scripts/themed_posts.js
> +          --black: ${titleColorHex};
```suggestion
          --white: ${backgroundColorRGB};
          --black: ${titleColorRGB};
```

2022-05-14 18:49 UTC, marcustyphoon commented on src/scripts/themed_posts.js
> +    const titleColorHex = hexToRGB(titleColor);
...huh, I have no idea what I was thinking there :D

2022-05-23 22:50 UTC, AprilSylph commented on src/scripts/themed_posts.js
> +};
i see the spirit of what this is trying to do, but i think a regex approach could be a lot more fun...

patch notes:
- made the function shorter in terms of sloc
- probably made the function longer in terms of total characters
- now supports `#RGB` syntax properly
- now supports alpha values even less! (`#RGBA` will be interpreted as `#RRGB`, `#RRGGBBAA` will throw an error)

```suggestion
const hexToRGB = (hex) => {
  const { red, green, blue } = hex.match(/^#(?<red>[A-Fa-f0-9]{1,2})(?<green>[A-Fa-f0-9]{1,2})(?<blue>[A-Fa-f0-9]{1,2})$/).groups;
  return [red, green, blue]
    .map(color => color.padEnd(2, color))
    .map(color => parseInt(color, 16))
    .join(', ');
};
```

we could support alpha values properly by having four perfect regexes (one per valid hex syntax) but i think it's safe enough to operate on the assumption that blog theme colours will never support alpha

2022-05-23 23:01 UTC, marcustyphoon commented on src/scripts/themed_posts.js
> +};
Wait, how does this - oh, greedy quantifiers give back. Wild.

(Also, whoops, I didn't realize I wasn't correctly handling `#RGB` colors. That is a weird but convenient shorthand!)

Adding a `{0,2}` alpha term would work for `#RRGGBBAA` but still parse `#RGBA` as `#RRGB`, right? Darn.

2022-05-23 23:06 UTC, marcustyphoon commented on src/scripts/themed_posts.js
> +};
I guess one could do `hex.replace(`#`, ``).slice(0, 6).match(` to at least not crash on... ah, still doesn't work for #RGBA, never mind.

2022-05-24 21:49 UTC, AprilSylph requested changes
code otherwise LGTM!

2022-05-24 21:49 UTC, AprilSylph commented on src/scripts/themed_posts.js
> +    }
it looks like this is calculating RGB values and then discarding them if the blog is already registered

```suggestion
    const { blog: { name, theme } } = await timelineObject(postElement);

    if (blacklist.includes(name)) return;

    if (!blogs.has(name)) {
      blogs.add(name);

      const { backgroundColor, titleColor } = theme;

      const backgroundColorRGB = hexToRGB(backgroundColor);
      const titleColorRGB = hexToRGB(titleColor);

      styleElement.textContent += `
        [data-xkit-themed="${name}"] {
          --white: ${backgroundColorRGB};
          --black: ${titleColorRGB};
        }
      `;
    }

    postElement.dataset.xkitThemed = name;
```

2022-05-24 21:49 UTC, AprilSylph commented on src/scripts/themed_posts.js
> +
i already removed the logic in my first suggestion, but while i was working on that, i realised how it just doesn't fit the spirit of the feature to have this override, IMO. if someone has an off-white background i want to see an off-white background.

2022-05-25 04:27 UTC, marcustyphoon commented
Not sure what one would call the variable, but I think I would prefer if the regex were extracted as a variable for line length reasons. (I'm sure some people use wrapping, but I don't.)

2022-05-25 04:37 UTC, marcustyphoon commented on src/scripts/themed_posts.js
> +
Yeah, I thought about it. Realistically, if this were first-party, I would want a valid (default) theme color of undefined and a way to revert to that, which would result in this script falling back to the current theme's coloration as if the script were not enabled. Seems too cute to just skip theming posts from blogs with `#FAFAFA` set, though, I think; it would feel more natural at first IMO, but the idea that you must reset your theme color to a magic value if you want to make your posts not colored anymore is definitely not intuitive.

2022-05-28 10:30 UTC, AprilSylph commented on src/scripts/themed_posts.js
> +  const { red, green, blue } = hex.match(/^#(?<red>[A-Fa-f0-9]{1,2})(?<green>[A-Fa-f0-9]{1,2})(?<blue>[A-Fa-f0-9]{1,2})$/).groups;
> Not sure what one would call the variable, but I think I would prefer if the regex were extracted as a variable for line length reasons.

```suggestion
const groupsFromHex = /^#(?<red>[A-Fa-f0-9]{1,2})(?<green>[A-Fa-f0-9]{1,2})(?<blue>[A-Fa-f0-9]{1,2})$/;

const hexToRGB = (hex) => {
  const { red, green, blue } = hex.match(groupsFromHex).groups;
```

2022-06-02 21:39 UTC, AprilSylph approved these changes
Beautiful!

2022-06-02 21:40 UTC, merged