Implementing feature requested in issue  #588
AprilSylph/XKit-Rewritten pull request #589
Opened 2022-05-10 04:07 UTC by salazarbarrera

#### User-facing changes
- Added option to Mutual Checker script to only show posts by mutuals on dashboard.

#### Technical explanation
- Hides via CSS all the posts made by non-mutual blogs.

#### Issues this closes
Issue #588

2022-05-10 04:11 UTC, salazarbarrera reviewed
Changes made to pass test.

2022-05-10 04:13 UTC, salazarbarrera reviewed
More style changes.

2022-05-14 13:56 UTC, AprilSylph requested changes
Very nice for a first contribution! It's always wonderful to see someone new joining in with the project. I hope that between the documentation and the framework itself, it wasn't too hard to get your bearings in the codebase.

Other than these few little details, this looks good to go!

2022-05-14 13:56 UTC, AprilSylph commented on src/scripts/mutual_checker.css
> +.xkit-mutual-checker-hidden article {
If the option is only supposed to hide non-mutual posts on the dashboard, we need to make this selector more specific. Tumblr has `data-timeline` attributes on each timeline, which makes this very easy!

```suggestion
[data-timeline="/v2/timeline/dashboard"] .xkit-mutual-checker-hidden article {
```

2022-05-14 13:56 UTC, AprilSylph commented on src/scripts/mutual_checker.js
> +      postElement.classList.remove(hiddenClass);
It looks like this condition only exists for cleanup when the preference is toggled... is that right? If so, it's sadly insufficient; while it does work for disabling the preference, it won't get called when the feature itself is disabled. Features should always clean themselves up in the `clean()` function.

```suggestion
```
---
Unfortunately I can't code-suggest this properly, and you won't be able to copy-paste this entire block, but this is what I'd do further down this file:
```diff
 export const clean = async function () {
   onNewPosts.removeListener(addIcons);

   $(`.${mutualsClass}`).removeClass(mutualsClass);
+  $(`.${hiddenClass}`).removeClass(hiddenClass);
   $(`.${mutualIconClass}`).remove();
 };
```

2022-05-14 13:56 UTC, AprilSylph commented on src/scripts/mutual_checker.json
> +      "label": "Only show mutuals on dashboard",
This is a nitpick, so feel free to resolve without committing this if you disagree, but I feel like the description here could stand to be a little more verbose...

```suggestion
      "label": "Only show posts from mutuals on dashboard",
```

2022-05-14 18:02 UTC, salazarbarrera commented on src/scripts/mutual_checker.js
> +      postElement.classList.remove(hiddenClass);
Thanks! Effectively, that else was to undo the changes when someone wanted to stop using that feature. I'll add that cleanup and test it later.

2022-05-15 02:53 UTC, salazarbarrera commented on src/scripts/mutual_checker.js
> +      postElement.classList.remove(hiddenClass);
Worked wonderfully.

2022-05-15 06:33 UTC, marcustyphoon commented on src/scripts/mutual_checker.json
> +      "label": "Only show posts from mutuals on dashboard",
```suggestion
      "label": "Only show posts from mutuals on the dashboard",
```

Minor phrasing suggestion!

2022-05-15 08:09 UTC, AprilSylph commented on src/scripts/mutual_checker.json
> +      "label": "Only show posts from mutuals on dashboard",
gonna commit this one myself, i should have looked more carefully at my original suggestion

2022-05-16 21:29 UTC, merged

2022-05-17 01:23 UTC, salazarbarrera commented on src/scripts/mutual_checker.json
> +      "label": "Only show posts from mutuals on dashboard",
Thanks! I too should have checked it better. Since English is my second language, on first inspection it sounded fine.