Create isMyPost utility
AprilSylph/XKit-Rewritten pull request #601
Opened 2022-05-17 23:09 UTC by marcustyphoon

#### User-facing changes
- n/a

#### Technical explanation
Extracts the reused "is this my own post" logic into a utility function.

Uses top-level await.

#### Issues this closes
n/a

2022-05-19 17:42 UTC, AprilSylph commented on src/util/react_props.js
> +const primaryBlogName = await getPrimaryBlogName().catch(() => undefined);
we wouldn't need to `await` this if `user.js` exported synchronous functions, which would be completely possible if it top-level awaited the `apiFetch` call

(not a blocker, i don't expect you to go overhaul the whole utility; you are of course free to, though)

2022-05-19 19:37 UTC, marcustyphoon commented on src/util/react_props.js
> +const primaryBlogName = await getPrimaryBlogName().catch(() => undefined);
Oh yeah!

I can do most of the top level `await` chores if you'd like.

2022-05-19 20:11 UTC, AprilSylph commented on src/util/react_props.js
> +const primaryBlogName = await getPrimaryBlogName().catch(() => undefined);
fine by me, just make sure to split it up per util file. this is where i'd probably get tempted to open one giant PR

2022-05-24 21:31 UTC, AprilSylph commented
Do you still want this reviewed as-is or should we convert the user util functions to be synchronous first?

2022-05-25 04:38 UTC, marcustyphoon commented
No preference here. Would you like that conversion after merging this, in this PR, or as another PR to review first?

2022-05-25 07:43 UTC, AprilSylph commented
I think I'd prefer a separate PR first!

2022-06-04 21:44 UTC, AprilSylph commented
As per https://github.com/AprilSylph/XKit-Rewritten/issues/627#issuecomment-1146687116, relying on `canEdit` may disqualify the user's own Blazed posts from being counted as own posts by this logic. It would be nice to fix that!

An idea I have is to export two new constants in `user.js`: one of blogs where the user is an admin, and another of just those blogs' names. We could use the latter as an alternative to `canEdit`, something like...

```js
const isAdmin = adminBlogNames.includes(blog.name);

return (canEdit || isAdmin) && <group blog is-actually-mine assurance>;
```

There might be cases I'm not thinking of that this wouldn't cover, but intuitively it seems like this would be a solid fallback. If you can't edit it because you're not a blog admin and it's not your post, it's not your post. If you can't edit it but you are a blog admin, you'll probably be able to edit it later anyway, so continue with the checks.

As an aside, this actually has me happy that Quick Tags & Trim Reblogs literally only check for the edit button. I didn't know it was going to be possible for a post to be yours but not editable, but using dead simple assumptions has covered that case for those features already!

2022-06-04 22:00 UTC, marcustyphoon commented
Wait, if you're part of a group blog where you're not an admin... currently, if you make a post... then you can edit the post, `postAuthor === primaryBlogName` is true, and this returns true, right? Or do those not count as your own posts - I forget, now.

2022-06-04 22:58 UTC, AprilSylph commented
A post is "yours" if you made it or (regarding submissions) it can't be proven that you didn't publish it. Posts made on group blogs are editable by the post author (regardless of admin status) and all group admins.

2022-06-04 23:17 UTC, marcustyphoon commented
Right, so this would still lead to inconsistent results on posts you make on group blogs. `(canEdit || isAdmin)` would still depend on the blaze status of the post.

2022-06-05 21:58 UTC, AprilSylph requested changes
stupid problems require foolproof solutions

(this comment will be funnier if i actually missed a case here.)

2022-06-05 21:58 UTC, AprilSylph commented on src/util/react_props.js
> +import { primaryBlogName, adminBlogNames } from './user.js';
```suggestion
import { primaryBlogName, userBlogNames, adminBlogNames } from './user.js';
```

2022-06-05 21:58 UTC, AprilSylph commented on src/util/react_props.js
> +  const isAdmin = adminBlogNames.includes(blog.name);
```suggestion
  const userIsMember = userBlogNames.includes(blog.name);
  const userIsAdmin = adminBlogNames.includes(blog.name);
```

2022-06-05 21:58 UTC, AprilSylph commented on src/util/react_props.js
> +  return (canEdit || isAdmin) && (isSubmission || postAuthor === primaryBlogName || postAuthor === undefined);
```suggestion
  // Post belongs to the user's primary blog
  if (blog.name === primaryBlogName) return true;

  // Post belongs to the user's single-member sideblog
  if (postAuthor === undefined && userIsMember) return true;

  // Post was created by the user on a group blog
  if (postAuthor === primaryBlogName && !isSubmission) return true;

  // Submission belongs to group blog which the user is admin of
  if (isSubmission && userIsAdmin) return true;

  return false;
```

2022-06-05 21:58 UTC, AprilSylph commented on src/util/react_props.js
> +  const { blog, canEdit, isSubmission, postAuthor } = await timelineObject(postElement);
```suggestion
  const { blog, isSubmission, postAuthor } = await timelineObject(postElement);
```

2022-06-05 22:02 UTC, AprilSylph requested changes
also jsdoc on the new exports

2022-06-05 22:02 UTC, AprilSylph commented on src/util/user.js
> + * {object[]} userBlogs - An array of blog objects the current user has post access to
```suggestion
 * {object[]} adminBlogs - An array of blog objects the current user is admin of
```

2022-06-05 22:02 UTC, AprilSylph commented on src/util/user.js
> + * {string[]} userBlogNames - An array of blog names the current user has post access to
```suggestion
 * {string[]} adminBlogNames - An array of blog names the current user is admin of
```

2022-06-05 22:20 UTC, marcustyphoon commented
Perfect, thanks! Had a hell of a time trying to figure this one out. All of this looks correct to me!

Make sure you don't lose coauthor on this one :D

2022-06-06 21:22 UTC, AprilSylph approved these changes

2022-06-06 21:22 UTC, merged