NotificationBlock: Fix menu item missing on non-editable posts
AprilSylph/XKit-Rewritten pull request #630
Opened 2022-06-06 21:51 UTC by marcustyphoon

#### User-facing changes
- NotificationBlock menu items appear on non-editable posts

#### Technical explanation
The notificationblock menu item appears on any post from any of the user's blogs, regardless of whether the user has edit access to that post.

This makes sense for blazed posts the user has made, as well as group blog posts that the user didn't make and can't edit, as the user can still see notifications on those.

#### Issues this closes
resolves #627
(for real this time)

2022-06-08 19:20 UTC, marcustyphoon commented
Hm, you definitely are right that adding the UI to the notifications themselves solves a lot of weirdness.

I just noticed that it would - in theory - make sense to also have these buttons on any post containing one of your blogs in the reblog chain, in a way. After all, if I reblog user A's post, and I receive a notification that user B has reblogged my reblog, and I click that notification... it opens user B's blog. In that case, I have open a post which I might want to block future similar notifications from, in which I am neither the current post author nor the root post author.

2022-06-08 19:54 UTC, marcustyphoon commented
`blog.name` is equivalent to `blogName`, right?

2022-06-08 21:27 UTC, AprilSylph commented
I think `blogName` and `blog.name` should be the same, yeah.

2022-06-08 21:51 UTC, AprilSylph requested changes

2022-06-08 21:51 UTC, AprilSylph commented on src/scripts/notificationblock.js
> +  return (yourOriginalPost || yourReblog) && blockedPostTargetIDs.includes(rootId) === false;
These names aren't strictly accurate... `rebloggedRootName` will be undefined when viewing _any_ original post, which means all original posts when viewing your own blog would be counted as `yourReblog` rather than `yourOriginalPost`.

What's being tested for *is* correct though, so let's just combine the two constants.

```suggestion
  const canReceiveActivity = userBlogNames.includes(blogName) ||
    userBlogNames.includes(rebloggedFromName) ||
    userBlogNames.includes(rebloggedRootName);

  return canReceiveActivity && blockedPostTargetIDs.includes(rootId) === false;
```

2022-06-08 21:53 UTC, marcustyphoon commented on src/scripts/notificationblock.js
> +  return (yourOriginalPost || yourReblog) && blockedPostTargetIDs.includes(rootId) === false;
Oh, right! Whoops. Sometimes I think I need to just write documentation for the timelineObject fields for myself as if they were official API endpoints :D

2022-06-09 21:27 UTC, AprilSylph approved these changes

2022-06-09 21:28 UTC, merged