Tweaks: Add unsticky tab bar tweak
AprilSylph/XKit-Rewritten pull request #670
Opened 2022-07-20 19:08 UTC by marcustyphoon

Hiding is also an option, of course.

#### User-facing changes
- Adds a tweak to remove the sticky effect from the "following/for you" tab bar element.

#### Technical explanation
I wish there was a way to, like, find and remove the effect of a specific css rule, rather than overriding it with a set value.

#### Issues this closes
Related to: #645, #669

2022-07-20 21:45 UTC, marcustyphoon commented on src/scripts/tweaks.json
> +    },
Oh, whoops, I think that's where I meant to put it!

2022-07-23 21:57 UTC, AprilSylph requested changes

2022-07-23 21:57 UTC, AprilSylph commented on src/scripts/tweaks/unsticky_tab_bar.js
> +  ${keyToCss('timelineHeader')}${keyToCss('sticky')} { position: static; }
would be nice to remove the slide effect since that's visible if you scroll to the top of the page too quickly

```suggestion
  ${keyToCss('timelineHeader')}${keyToCss('sticky')} { position: static; transform: none; }
```

2022-07-23 22:03 UTC, AprilSylph approved these changes

2022-07-23 22:03 UTC, merged