Tweaks: Add full note count tweak
AprilSylph/XKit-Rewritten pull request #689
Opened 2022-08-01 18:43 UTC by marcustyphoon

#### User-facing changes
- Adds a tweak to display full note counts (1,234) instead of compact note counts (1.2k)

#### Technical explanation
Very similar to timeformat.

Using a pseudo element makes the note count non-selectable, which I personally find sort of annoying, but it looks like the note count isn't currently selectable anyway. Opinions on changing this?

#### Issues this closes
resolves #576

2022-08-01 19:00 UTC, marcustyphoon commented
Oh, interesting performance note: this won't use the `timelineObject` cache unless `timelineObject(noteElement)` is replaced by e.g. `timelineObject(noteElement.closest(postSelector))`, but that would require an exception to be made to work in the radar since postSelector doesn't select the radar post.

In MV2, this doesn't reeeeeeeally matter, but still. Will look for other edge cases with postSelector and the radar post.

2022-08-01 19:52 UTC, AprilSylph commented on src/scripts/tweaks/show_full_note_count.js
> +  const locale = code.replaceAll('_', '-');
```suggestion
  const locale = document.documentElement.lang;
```

2022-08-01 19:53 UTC, marcustyphoon commented on src/scripts/tweaks/show_full_note_count.js
> +  const locale = code.replaceAll('_', '-');
Ah, excellent!

2022-08-01 20:11 UTC, AprilSylph commented on src/scripts/tweaks/show_full_note_count.js
> +const numberFormat = await createNumberFormat().catch(() => new Intl.NumberFormat());
I don't believe this can fail now, so
```suggestion
const { lang } = document.documentElement;
const numberFormat = new Intl.NumberFormat(lang);
```

2022-08-07 22:11 UTC, AprilSylph requested changes

2022-08-07 22:11 UTC, AprilSylph commented on src/scripts/tweaks/show_full_note_count.js
> +  $('[data-full-notes]').removeAttr('data-full-notes');
Listeners first!

```suggestion
  pageModifications.unregister(formatNoteElements);
  styleElement.remove();
  $('[data-full-notes]').removeAttr('data-full-notes');
```

2022-08-13 21:38 UTC, AprilSylph approved these changes

2022-08-13 21:38 UTC, merged