Tag Replacer: Add extra API filter for peace of mind
AprilSylph/XKit-Rewritten pull request #693
Opened 2022-08-06 01:55 UTC by marcustyphoon

#### User-facing changes
- Probably none; small chance of fixing unexpected tag replacer behavior.

#### Technical explanation
In the off chance that the tag-filtered version of the `/v2/blog/[blog]/posts` can have or ever gets recommended posts (related posts from your blog without that specific tag?), this adds a filter to remove them. Yes, this is probably paranoia.

#### Issues this closes
n/a

2022-08-06 07:58 UTC, AprilSylph requested changes
`.includes()` is case-sensitive

2022-08-06 07:58 UTC, AprilSylph commented on src/scripts/tag_replacer.js
> +        const posts = response.posts.filter(({ canEdit, tags }) => canEdit === true && tags.includes(oldTag));
```suggestion
        const posts = response.posts.filter(({ canEdit, tags }) => canEdit === true && tags.some(tag => tag.toLowerCase() === oldTag.toLowerCase()));
```

2022-08-06 08:00 UTC, marcustyphoon commented on src/scripts/tag_replacer.js
> +        const posts = response.posts.filter(({ canEdit, tags }) => canEdit === true && tags.includes(oldTag));
Whoops. Sure am glad there's a review process for these things.

2022-08-28 22:13 UTC, AprilSylph commented
Hmm, yeah, I think this is best left out until necessary, if ever.

I'll let you close this PR so that you can reopen it later if needed. (Not sure if you being a collaborator allows you to reopen your own issues/PRs that I've closed - I know normal users definitely can't.)

2022-08-28 23:00 UTC, closed without merging