Rename "you're caught up" carousel references
AprilSylph/XKit-Rewritten pull request #704
Opened 2022-08-16 02:09 UTC by marcustyphoon

I don't know. I hate this. Can we put a picture of the element in question inline in the settings panel?

#### Issues this closes
resolves #643

2022-08-27 21:50 UTC, AprilSylph commented
Tumblr still doesn't have a good name for this internally.

How about briefly describing it? "The Changes/Shop/etc. links carousel" is unambiguous.

2022-08-27 22:11 UTC, marcustyphoon commented
Hmm. They all seem... fine.

| |
| - |
| <img width="374" alt="Screen Shot 2022-08-27 at 3 08 30 PM" src="https://user-images.githubusercontent.com/8336245/187049629-426d3ce1-610a-43c2-bab5-73e2d68c8373.png"> | 
| <img width="376" alt="Screen Shot 2022-08-27 at 3 07 58 PM" src="https://user-images.githubusercontent.com/8336245/187049630-e76a5b70-85c3-4478-8e89-8eb14442e86a.png"> | 
| <img width="373" alt="Screen Shot 2022-08-27 at 3 07 32 PM" src="https://user-images.githubusercontent.com/8336245/187049631-790ca4cf-868b-40c5-b318-11fb2038872f.png"> | 
| <img width="376" alt="Screen Shot 2022-08-27 at 3 06 49 PM" src="https://user-images.githubusercontent.com/8336245/187049632-caf8c82f-a8a2-45fc-a6a0-3a34e00098c4.png"> | 
| <img width="376" alt="Screen Shot 2022-08-27 at 3 06 02 PM" src="https://user-images.githubusercontent.com/8336245/187049633-d30735e0-80c8-45d7-994e-3226a9d729b0.png"> |

2022-08-27 22:29 UTC, AprilSylph requested changes

2022-08-27 22:29 UTC, AprilSylph commented on src/scripts/accesskit.json
> +      "label": "De-animate the dashboard \"caught up\" carousel",
```suggestion
      "label": "De-animate the Changes/Shop/etc. links carousel",
```

2022-08-27 22:29 UTC, AprilSylph commented on src/scripts/tweaks.json
> +      "label": "Turn the dashboard \"caught up\" carousel into a separating line",
```suggestion
      "label": "Turn the Changes/Shop/etc. links carousel into a separating line",
```

2022-08-28 09:44 UTC, AprilSylph approved these changes

2022-08-28 09:44 UTC, merged