Scroll to Bottom: fixes
AprilSylph/XKit-Rewritten pull request #713
Opened 2022-08-20 01:22 UTC by marcustyphoon

wip

#### User-facing changes
- 

#### Technical explanation

#### Issues this closes

2022-08-20 01:23 UTC, marcustyphoon commented
- [ ] call stopScrolling on navigation somehow

Man, I wish #453 was less... hacky.

2022-08-21 22:04 UTC, AprilSylph commented on src/scripts/scroll_to_bottom.js
> +  const glassContainerOpen = document.getElementById('glass-container')?.hasChildNodes();
Is this reliable again? Last I knew, the glass container doesn't have an ID at all if the first route has glass (e.g, `/new/text`), hence the usage of `[role="dialog"]` glass checks everywhere.

2022-08-21 22:11 UTC, marcustyphoon commented on src/scripts/scroll_to_bottom.js
> +  const glassContainerOpen = document.getElementById('glass-container')?.hasChildNodes();
a) That is a good question! I didn't see any instances where it didn't on a quick check, but I'm not sure exactly where to look. However:
b) I just noticed this makes scroll to bottom stop if you accidentally mouse over a blog avatar.

Uh. Oops.

2022-08-29 10:08 UTC, AprilSylph commented on src/scripts/scroll_to_bottom.js
> +${keyToCss('timeline', 'blogRows')} > ${keyToCss('loader')},
What are `blogRows`?

2022-08-29 10:10 UTC, AprilSylph commented on src/scripts/scroll_to_bottom.js
> +${keyToCss('timeline', 'blogRows')} > ${keyToCss('loader')},
Oh wait, I see, it's follower/following lists. I guess those are rows of blogs.

2022-08-29 10:19 UTC, AprilSylph requested changes

2022-08-29 10:19 UTC, AprilSylph commented on src/scripts/scroll_to_bottom.js
> +  display: none;
The hiding CSS was the way it was for a reason; it allows the scroll to bottom button to fade out/in with the scroll to top button when peepr is opened/closed.
```suggestion
  opacity: 0;
  pointer-events: none;
```

2022-08-29 10:21 UTC, marcustyphoon commented on src/scripts/scroll_to_bottom.js
> +  display: none;
Hmmm. Makes sense; I guess non-modal blog view will need a different solution.

2022-08-29 10:41 UTC, marcustyphoon commented on src/scripts/scroll_to_bottom.js
> +  display: none;
Almost works, but it glitches briefly when you scroll up in non modal blog view. Oh well, really not important.

```diff
  ${keyToCss('isPeeprShowing')} #${scrollToBottomButtonId} {
    opacity: 0;
    pointer-events: none;
  }

+ ${keyToCss('isPeeprShowing')} button:not(${keyToCss('hidden')}) + #${scrollToBottomButtonId} {
+   display: none;
+ }
```

2022-08-29 16:33 UTC, AprilSylph approved these changes
Shame to merge this without a fix for the non-modal blog view issue, but it's minor enough (doesn't impair use) and the other fixes are more important.

Also, I was going to say this fixes #619 for me, but I only tested it going from my drafts to the dashboard. If going between drafts and the queue still doesn't deactivate scroll to bottom by itself, I don't think it ever did, and I'd be tempted to classify that behaviour as working as intended.

2022-08-29 16:33 UTC, merged

2022-08-29 19:47 UTC, marcustyphoon commented
Interesting; I swore that going from drafts to dashboard wasn't stopping it for me, but it certainly is now. It's triggering the "no loader" code; it looks like `checkForButtonRemoved` isn't doing much of anything at the moment.

Anyway, yes, I think "I clicked a UI element while scroll to bottom was actively making my page jump around" having nonobvious behavior doesn't even really count as a bug almost regardless of what that behavior is, because... you know, why, and what were you expecting :D

I do like the currently unimplemented behavior of "clicking the Tumblr logo stops scroll to bottom on the dashboard" though.