Postblock: Make options UI items links if possible
AprilSylph/XKit-Rewritten pull request #719
Opened 2022-08-22 19:48 UTC by marcustyphoon

#### User-facing changes
- Postblock's options UI links to posts you have blocked, so you can tell what they actually are if you want to unblock them. Posts that have not been seen since this upgrade won't have links, since we didn't store the required information previously.
- When viewing a single blocked post in /blog/view, there is a visual indicator with an unhide button instead of, you know, nothing. 

#### Technical explanation
Committing with two storage keys since that's how I implemented it first. Kind of a waste of storage to store every blocked post twice, of course; transitioning to an array of `[id, ?uuid]` is probably better.

This all feels like a hot mess so idk. Drafting for now even though it's fully functional.

#### Issues this closes
discussion #402

2022-12-02 04:42 UTC, marcustyphoon commented
Uhhhhhhh. Is this impossible now? Can you no longer go to a post on a blog given the blog UUID and post ID?

2022-12-08 20:48 UTC, AprilSylph commented
Shit, really? What happens if you do? (Mainly want to see if it ends up on a Redpop 404 page; if it does, my redirection code handling this is busted but can probably be fixed.)

2022-12-08 21:11 UTC, marcustyphoon commented
does work (post, name):
**Blog network:** https://april.tumblr.com/post/661324787743948800/
**Blog view (new):** https://www.tumblr.com/april/661324787743948800/, https://tumblr.com/april/661324787743948800/
**Blog view (new, @):** https://www.tumblr.com/@april/661324787743948800/, https://tumblr.com/@april/661324787743948800/
**Blog view (old):** https://www.tumblr.com/blog/view/april/661324787743948800/, https://tumblr.com/blog/view/april/661324787743948800/
**Branch.io:** https://at.tumblr.com/april/im-april-im-a-web-developer-who-makes-things/sso2gjczjg24

does work (blog, uuid):
**Blog view (new, @):** https://www.tumblr.com/@t:Fft_7iTGnBlHdl-UtlllwQ, https://tumblr.com/@t:Fft_7iTGnBlHdl-UtlllwQ
**Blog view (old):** https://www.tumblr.com/blog/view/t:Fft_7iTGnBlHdl-UtlllwQ, https://tumblr.com/blog/view/t:Fft_7iTGnBlHdl-UtlllwQ

doesn't work (blog, uuid):
**Blog view (new):** https://www.tumblr.com/t:Fft_7iTGnBlHdl-UtlllwQ

doesn't work (post, uuid):
**Blog view (new, @):** https://www.tumblr.com/@t:Fft_7iTGnBlHdl-UtlllwQ/661324787743948800, https://tumblr.com/@t:Fft_7iTGnBlHdl-UtlllwQ/661324787743948800
**Blog view (old):** https://www.tumblr.com/blog/view/t:Fft_7iTGnBlHdl-UtlllwQ/661324787743948800, https://tumblr.com/blog/view/t:Fft_7iTGnBlHdl-UtlllwQ/661324787743948800

doesn't work: blog/view/@username, anything with /post/

2023-02-16 00:41 UTC, marcustyphoon commented
Oh, I guess that's a silly reason to abandon this; it can just look up the blog name via an API request before navigation. Well, not "just," actually, since we can't access apiFetch from a settings panel. But it's solvable.

2025-07-31 21:14 UTC, marcustyphoon commented
#1544 breaks this, as it currently inserts an element before the `article` in a hidden post with the intention that the element is shown when the post is hidden.

2025-10-17 21:40 UTC, marcustyphoon commented
- [x] make link color reasonable in firefox dark mode

2026-03-06 16:52 UTC, marcustyphoon commented
- [x] check/sync #1755, #1445 #2115, #2117, other potential changes

2026-03-06 17:39 UTC, AprilSylph commented
Hold on, couldn't this be massively simplified by just storing the `shortUrl` from each blocked post? It wouldn't always link to the blog view, but the blog network always links to the blog view... it wouldn't be quite as good for UX, but it would be extremely reliable, no?

2026-03-06 17:48 UTC, marcustyphoon commented
Hm, probably, assuming that posts always have those, they don't change when a user changes blog names, and they're stored/hosted/whatever in a way we think will persist. I would trust an ex-tumblr-employee to have a better idea of that than I would! Do you think it's a good idea?

2026-03-06 19:53 UTC, AprilSylph commented
Reliability-wise they are exactly as good as a blog UUID and post ID, if not better. They continue to work through blog name changes and, although this has never happened, I _believe_ through a blog UUID change as well. They're a very _very_ old part of Tumblr. The only downside is that they will always go to the post on the blog's custom theme, if it has one. (I'm not even sure it goes to the blog view immediately if the blog doesn't? It might be a chain-redirect in that case.)

2026-03-06 20:03 UTC, marcustyphoon commented
> They're a very _very_ old part of Tumblr.

You know, I'm sure that's meant to sound reassuring, but... :D

2026-03-06 20:20 UTC, marcustyphoon commented
Ah: this will require some network fetching because we block posts by root id, and "the short url of the root post of this reblog" naturally isn't included in a post's data. Not the end of the world, but it does mean we have to think about no-longer-accessible posts and a bit more async stuff. `rebloggedRootUuid` is a pretty convenient field.

2026-03-06 20:48 UTC, marcustyphoon commented
#2141 / https://github.com/AprilSylph/XKit-Rewritten/pull/2141/changes/2ff88469ed834e37a57582aef308eff78affae49. Not too bad.

2026-03-06 20:52 UTC, AprilSylph commented
> > They're a very _very_ old part of Tumblr.
> 
> You know, I'm sure that's meant to sound reassuring, but... :D

Okay, fine: the system is very old _and_ is still driving enough traffic that it can't just be axed.

It's tried and true, here to stay, proven working, decades-scale reliable.

If it ever does get cut... the broken links in PostBlock will be a drop in the ocean.

2026-03-06 21:01 UTC, marcustyphoon commented
> I would love to do this, but those links would rot very easily. Tumblr needs a way for UUIDs to be translated into blog URLs without an authorised API call tbqh. I think I tested at some point that `shortUrl` links break across blog name changes, but maybe I'm wrong/misremembering/outdated. Something to test again for sure.
> 
> _Originally posted by @AprilSylph in https://github.com/AprilSylph/XKit-Rewritten/discussions/402#discussioncomment-2016210_

Oh hey. That's fairly funny. I guess we never did test again for sure, huh.

2026-03-06 22:28 UTC, AprilSylph commented
Well, I'm completely misremembering in one of these comments. Wouldn't it be really funny if it was the one I made after working at Tumblr, and not the one before? We really do need to test it to be sure.

2026-03-12 14:28 UTC, marcustyphoon commented
https://www.tumblr.com/url-change-test-54375/810890566411878400/sdlfjn

Ah, fuck.

2026-03-12 14:48 UTC, AprilSylph commented
<img height="128" width="128" src="https://discord.com/assets/8ad827d7dad91d44.svg">

2026-04-09 17:38 UTC, marcustyphoon commented
~~Wait. Why does the short link in the post I linked work. What.~~

edit: now it doesn't? did I mix up my tabs? what am I smoking

2026-04-21 10:03 UTC, AprilSylph requested changes

2026-04-21 10:03 UTC, AprilSylph commented on src/features/postblock/options/index.js
> +        a.href = `https://www.tumblr.com/?xkit-postblock-open-post-id=${blockedPostID}`;
I think we shouldn't potentially open the following feed during this process; it unexpectedly moves the "You're caught up" carousel (even if it's not called that anymore).

Could we change this to use the blog view as a base instead? That way we even load the right route chunks! e.g. `https://www.tumblr.com/@${uuids[blockedPostID]}?postblock-id=${blockedPostID}`

2026-04-21 10:03 UTC, AprilSylph commented on src/features/postblock/options/index.js
> +const uuidsStorageKey = 'postblock.uuids';
nit: prefer less-ambiguous naming

suggestion: `'postblock.blockedPostBlogUUIDs'`

2026-04-21 10:29 UTC, AprilSylph commented on src/features/postblock/index.js
> +    };
This should be extracted out of `processPosts`, it doesn't need to be recreated every time here, right?

2026-04-21 10:29 UTC, AprilSylph commented on src/features/postblock/index.js
> +    saveUuidPair(rebloggedFromId, rebloggedFromUuid);
nit: this is just... unsatisfying. least-to-most immediate or most-to-least, I don't care, just pick one

```suggestion
    saveUuidPair(rebloggedRootId, rebloggedRootUuid);
    saveUuidPair(rebloggedFromId, rebloggedFromUuid);
    saveUuidPair(id, uuid);
```

```suggestion
    saveUuidPair(id, uuid);
    saveUuidPair(rebloggedFromId, rebloggedFromUuid);
    saveUuidPair(rebloggedRootId, rebloggedRootUuid);
```

2026-04-21 17:43 UTC, marcustyphoon commented on src/features/postblock/options/index.js
> +        a.href = `https://www.tumblr.com/?xkit-postblock-open-post-id=${blockedPostID}`;
I like it. Potentially. The redirect from `@${uuid}` appears to strip the query param, unfortunately; any idea how to get around that if I'm right?

2026-04-22 09:32 UTC, AprilSylph commented on src/features/postblock/options/index.js
> +        a.href = `https://www.tumblr.com/?xkit-postblock-open-post-id=${blockedPostID}`;
Ah, bum.

Well, hashes aren't stripped: https://www.tumblr.com/@t:Fft_7iTGnBlHdl-UtlllwQ#813969316148051968

2026-04-23 15:11 UTC, marcustyphoon commented on src/features/postblock/index.js
> +    };
Honestly, I might make this a forEach.

2026-04-23 15:37 UTC, marcustyphoon commented
Hm. Not sure if:

- this url hash should be prefixed (`post-id-${blockedPostID}` or whatever)
- this code should skip the extra api fetch since we have the blog name in location.pathname now

2026-04-24 08:10 UTC, AprilSylph commented
I would prefix it with `postBlock:` and drop the API fetch, I think.

* Test that the hash starts with `postBlock:`
* Check that the rest of the hash consists of only `0-9`
* Check that the rest of the hash is a valid length for a post ID (don't remember what the upper bound is, sorry)
* ```js
  tumblr.navigate(`./${postId}`);
  ```

2026-04-24 14:22 UTC, marcustyphoon commented
re: dropping the api fetch, do we know if it's possible for there to be a trailing slash on the url post redirect? I assume there's no reason that would ever happen?

(aside: I feel like js needs better primitives for url path segments; the moment I write .split('/').filter(Boolean) I feel very silly, and that's even avoiding the magic number stuff most people use)

2026-04-24 14:23 UTC, marcustyphoon commented
...oh, I missed the implications of the last line of your comment. never mind!

2026-04-28 08:30 UTC, AprilSylph requested changes

2026-04-28 08:30 UTC, AprilSylph commented on src/features/postblock/index.js
> +
I think it's fine to have the hash persist if you go back, as long as you aren't redirected again (which you wouldn't be, since this isn't in any kind of listener).


```suggestion
```

2026-04-28 08:30 UTC, AprilSylph commented on src/features/postblock/index.js
> +  }, 'unblock it');
I think we shouldn't have an unblock button here... but we _should_ have an unblock button in the post's meatballs menu once revealed, similar to NotificationBlock.

2026-05-06 09:01 UTC, marcustyphoon commented on src/features/postblock/index.js
> +  }, 'unblock it');
I suppose that would mean just having the show button remove/hide the whole warning, probably?

2026-05-06 09:10 UTC, AprilSylph commented on src/features/postblock/index.js
> +  }, 'unblock it');
Yep!

2026-05-06 09:15 UTC, marcustyphoon commented
Ah, this PR straight-up merge conflicts with #2132, doesn't it. So if I merge this PR, I'll then be immediately deleting some of the code in it in that PR. Fun!

2026-05-06 10:10 UTC, marcustyphoon commented
Feel free to bikeshed 03fd22f.

2026-05-26 09:47 UTC, AprilSylph approved these changes
After four years in development, hopefully it will have been worth the wait.

2026-05-26 19:56 UTC, marcustyphoon commented on src/features/postblock/index.css
> +:root[style*="--font-family-modern"] .xkit-postblock-hidden-post-controls {
@AprilSylph is this Palettes for Tumblr compat?

2026-05-27 09:00 UTC, AprilSylph commented on src/features/postblock/index.css
> +:root[style*="--font-family-modern"] .xkit-postblock-hidden-post-controls {
Yep!

2026-05-27 11:26 UTC, marcustyphoon commented
It might be a liiiittle hard to see on some palettes? But, like, eh. Do I really want to bikeshed the bikeshedding? No, not really. (And we can always change it later.)

<img width="615" src="https://github.com/user-attachments/assets/2f21572c-e7b4-4a65-bd35-b8a1730f7a0c" />

<img width="615" src="https://github.com/user-attachments/assets/d72daa52-01f7-4c81-a4d9-2bee168bfa7e" />

2026-05-27 22:00 UTC, merged

2026-10-28 14:33 UTC, marcustyphoon commented
> [tumblr.com/url-change-test-54375/810890566411878400/sdlfjn](https://www.tumblr.com/url-change-test-54375/810890566411878400/sdlfjn)
> 
> Ah, fuck.

Again: the short link in here *does* work now. What?