Enhancement: PostBlock blocks instantly.
AprilSylph/XKit-Rewritten pull request #898
Opened 2022-12-06 23:41 UTC by alleycatboy

### Description

Addresses issue #894 reported by @marcustyphoon by using the same caching as Seen Posts to block posts during soft navigation.

### Testing steps

Enable PostBlock script and use as normal.

2022-12-06 23:52 UTC, marcustyphoon commented on src/scripts/postblock.js
> +  ));
This obviously should cause no problems in this case, but as a pattern I think it's probably best to await setup functions before registering effects, so that none of the code can run with uninitialized variables.

2022-12-06 23:52 UTC, marcustyphoon commented on src/scripts/postblock.js
> +  }
I see you switched from async-await to .then() - any particular reason?

2022-12-07 04:13 UTC, alleycatboy commented on src/scripts/postblock.js
> +  }
After a some speed testing I've found that as the user accumulates more blocks and scrolls the dashboard, the time to block each post sequentially with the thread blocking `await` increases rapidly, mainly due to the response time of `timeline` object.

Using `then` splits off the scope until the response is ready, and reduces the time to block on average by 1ms and the reduction increases as the user scrolls further blocks more.

The real gains come when unblocking the posts. Using `then` removes them in constant time, about 4.11ms every single time.  Using `await` begins at 9.79ms and increases by about 0.2ms per per post. 

And that's just with not too extensive dash scrolling, the numbers keep going up as I go further.

2022-12-07 04:37 UTC, marcustyphoon commented on src/scripts/postblock.js
> +  }
...Hm. Interesting. Was your test with async-await still using the await inside the forEach, or was that including your change to for-of?

I'll have to go try this and verify if I'm correct, but my understanding is that:

```js
// awaits simultaneously
const exampleOne = (posts) => {
  posts.forEach(async (post) => {
    before();
    await someFunction(post);
    after();
  });
};

// awaits simultaneously; identical behavior to first example unless you transpile earlier than es2017
const exampleTwo = (posts) => {
  for (const post of posts) {
    before();
    someFunction(post).then(() => after());
  }
};

// awaits sequentially; slower then the other two ways if someFunction resolves in a new task
const exampleThree = async (posts) => {
  for (const post of posts) {
    before();
    await someFunction(post);
    after();
  }
};
```

`await` doesn't "block" the thread per se; it's essentially syntactic sugar for `then()` but it preserves function scope/context.

Something else must be up, though; even if you were testing the "third" way here with a sequential await in a loop, our `timelineObject` implementation resolves in the same event loop task, so I wouldn't expect it to take a measurably different amount of time in that case. That's really interesting. Are you testing in Firefox or a Chromium-based browser?

2022-12-07 07:53 UTC, marcustyphoon commented on src/scripts/postblock.js
> +  }
Hm, those numbers look weird to me. What did you measure? I'm observing that step taking like 1ms, so I can't produce a multiple-millisecond time difference (Chromium). Maybe Firefox behaves differently; I've seen optimizations go the other way on it before.

> When the results aren't used, splitting off can provide a "more asynchronous" experience.

Not exactly sure what you mean by this! If the results aren't used at all and you don't care about sequencing, you can use neither await nor then, correct? 

> In either case, do you think it would be overkill to catch the potential exceptions thrown by timelineObject? The function throws up the exceptions in inject, but it seems like that isn't a realistic concern. Unless it's already being handled?

I don't think we generally explicitly handle `timelineObject` exceptions unless there's a specific action we' like to take in that case besides silently failing. I do try to keep in mind how large the effect of an individual error would be, of course (to avoid things like #874).

If we wanted those failures not to be silent, the best way IMO would be to attach error and unhandledrejection listeners to `window`, as that would only have to be done once (i.e. #472).

2022-12-07 10:01 UTC, marcustyphoon commented on src/scripts/postblock.js
> +  }
Both! Strange. `timelineObject` is cached, so it should be basically instant as long as you've already seen the posts (inside a promise, of course, so if you time a `then` or `await` you'll still be measuring the duration of everything already in the microtask queue when you make the call; [one can have a fair amount of fun with this](https://gist.github.com/marcustyphoon/b8e08636501c478f05efe695d4badcbd)).

You said you were testing blocking and unblocking, which would mean the task doing this would have been triggered by the storage mutation callback running onStorageChanged, which... shouldn't have any other asynchronous code in it, so the microtask queue should be empty. Oh well, no idea why it would be different!

> Thoughts on using a `Promise.all(filterPostElements(postElement , {...}).map(async postElement => {`?

This is equivalent to `filterPostElements(postElement , {...}).forEach(async postElement => {` if you don't have any code you need to run after all of the callbacks resolve, right? That would just discard the callback's return values instead of collecting them.

2022-12-07 16:52 UTC, alleycatboy commented on src/scripts/postblock.js
> +  }
> This is equivalent to `filterPostElements(postElement , {...}).forEach(async postElement => {` if you don't have any code you need to run after all of the callbacks resolve, right?

True! Let's stick with the `forEach` instead of the `for...of` as well!

2022-12-11 22:22 UTC, alleycatboy commented
Now using CSS selectors instead of directly adding/removing classes as suggested [here](https://github.com/AprilSylph/XKit-Rewritten/pull/898/commits/8ebcf10ac27cb382f0b0ee84fac3c1353930e13b).

2023-02-21 02:03 UTC, marcustyphoon requested changes
The GitHub review UI apparently doesn't let me make a code suggestion when there's a CI warning in the "files changed" interface, but as per that warning, you can combine the two imports from the same file.

2023-02-21 06:52 UTC, marcustyphoon reviewed
`postblock.css` can be removed as part of this, as it is no longer used! Addtionally:

2023-02-21 06:52 UTC, marcustyphoon commented on src/scripts/postblock.js
> +      postElement.dataset.targetRootId = rootID;
These need to be removed in `clean()`!

2023-02-21 06:52 UTC, marcustyphoon commented on src/scripts/postblock.js
> +    .map((rootId) => `[data-target-root-id="${rootId}"]`)
Here we should target the `article` elements within the post elements, not the post elements themselves, to avoid breaking J/K scrolling.

2024-07-13 19:24 UTC, closed without merging