Quote Replies: Show all buttons when using touchscreen
AprilSylph/XKit-Rewritten pull request #900
Opened 2022-12-08 05:15 UTC by marcustyphoon

### Description

This shows the Quote Replies button whether or not the user is hovering over a notification if they're using a device without the ability to hover or if they have made use of the touchscreen since the extension was turned on.

I didn't worry about the fact that Tumblr's block buttons don't have this behavior, but still take up some space, so the spacing does look a bit odd.

I did try this on a Surface device without a keyboard attached, and the media query works in that case, so I think one could make a reasonable argument that the media query alone is sufficient and the on-touch behavior change is unnecessary, and users with touchscreen laptops with trackpads can just use the trackpads. I could go either way on this.

Resolves #895

### Testing steps

- Enable Quote Replies and navigate to the notifications page on a touchscreen-only mobile device. Quote Replies buttons should appear on replies.
- Enable Quote Replies and navigate to the notifications page on a laptop with a touchscreen. Use the touchscreen to interact with the page. Quote Replies buttons should appear on replies.

2022-12-09 10:22 UTC, AprilSylph requested changes
Better to assume the feature's absence and then test for its existence rather than vice-versa

```diff
  button.xkit-quote-replies svg {
    width: 21.5px;
    height: 21.5px;

    fill: rgb(var(--blue));
-   opacity: 0;
-   transform: scale(0);
    transition: all .25s ease-out .4s;
  }

+ @media (hover: hover) {
+   button.xkit-quote-replies svg {
+     opacity: 0;
+     transform: scale(0);
+   }
+
+   :is(:hover, :focus-within) > button.xkit-quote-replies svg {
+     opacity: 1;
+     transform: scale(1);
+   }
+ }
```

2022-12-09 10:48 UTC, AprilSylph reviewed
I can see what you're trying to do with the event listener, but... it's pretty safe to assume that if a trackpad is being recognised as the primary pointing device by the browser, that it's probably being used as such. Do you have a hybrid device that you're testing this with? Is that assumption flawed?

2022-12-09 10:48 UTC, AprilSylph commented on src/scripts/quote_replies.css
>  }
```suggestion
```

2022-12-09 10:48 UTC, AprilSylph commented on src/scripts/quote_replies.js
> +const touchClass = 'xkit-quote-replies-touch';
```suggestion
```

2022-12-09 10:48 UTC, AprilSylph commented on src/scripts/quote_replies.js
> +const addTouchClass = () => document.body.classList.add(touchClass);
```suggestion
```

2022-12-09 10:48 UTC, AprilSylph commented on src/scripts/quote_replies.js
> +  document.body.addEventListener('touchstart', addTouchClass, { once: true });
```suggestion
```

2022-12-09 10:48 UTC, AprilSylph commented on src/scripts/quote_replies.js
> +  document.body.removeEventListener('touchstart', addTouchClass);
```suggestion
```

2022-12-09 10:48 UTC, AprilSylph commented on src/scripts/quote_replies.js
> +  document.body.classList.remove(touchClass);
```suggestion
```

2022-12-09 10:49 UTC, AprilSylph commented on src/scripts/quote_replies.css
> +  :is(:hover, :focus-within)>button.xkit-quote-replies svg {
```suggestion
  :is(:hover, :focus-within) > button.xkit-quote-replies svg {
```

2022-12-09 17:00 UTC, marcustyphoon commented
>  I think one could make a reasonable argument that the media query alone is sufficient and the on-touch behavior change is unnecessary, and users with touchscreen laptops with trackpads can just use the trackpads. I could go either way on this.

That's what I was trying to describe here! The touch event listener only serves to facilitate someone who has a traditional laptop with a touchscreen but prefers to use the touchscreen over the trackpad, which seems niche. (I don't know if this would apply to "iPad with a magic keyboard attached," but we don't build for Safari anyway.)

2023-02-27 12:23 UTC, merged

2023-03-15 18:58 UTC, marcustyphoon commented
This appears not to work in Kiwi Browser 107 on my phone even though it does in Firefox Nightly. I assume that's probably a Kiwi Browser bug but it's a huge pain to investigate on my 2016-era device.