Quote Replies: Enable quoting mentions
AprilSylph/XKit-Rewritten pull request #901
Opened 2022-12-08 06:27 UTC by marcustyphoon

Now that I've thought about it more, I guess I can see how this is sort of weird to do in practice in some cases? I dunno. 

### Description

Enables Quote Replies on notes about replies that mention you on posts which are not yours, in addition to its current function that works on replies to your own posts whether they mention you or not.

This does not enable the script on notes about posts in which you're mentioned in the actual post (those, you can just reblog).

Resolves #861.

### Testing steps

- Find a note about a mention (purple at sign). Use Quote Replies on it.
- Find a note about a mention on a sideblog. Use Quote Replies on it.

2023-02-18 17:13 UTC, AprilSylph requested changes

2023-02-18 17:13 UTC, AprilSylph commented on src/scripts/quote_replies.js
> +  const { response: { id: responseId, displayText } } = await apiFetch(`/v2/blog/${yourUuid}/posts`, { method: 'POST', body: { content, state: 'draft', tags } });
I don't think these changes are necessary. Quote Replies should always create drafts on the blog you're viewing activity for, but this logic looks for the first mention of any of your blogs, and then changes the target accordingly. Why?

If a reply mentions both my main blog and my sideblog, I don't care about what order those mentions are in; if I'm viewing my main blog's activity and quote that reply, I expect to be acting as my main blog. Likewise, if I am viewing my sideblog's activity, I expect to be acting as my sideblog.

2023-02-18 17:17 UTC, AprilSylph commented on src/scripts/quote_replies.js
> +  const { response: { id: responseId, displayText } } = await apiFetch(`/v2/blog/${yourUuid}/posts`, { method: 'POST', body: { content, state: 'draft', tags } });
We already check if the reply's timestamp matches the activity item's timestamp for handling deleted replies up on L76, too.

2023-02-18 17:18 UTC, marcustyphoon commented on src/scripts/quote_replies.js
> +  const { response: { id: responseId, displayText } } = await apiFetch(`/v2/blog/${yourUuid}/posts`, { method: 'POST', body: { content, state: 'draft', tags } });
If I recall correctly, in this code, in this location, if you are quote replying a mention, `uuid` isn't your blog's: it's the blog that posted the post which the reply was on, which you may not even own.

2023-02-18 17:21 UTC, AprilSylph commented on src/scripts/quote_replies.js
> +  const { response: { id: responseId, displayText } } = await apiFetch(`/v2/blog/${yourUuid}/posts`, { method: 'POST', body: { content, state: 'draft', tags } });
Ah, that's annoying.

2023-02-18 17:21 UTC, marcustyphoon commented on src/scripts/quote_replies.js
> +  const { response: { id: responseId, displayText } } = await apiFetch(`/v2/blog/${yourUuid}/posts`, { method: 'POST', body: { content, state: 'draft', tags } });
Yeah, I think that's it. Want me to rename it to e.g. `postAuthorUuid` for clarity?

2023-02-18 17:27 UTC, AprilSylph commented on src/scripts/quote_replies.js
> +  const { response: { id: responseId, displayText } } = await apiFetch(`/v2/blog/${yourUuid}/posts`, { method: 'POST', body: { content, state: 'draft', tags } });
I think I'd prefer removing the prop renames from L38-41

2023-02-18 17:36 UTC, marcustyphoon commented on src/scripts/quote_replies.js
> +  const { response: { id: responseId, displayText } } = await apiFetch(`/v2/blog/${yourUuid}/posts`, { method: 'POST', body: { content, state: 'draft', tags } });
Oh, yep, much better.

2023-02-18 17:46 UTC, AprilSylph requested changes

2023-02-18 17:46 UTC, AprilSylph commented on src/scripts/quote_replies.js
> +  )?.blog;
I still would like to account for the possibility of multiple mentioned blogs belonging to the same account. If we can't do it via the notification's props, surely we could go higher in the React tree to extract the endpoint it was fetched with?

2023-02-18 17:50 UTC, marcustyphoon commented on src/scripts/quote_replies.js
> +  )?.blog;
Oh, activity pages are per-blog. Right—no idea why I thought there was just the one. Will check on that.

2023-02-18 18:08 UTC, marcustyphoon commented on src/scripts/quote_replies.js
> +  )?.blog;
Well, that was substantially less convoluted.

2023-03-08 22:20 UTC, AprilSylph approved these changes

2023-03-08 22:20 UTC, merged