Meatballs util: Enable meatball items in blog menus
AprilSylph/XKit-Rewritten pull request #910
Opened 2022-12-12 22:23 UTC by marcustyphoon

### Description

This creates `registerBlogMeatballItem`/ `unregisterBlogMeatballItem`, allowing scripts to add meatball items to the meatball menus in blog cards and the blog view header.

### Testing steps

n/a

2023-03-08 09:24 UTC, marcustyphoon commented
Worth noting, I guess, that I didn't put much thought into this API; perhaps it's better to add configuration to the register and unregister functions so scripts can register once for both post and user meatball menus if the menu items they're registering are substantially similar? Thinking about it now, I think one might want to make the labels different in that case, though. So actually, eh, this seems fine.

2023-04-30 22:23 UTC, AprilSylph requested changes
didn't test the demo but code looks good, though I have some nitpicks about variable naming. The suggestions are backwards because I fumbled the selected lines for the first one and didn't notice until I'd done the others, whoops.

There's a high likelihood that I missed some usages anyway.

2023-04-30 22:23 UTC, AprilSylph commented on src/util/meatballs.js
> +    const { label, onclick, postFilter } = blogMeatballItems[id];
```suggestion
    const { label, onClick, blogFilter } = blogMeatballItems[id];
```

2023-04-30 22:23 UTC, AprilSylph commented on src/util/meatballs.js
> +      click: onclick
```suggestion
      click: onClick
```

2023-04-30 22:23 UTC, AprilSylph commented on src/util/meatballs.js
> +      const shouldShowItem = postFilter(__blogData);
```suggestion
    if (blogFilter instanceof Function) {
      const shouldShowItem = blogFilter(__blogData);
```

2023-04-30 22:23 UTC, AprilSylph commented on src/util/meatballs.js
> +  blogMeatballItems[id] = { label, onclick, postFilter };
1. I've regretted the casing of `onclick` for a while now
2. `postFilter` doesn't make sense if we're not filtering posts :P

```suggestion
 * @param {Function} options.onClick - Button click listener function
 * @param {Function} [options.blogFilter] - Filter function, called with the blog data of the menu element being actioned on. Must return true for button to be added. Some blog data fields, such as "followed", are not available in blog cards.
 */
export const registerBlogMeatballItem = function ({ id, label, onClick, blogFilter }) {
  blogMeatballItems[id] = { label, onClick, blogFilter };
```

(I thought about suggesting `postFilter` &rarr; `filter` but I probably had a reason for not going for `filter` for post meatball items, maybe to avoid confusion with `Array.prototype.filter`?)

2023-04-30 22:24 UTC, marcustyphoon commented on src/util/meatballs.js
> +  blogMeatballItems[id] = { label, onclick, postFilter };
I'll merge then take a look!

2023-04-30 22:29 UTC, marcustyphoon commented on src/util/meatballs.js
> +  blogMeatballItems[id] = { label, onclick, postFilter };
Ah, I see; changing to `onClick` in the current meatballs utils would require a big diff.

2023-04-30 22:40 UTC, AprilSylph approved these changes

2023-04-30 22:40 UTC, merged