Fix Chrome script loading inconsistency via preload
AprilSylph/XKit-Rewritten pull request #945
Opened 2023-01-29 00:28 UTC by marcustyphoon

### Description

### Testing steps

2023-01-29 10:29 UTC, AprilSylph commented on src/util/_index.json
> +]
We're not using this array anywhere else, so I think we should move it to `preload.js`; the only reason that `src/scripts/_index.json` exists is to avoid duplicating it beween `main.js` and the control panel

2023-01-29 10:32 UTC, AprilSylph requested changes

2023-01-29 10:32 UTC, AprilSylph commented on src/manifest.json
> +      "run_at": "document_start",
We probably shouldn't touch the DOM until the page is in the `interactive` state

```suggestion
      "run_at": "document_end",
```

2023-01-29 10:35 UTC, AprilSylph commented on src/manifest.json
> +    },
🤔 Do separate content scripts for the same addon on the same page get different sandboxes? It would be cool to be able to load all our libraries here...

2023-01-29 10:36 UTC, marcustyphoon commented on src/manifest.json
> +      "run_at": "document_start",
Oh... hm. I will have to see if that actually works!

2023-01-29 10:37 UTC, marcustyphoon commented on src/manifest.json
> +    },
I did it like this just because of the differing `run_at` values; if they're both going to be at `document_end` I don't see why we can't just combine them.

2023-01-29 10:39 UTC, marcustyphoon commented on src/manifest.json
> +    },
(Also, yep, they do; that works if we don't change the `run_at` value and just delay the preload)

2023-01-29 10:40 UTC, AprilSylph requested changes

2023-01-29 10:40 UTC, AprilSylph commented on src/manifest.json
> +      ],
We don't need these exclusions just for preloading - they're in place to prevent passive API calls (think `user.js`) from triggering infinite redirects

```suggestion
```

2023-01-29 10:40 UTC, marcustyphoon commented on src/util/_index.json
> +]
Sure, I'm indifferent either way. Loading an extra JSON file for no actual reason seems silly; on the other hand, having it there makes it clearer that it should be updated if another util file is added.

2023-01-29 10:41 UTC, marcustyphoon commented on src/manifest.json
> +      "run_at": "document_start",
So far it seems to work.

2023-01-29 10:51 UTC, AprilSylph commented on src/manifest.json
> +      "run_at": "document_start",
We might have to change the boot script to run at `document_idle` for this to be reliable, assuming the scripts we specify for preload behave normally (i.e. have to be loaded before the document's state is considered `complete`)

Honestly, I thought we were using `document_idle` already since I don't imagine hydration can ever occur before the document `load` event, but I didn't ever test that, so I might be wrong.

2023-01-29 10:53 UTC, marcustyphoon commented on src/manifest.json
> +      "run_at": "document_start",
Ah, I remember now: in the fully optimized version, I started fetching the script index JSON at `document_start` and could delay stuff until `interactive` using a `waitForDocumentReady()` function. Still wouldn't be 100% guaranteed reliable, I suppose.

Hydration does occur before that, as far as I know, yeah.

2023-01-29 11:04 UTC, AprilSylph commented on src/manifest.json
> +      "run_at": "document_start",
For the sake of reliability I'm willing to entertain the idea of actually delaying boot until the preloading is finished. Would be interesting to see just how much of a difference it makes to boot at `document_idle` with scripts preloaded vs `document_end` without preloading.

2023-01-29 11:14 UTC, AprilSylph commented on src/util/_index.json
> +]
Maybe we should just create a `src/util/README.md` instructing contributors to update the preload file.
Maybe we should have a README for _every_ directory...

(These would both be out of scope for this PR; right now my verdict is "more synchronous code, please")

2023-01-29 11:33 UTC, marcustyphoon commented on src/manifest.json
> +      "run_at": "document_start",
![image](https://user-images.githubusercontent.com/8336245/215322235-6176adae-ef0a-4738-88b4-48a91b5598ff.png)

Man, this whole thing is hard to illustrate without getting out the ol' ms paint or whatever and marking up screenshots. (Screenshot is illustrative only.)

Short version: I poked some things a bunch. With the current unmodified main.js code, `init()` waits on its own script index JSON load after waitForReactLoaded, which puts the import() statements and waterfall later than `document_idle` anyway. Of course, running main.js at `document_idle` would cause that JSON load to begin at that point. And, uh... I dunno, some other things are also true; I may try to summarize this better later :P 

Stepping back, I would randomly ballpark the total difference in time between hydration and xkit load from any of these possibilities at, like, I dunno, 400ms? Do we care?

2023-01-29 11:56 UTC, AprilSylph commented on src/manifest.json
> +      "run_at": "document_start",
I don't care about 400ms. We could probably regain that with further optimisations, but I wouldn't feel bad if we figure out that we can't.

2023-02-15 01:01 UTC, marcustyphoon commented
Okay, as nightpool mentioned... somewhere, I honestly think that setting run_at just doesn't really work that well. MDN says:

> `"document_end"` | Corresponds to `interactive`.

When I put a content script there, though, it gets run way after the `readystatechange` event that corresponds with `document.readyState === interactive`. Maybe that's when the browser starts loading the script file? If so, I mean, that's objectively reasonable, I guess, but also, why suggest that that's when the script will actually get executed, then?

Putting a `readystatechange` listener at the top of `init()`, on the other hand, times everything reliably and consistently as expected.

2023-02-15 02:19 UTC, marcustyphoon commented
Note for posterity: adding `type: 'application/json',` seems to fix the console spam when preloading JSON files for getPreferences. However, since we have no way of knowing if scripts have any preferences at all, this still results in loading a bunch of JSON files for scripts that will never reference them, and those files will spam the console.

2023-02-17 02:30 UTC, marcustyphoon commented
Random tidbits:

>  I don't imagine React hydration can ever occur before the document load event, but I didn't ever test that, so I might be wrong.

I checked for fun; hydration fires after a [stylesheet load event](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#stylesheet_load_events).

I remember someone said something complicated about when exactly a stylesheet counts as loaded (probably on MDN somewhere), but I forget where. If more research needed to be done, though, there's a direction to look in.

> https://www.tumblr.com/transienturl/709284574500438016

Poked a bit more and yep: it seems like the same synchronous event loop invocation contains both the `readyStateChange` **interactive** event handlers and the `DOMContentLoaded` event handlers... but it takes more than half a second (parsing redpop code), the `readyStateChange` handlers are at the beginning, and the `DOMContentLoaded` handlers are at the end, so which event you use to time a resource fetch makes a huge difference!

If the thing one was trying to do was a DOM manipulation, it wouldn't make a difference, of course; the page only gets rendered at the end of all of that parsing, so the time at which the user will see the result is the same. But when the work you're doing is on another thread, the order can matter!

2023-02-22 04:37 UTC, marcustyphoon commented
Fascinating result from loading the extension into Safari 15 on MacOS: the extension consistently fails to load unless the imports really are not all at once, e.g. the old:

```js
for (const scriptName of installedScripts.filter(scriptName => enabledScripts.includes(scriptName))) {
  await runScript(scriptName);
}
```

Apparently there is a Safari bug with multiple simultaneous fetches to a module that uses top-level await. It doesn't seem like the same problem as the Chrome one, but does share a lot of similarities to it? Annoyingly, "make a test copy of XKit Rewritten that does not use top-level await" isn't really a viable testing option.

https://www.tumblr.com/transienturl/709927672316329984/reference-error-cannot-access-uninitialized

2023-02-22 06:13 UTC, marcustyphoon commented
Confirmed that the description of that bug is correct; Safari loads correctly with the unnecessary top level await in Tag Tracking+ removed and no multiple simultaneous imports of the same file with top-level await by prepending:

```js
await Promise.all(['css_map', 'language_data', 'user'].map(async name => {
  const scriptPath = getURL(`/util/${name}.js`);
  await import(scriptPath);
}));
```

(Identical result 16.3 on Ventura on M1 Mac; 15.6.1 on Catalina on Intel.)

Kind of a pain.

2023-02-28 20:44 UTC, marcustyphoon commented
The above message about Safari appears to apply to Chrome as well. It's much harder to trigger, but having legacy XKit loaded at the same time helps.

So, to recap, as far as I can tell:
 - Two scripts importing the same js file at the same time, when the js file has a top-level await, can be problematic depending on timing. This seems to be a webkit bug, affecting both Safari and Chrome on iOS.

Thus we could:
 - Import the top level await utils before loading scripts. The list would effectively be a magic number; we/contributors could forget to update it.
 - Import the top level await utils before loading scripts and use an eslint rule to warn about top level awaits, disabling it on certain files.
 - Import all of the utils before loading scripts (wasted cpu cycles)
 - Don't import scripts simultaneously (much larger loading speed drawback)

In addition to this, we could improve loading speed by:
 - Implementing a timing improvement in main.js that fires events exactly when they should happen
 - Doing that, and also preloading util and script js files. This makes the change when viewed as a whole a loading speed improvement regardless of which option is picked in the first section, I think, probably, don't quote me on that.

2023-02-28 22:04 UTC, AprilSylph commented
So, where are we at now? Preloading doesn't solve the issue across the board? I think you said that on your blog, but you didn't mention it here.

Maybe we _should_ just disallow top-level await in util files. Just exporting promises and allowing the features to top-level await the results is almost as good as exporting results of promises.

2023-02-28 22:26 UTC, marcustyphoon commented
Oh, sorry, to clarify:

> Preloading actually doesn't solve the issue in Chrome?

Yes. (After I installed XKit 7, I got occurrences with the preloading patch loaded.)

> Maybe we should just disallow top-level await in util files. Just exporting promises and allowing the features to top-level await the results is almost as good as exporting results of promises.

For user info, I definitely think it's fine either way. Not being able to use `keyToCss` and `translate` in top-level buildStyle calls sucks though.

2023-02-28 23:16 UTC, AprilSylph commented
It would look a little silly, but think of it as clown makeup for this WebKit bug.

2023-03-01 01:51 UTC, marcustyphoon commented
```js
// util:

const cssMapPromise = inject(async () => window.tumblr.getCssMap());

export const getKeyToClasses = cssMapPromise.then(
  cssMap =>
    /**
     * @param {...string} keys - One or more element source names
     * @returns {string[]} An array of generated classnames from the CSS map
     */
    function (...keys) {
      return keys.flatMap(key => cssMap[key]).filter(Boolean);
    }
);

export const getKeyToCss = getKeyToClasses.then(
  keyToClasses =>
    /**
     * @param {...string} keys - One or more element source names
     * @returns {string} - A CSS :is() selector which targets all elements that match any of the given source names
     */
    function (...keys) {
      const classes = keyToClasses(...keys);
      return `:is(${classes.map(className => `.${className}`).join(', ')})`;
    }
);

// script:

import { getKeyToCss } from '../util/css_map.js';
const keyToCss = await getKeyToCss;
```

```js
// util:

export default inject(async () => window.tumblr.getCssMap()).then(cssMap => {
  /**
   * @param {...string} keys - One or more element source names
   * @returns {string[]} An array of generated classnames from the CSS map
   */
  const keyToClasses = (...keys) => keys.flatMap(key => cssMap[key]).filter(Boolean);

  /**
   * @param {...string} keys - One or more element source names
   * @returns {string} - A CSS :is() selector which targets all elements that match any of the given source names
   */
  const keyToCss = function (...keys) {
    const classes = keyToClasses(...keys);
    return `:is(${classes.map(className => `.${className}`).join(', ')})`;
  };

  return { keyToClasses, keyToCss };
});

// script:
import cssMapPromise from '../util/css_map.js';
const { keyToCss } = await cssMapPromise;
```

Eugh.

2023-08-30 05:07 UTC, marcustyphoon commented
Closing currently-inactive PRs for cleanup.

2023-08-30 05:07 UTC, closed without merging