Mutual Checker: Following icons in blog cards
AprilSylph/XKit-Rewritten pull request #992
Opened 2023-02-21 22:16 UTC by marcustyphoon

todo: rebase

### Description

This is really what I actually wanted the Mutual Checker blog card thing for: the ability to add an icon to blog cards when a user follows you but you don't follow them back as well as when they're a mutual. Oftentimes I'm in a thread somewhere and I see a blog that I think I might recognize, but that I'm not super familiar with as I don't follow them, and being able to see that they're a follower quickly is very convenient.

Obviously this doesn't work if the blog in question is a sideblog, but most of the time when I want this, it works great.

### Testing steps

2026-05-04 08:47 UTC, AprilSylph requested changes

2026-05-04 08:47 UTC, AprilSylph commented on src/features/mutual_checker/index.js
> +        dom('use', { xmlns: 'http://www.w3.org/2000/svg', href: '#ri-user-shared-line' }),
This doesn't work if you don't have Quick Tags or Trim Reblogs enabled.

Maybe we should be using the icons that Tumblr used to use for the Mutuals/Following activity badges? Which ones were those again?

2026-05-08 11:56 UTC, marcustyphoon commented on src/features/mutual_checker/index.js
> +        dom('use', { xmlns: 'http://www.w3.org/2000/svg', href: '#ri-user-shared-line' }),
"Used to" implying that they differed from the current ones, I assume? I vaguely remember this. Were they, like, kinda squareish...?

2026-05-08 11:58 UTC, marcustyphoon commented on src/features/mutual_checker/index.js
> +        dom('use', { xmlns: 'http://www.w3.org/2000/svg', href: '#ri-user-shared-line' }),
`managed-icon__following` isn't it, is it?

2026-05-08 13:24 UTC, AprilSylph commented on src/features/mutual_checker/index.js
> +        dom('use', { xmlns: 'http://www.w3.org/2000/svg', href: '#ri-user-shared-line' }),
"Used to" as in they don't have icons at all anymore:

<img width="380" height="162" alt="image" src="https://github.com/user-attachments/assets/78fac4de-1b18-4d51-87e3-0a917a52c85b" />

2026-05-08 13:29 UTC, AprilSylph commented on src/features/mutual_checker/index.js
> +        dom('use', { xmlns: 'http://www.w3.org/2000/svg', href: '#ri-user-shared-line' }),
I see we still have the icon IDs in Tweaks:

https://github.com/AprilSylph/XKit-Rewritten/blob/f8d496ad0ae57d081b8e2dfa1b1b56b88d8409e0/src/features/tweaks/subtle_activity_mutuals.js#L54-L56

I wonder if the design system icons have equivalents we can update to. The pre-DS icons could be on the chopping block at some point.

2026-05-08 13:38 UTC, AprilSylph commented on src/features/mutual_checker/index.js
> +        dom('use', { xmlns: 'http://www.w3.org/2000/svg', href: '#ri-user-shared-line' }),
Mutuals icon equivalent: `#managed-icon__ds-users-filled-24`
(Or, intended replacement: `#managed-icon__ds-user-mutual-filled`)

Following icon equivalent: `#managed-icon__ds-user-following-filled`

2026-05-08 18:18 UTC, marcustyphoon commented on src/features/mutual_checker/index.js
> +        dom('use', { xmlns: 'http://www.w3.org/2000/svg', href: '#ri-user-shared-line' }),
Ah, you mean the ones that are still currently used in—

—ah, damn, I had forgotten we insert them in that tweak.

2026-05-11 09:07 UTC, AprilSylph approved these changes
Ready to merge after one last thing...

2026-05-11 09:07 UTC, AprilSylph commented on src/features/mutual_checker/index.js
> +        buildSvg('ri-user-shared-line').firstElementChild,
As per the other conversation:

```suggestion
        buildSvg('ri-user-follow-line').firstElementChild,
```

2026-05-11 09:26 UTC, marcustyphoon commented on src/features/mutual_checker/index.js
> +        buildSvg('ri-user-shared-line').firstElementChild,
Ah, so—still using a remix icon icon, but one with a check mark instead of an arrow, matching the iconography with Tumblr's icon that represents a following blog even though it's not currently used anywhere(?), so that it will be consistent if it is.

I think the check mark is slightly less clear as meaning "this user follows you," but neither one of them is actually particularly clear and it's thus not a huge difference.

2026-05-11 10:26 UTC, AprilSylph commented on src/features/mutual_checker/index.js
> +        buildSvg('ri-user-shared-line').firstElementChild,
Yep—if we have to choose one, we should go with the one that doesn't contradict Tumblr. There's lots of ways[^1] for the Tumblr icon to still be part of one's picto-vocabulary[^2], so we can exploit that to make our icon choice seem more intuitive to more people, without it actually being any more intuitive than the alternative.

[^1]: e.g. simply remembering the icon from when it was used by Tumblr previously
  e.g. seeing the icon in older screenshots, circulated via reblogs today
  e.g. using an older mobile app version that still uses the icon
  e.g. using the Tweaks option that inserts the icon
[^2]: Yes, I just made up this term; is there an actual term for this that I'm forgetting?

2026-05-11 10:28 UTC, AprilSylph commented on src/features/mutual_checker/index.js
> +        buildSvg('ri-user-shared-line').firstElementChild,
(Obviously, this line of thinking only works when the two choices are similarly [un]intuitive in a vacuum.)

2026-05-11 10:49 UTC, marcustyphoon commented on src/features/mutual_checker/index.js
> +        buildSvg('ri-user-shared-line').firstElementChild,
> picto-vocabulary
> Yes, I just made up this term; is there an actual term for this that I'm forgetting? 

I asked an AI model for you, and it just said "Noah's Fish." (Was it the worst AI I could find in a few minutes of googling? That's entirely unimportant and I don't know why you would ask that.)

2026-05-12 08:52 UTC, merged